import test from 'node:test';
import assert from 'node:assert/strict';

import { createGeneratedImageAssetStore } from '../src/app/legacy-runtime/features/generated-image-assets.js';

test('stores generated bytes under a user-scoped key and returns a lightweight descriptor', async () => {
  const values = new Map();
  const store = createGeneratedImageAssetStore({
    setItem: async (key, value) => values.set(key, value),
    getItem: async key => values.get(key),
    getUserName: () => 'alice',
    randomUUID: () => 'asset-1'
  });

  const descriptor = await store.save({ b64Json: 'aGVsbG8=', mediaType: 'image/png' });

  assert.deepEqual(descriptor, {
    id: 'asset-1',
    mediaType: 'image/png',
    size: 5,
    storageKey: 'generatedImage:alice:asset-1'
  });
  assert.equal(values.get(descriptor.storageKey) instanceof Blob, true);
  assert.equal(await values.get(descriptor.storageKey).text(), 'hello');
});

test('loads stored images as data URLs for image-to-image references', async () => {
  const blob = new Blob(['hello'], { type: 'image/webp' });
  const store = createGeneratedImageAssetStore({
    setItem: async () => {},
    getItem: async () => blob,
    getUserName: () => 'alice'
  });

  assert.equal(
    await store.getDataUrl({ storageKey: 'generatedImage:alice:asset-1', mediaType: 'image/webp' }),
    'data:image/webp;base64,aGVsbG8='
  );
});

test('keeps the requested aspect ratio on generated image descriptors', async () => {
  const store = createGeneratedImageAssetStore({
    setItem: async () => {},
    getItem: async () => null,
    getUserName: () => 'alice',
    randomUUID: () => 'asset-ratio'
  });

  const descriptor = await store.save({
    b64Json: 'aGVsbG8=',
    mediaType: 'image/png',
    aspectRatio: '16:9'
  });
  assert.equal(descriptor.aspectRatio, '16:9');
});

test('binds an object URL and original download name to generated image elements', async () => {
  const blob = new Blob(['hello'], { type: 'image/png' });
  const attrs = new Map();
  const image = { src: '' };
  const link = { href: '', download: '' };
  const root = {
    querySelectorAll(selector) {
      if (selector === '[data-generated-image-id="asset-1"]') return [image];
      if (selector === '[data-generated-image-download="asset-1"]') return [link];
      return [];
    },
    setAttribute(name, value) { attrs.set(name, value); }
  };
  const store = createGeneratedImageAssetStore({
    setItem: async () => {},
    getItem: async () => blob,
    getUserName: () => 'alice',
    createObjectURL: () => 'blob:asset-1'
  });

  await store.bind(root, [{ id: 'asset-1', storageKey: 'key', mediaType: 'image/png' }]);

  assert.equal(image.src, 'blob:asset-1');
  assert.equal(link.href, 'blob:asset-1');
  assert.equal(link.download, 'astra-generated-asset-1.png');
});
