// Interface texts for Advanced mode (Python in the browser), in the app's
// five interface languages. {name} placeholders are filled by sandboxText.

const TEXTS = Object.freeze({
  'zh-TW': {
    fileModeLabel: '製作方式',
    fileModeStandard: '標準',
    fileModeAdvanced: '進階',
    fileModeStandardNote: '所有模型都能用，速度最快。',
    fileModeAdvancedNote: 'AI 在你的瀏覽器執行 Python，可分析上傳的檔案、精算圖表。第一次使用需下載約 30 MB。',
    fileModeAdvancedReady: 'AI 在你的瀏覽器執行 Python，可分析上傳的檔案、精算圖表。Python 環境已下載。',
    fileModeUnavailable: '目前無法使用進階模式：{reason}',
    fileModeDefaultSetting: '新對話的製作方式',
    fileModeDefaultSettingNote: '進階模式讓 AI 在你的瀏覽器執行 Python；不支援的模型會自動改用標準。',
    sandboxPreparing: '正在準備 Python 環境……',
    sandboxCliPreparing: '正在準備命令工具……',
    sandboxCliInstalling: '正在安裝 {name}……',
    sandboxNetWaiting: '等你回答：要不要允許連到 {host}？',
    sandboxSkippedLarge: '未提供下載：{name}（{size}，超過每個檔案 {limit} 的上限）',
    sandboxSkippedTotal: '未提供下載：{name}（這一步的檔案總量超過上限）',
    sandboxSkippedCount: '未提供下載：{name}（這一步的檔案太多）',
    sandboxSkippedBlocked: '未提供下載：{name}（不允許的檔案類型）',
    sandboxSkippedNotSaved: '未提供下載：{name}（無法保存到雲端空間）',
    sandboxSkippedQuota: '未提供下載：{name}（雲端空間已滿，請先清理）',
    netAskTitle: '命令工具想連到 {host}',
    netAskOnce: '同意這一次',
    netAskAlways: '永遠同意',
    netAskDeny: '拒絕',
    netAskWait: '等你回答，{minutes} 分鐘內沒有回答就當作拒絕。',
    netAnsweredOnce: '已同意這一次：{host}',
    netAnsweredAlways: '已永遠同意：{host}',
    netAnsweredDeny: '已拒絕：{host}',
    netAnsweredTimeout: '沒有及時回答，已拒絕：{host}',
    netAskFailed: '答案沒有送出，請再試一次。',
    sandboxCredentialWaiting: '等你輸入 {tool} 的登入資料……',
    credAskTitle: '{tool} 需要你的登入資料',
    credAskSite: '登入 {site}',
    credAskEnter: '輸入',
    credAskSkip: '先不要',
    credAskWait: '等你輸入，{minutes} 分鐘內沒有輸入就當作沒有提供。',
    credAnsweredSaved: '已儲存 {tool} 的登入資料',
    credAnsweredCancel: '沒有提供 {tool} 的登入資料',
    credAnsweredTimeout: '沒有及時輸入，{tool} 的登入資料沒有提供',
    sandboxDownloading: '正在準備 Python 環境（第一次約 30 MB）…… 已下載 {mb} MB',
    sandboxPackages: '正在載入 Python 套件……',
    sandboxRunning: '正在執行程式：{title}',
    sandboxRunningUntitled: '正在執行程式……',
    sandboxThinking: '正在根據執行結果繼續……',
    sandboxAsking: '正在思考……',
    sandboxFixing: '程式出錯了，正在修正……',
    sandboxWriting: '正在撰寫程式……',
    sandboxNextStep: '正在準備下一步……',
    sandboxContinuedFiles: '已產生 {count} 個檔案，正在繼續……',
    sandboxFinishing: '正在整理產出的檔案……',
    thinkingLive: '正在思考……', thinkingDoneSummary: '思考摘要 · {s} 秒', thinkingDoneRaw: '思考過程 · {s} 秒', thinkingInterrupted: '思考中斷',
    sandboxThought: '思考',
    ledgerThought: '思考完成', ledgerRan: '已執行程式：{title}', ledgerRanUntitled: '已執行程式',
    sandboxDone: '已執行程式 {n} 次',
    processedIn: '處理時間為 {t}',
    copyCode: '複製程式碼',
    sandboxSearching: '正在搜尋網路……',
    processWorking: '執行中',
    processOpenSetting: '處理過程預設展開',
    processOpenHint: '回覆進行時，處理過程預設收成一行「執行中」，點一下才展開；開啟後會直接展開每一步。',
    webSearchingFor: '正在搜尋：{query}',
    webOpeningPage: '正在讀取網頁：{host}',
    skillLoading: '載入技能：{name}',
    skillFileReading: '讀取技能檔案：{path}',
    sourcesSearched: '已搜尋 {n} 個網站',
    sourcesRead: '已讀取 {n} 個網頁',
    citeSources: '{n} 個資料來源',
    sourcesTab: '來源',
    timelineTab: '時間線',
    sourcesPanelCount: '資料來源 · {n}',
    closePanel: '關閉',
    noSourcesInReply: '還沒有資料來源。',
    panelToggle: '時間線與來源',
    timelineYou: '你',
    timelineReply: 'Noureon',
    timelineEmpty: '沒有歷史訊息',
    timelineYourMessage: '（沒有文字）',
    timelineEmptyReply: '（沒有文字）',
    sandboxStopped: '已停止',
    sandboxFailed: '執行失敗',
    sandboxStep: '第 {n} 次',
    sandboxError: '錯誤',
    sandboxOutput: '輸出',
    sandboxProduced: '產生',
    sandboxSeconds: '{s} 秒',
    sandboxTimedOut: '超過時間上限，已停止',
    sandboxOutputTrimmed: '（輸出過長，已省略部分內容）',
    fallbackNotice: '已改用標準模式：{reason}',
    'reason.model-unsupported': '目前的模型不支援執行程式',
    'reason.council': '模型理事會不支援進階模式',
    'reason.learning': '學習模式不支援進階模式',
    'reason.browser-unsupported': '這個瀏覽器無法執行 Python（需要 WebAssembly 與 Web Worker）',
    'reason.sandbox-load-failed': 'Python 環境載入失敗（可能離線或連線被阻擋）',
    'reason.sandbox-crashed': 'Python 環境發生無法恢復的錯誤',
    'reason.search-conflict': '此模型無法同時使用網路搜尋與執行程式'
  },
  en: {
    fileModeLabel: 'Mode',
    fileModeStandard: 'Standard',
    fileModeAdvanced: 'Advanced',
    fileModeStandardNote: 'Works with every model and is the fastest.',
    fileModeAdvancedNote: 'The AI runs Python in your browser to analyse uploaded files and build precise charts. The first use downloads about 30 MB.',
    fileModeAdvancedReady: 'The AI runs Python in your browser to analyse uploaded files and build precise charts. The Python environment is downloaded.',
    fileModeUnavailable: 'Advanced mode is unavailable: {reason}',
    fileModeDefaultSetting: 'Mode for new chats',
    fileModeDefaultSettingNote: 'Advanced mode lets the AI run Python in your browser; models without support switch to Standard automatically.',
    sandboxPreparing: 'Preparing Python…',
    sandboxCliPreparing: 'Preparing the CLI tools…',
    sandboxCliInstalling: 'Installing {name}…',
    sandboxNetWaiting: 'Waiting for your answer: allow {host}?',
    sandboxSkippedLarge: 'Not offered for download: {name} ({size}, over the limit of {limit} per file)',
    sandboxSkippedTotal: 'Not offered for download: {name} (the files of this step are over the total limit)',
    sandboxSkippedCount: 'Not offered for download: {name} (too many files in this step)',
    sandboxSkippedBlocked: 'Not offered for download: {name} (a type of file that is not allowed)',
    sandboxSkippedNotSaved: 'Not offered for download: {name} (it could not be saved to your cloud space)',
    sandboxSkippedQuota: 'Not offered for download: {name} (your cloud space is full: clear some first)',
    netAskTitle: 'A command tool wants to connect to {host}',
    netAskOnce: 'Allow this time',
    netAskAlways: 'Always allow',
    netAskDeny: 'Refuse',
    netAskWait: 'Waiting for your answer. With none in {minutes} minutes the site is refused.',
    netAnsweredOnce: 'Allowed this time: {host}',
    netAnsweredAlways: 'Always allowed: {host}',
    netAnsweredDeny: 'Refused: {host}',
    netAnsweredTimeout: 'No answer in time, refused: {host}',
    netAskFailed: 'The answer could not be sent. Try again.',
    sandboxCredentialWaiting: 'Waiting for your login for {tool}…',
    credAskTitle: '{tool} needs your login',
    credAskSite: 'Sign in to {site}',
    credAskEnter: 'Enter',
    credAskSkip: 'Not now',
    credAskWait: 'Waiting for you. With nothing entered in {minutes} minutes it counts as not provided.',
    credAnsweredSaved: 'Login for {tool} saved',
    credAnsweredCancel: 'Login for {tool} not provided',
    credAnsweredTimeout: 'Not entered in time: login for {tool} not provided',
    sandboxDownloading: 'Preparing Python (about 30 MB the first time)… {mb} MB downloaded',
    sandboxPackages: 'Loading Python packages…',
    sandboxRunning: 'Running code: {title}',
    sandboxRunningUntitled: 'Running code…',
    sandboxThinking: 'Continuing from the results…',
    sandboxAsking: 'Thinking…',
    sandboxFixing: 'The code failed; fixing it…',
    sandboxWriting: 'Writing the code…',
    sandboxNextStep: 'Preparing the next step…',
    sandboxContinuedFiles: '{count} file(s) made; continuing…',
    sandboxFinishing: 'Preparing the files…',
    thinkingLive: 'Thinking…', thinkingDoneSummary: 'Thinking summary · {s}s', thinkingDoneRaw: 'Thinking · {s}s', thinkingInterrupted: 'Thinking interrupted',
    sandboxThought: 'Thinking',
    ledgerThought: 'Finished thinking', ledgerRan: 'Ran code: {title}', ledgerRanUntitled: 'Ran code',
    sandboxDone: 'Ran code {n} times',
    processedIn: 'Processed for {t}',
    copyCode: 'Copy code',
    sandboxSearching: 'Searching the web…',
    processWorking: 'Working',
    processOpenSetting: 'Show the steps by default',
    processOpenHint: 'While a reply is made, its steps are folded into one line, "Working", that opens when tapped. Turn this on to have them open.',
    webSearchingFor: 'Searching: {query}',
    webOpeningPage: 'Reading page: {host}',
    skillLoading: 'Loading skill: {name}',
    skillFileReading: 'Reading skill file: {path}',
    sourcesSearched: 'Searched {n} sites',
    sourcesRead: 'Read {n} pages',
    citeSources: '{n} sources',
    sourcesTab: 'Sources',
    timelineTab: 'Timeline',
    sourcesPanelCount: 'Sources · {n}',
    closePanel: 'Close',
    noSourcesInReply: 'No sources yet.',
    panelToggle: 'Timeline and sources',
    timelineYou: 'You',
    timelineReply: 'Noureon',
    timelineEmpty: 'No messages yet',
    timelineYourMessage: '(no text)',
    timelineEmptyReply: '(no text)',
    sandboxStopped: 'Stopped',
    sandboxFailed: 'Run failed',
    sandboxStep: 'Run {n}',
    sandboxError: 'Error',
    sandboxOutput: 'Output',
    sandboxProduced: 'Created',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Stopped at the time limit',
    sandboxOutputTrimmed: '(Output too long; part of it is left out)',
    fallbackNotice: 'Switched to Standard mode: {reason}',
    'reason.model-unsupported': 'the current model cannot run code',
    'reason.council': 'the model council does not support Advanced mode',
    'reason.learning': 'learning mode does not support Advanced mode',
    'reason.browser-unsupported': 'this browser cannot run Python (it needs WebAssembly and Web Workers)',
    'reason.sandbox-load-failed': 'Python could not be loaded (you may be offline or the connection is blocked)',
    'reason.sandbox-crashed': 'the Python environment hit an error it cannot recover from',
    'reason.search-conflict': 'this model cannot use web search and run code at the same time'
  },
  fr: {
    fileModeLabel: 'Mode',
    fileModeStandard: 'Standard',
    fileModeAdvanced: 'Avancé',
    fileModeStandardNote: 'Fonctionne avec tous les modèles et c’est le plus rapide.',
    fileModeAdvancedNote: 'L’IA exécute Python dans votre navigateur pour analyser les fichiers envoyés et créer des graphiques précis. La première utilisation télécharge environ 30 Mo.',
    fileModeAdvancedReady: 'L’IA exécute Python dans votre navigateur pour analyser les fichiers envoyés et créer des graphiques précis. L’environnement Python est téléchargé.',
    fileModeUnavailable: 'Le mode Avancé est indisponible : {reason}',
    fileModeDefaultSetting: 'Mode des nouvelles conversations',
    fileModeDefaultSettingNote: 'Le mode Avancé permet à l’IA d’exécuter Python dans votre navigateur ; les modèles incompatibles passent automatiquement en mode Standard.',
    sandboxPreparing: 'Préparation de Python…',
    sandboxCliPreparing: 'Préparation des outils CLI…',
    sandboxCliInstalling: 'Installation de {name}…',
    sandboxNetWaiting: 'En attente de votre réponse : autoriser {host} ?',
    sandboxSkippedLarge: 'Non proposé au téléchargement : {name} ({size}, au-delà de la limite de {limit} par fichier)',
    sandboxSkippedTotal: 'Non proposé au téléchargement : {name} (les fichiers de cette étape dépassent la limite totale)',
    sandboxSkippedCount: 'Non proposé au téléchargement : {name} (trop de fichiers dans cette étape)',
    sandboxSkippedBlocked: 'Non proposé au téléchargement : {name} (type de fichier non autorisé)',
    sandboxSkippedNotSaved: 'Non proposé au téléchargement : {name} (impossible de l’enregistrer dans votre espace cloud)',
    sandboxSkippedQuota: 'Non proposé au téléchargement : {name} (votre espace cloud est plein : faites de la place)',
    netAskTitle: 'Un outil en ligne de commande veut se connecter à {host}',
    netAskOnce: 'Autoriser cette fois',
    netAskAlways: 'Toujours autoriser',
    netAskDeny: 'Refuser',
    netAskWait: 'En attente de votre réponse. Sans réponse en {minutes} minutes, le site est refusé.',
    netAnsweredOnce: 'Autorisé cette fois : {host}',
    netAnsweredAlways: 'Toujours autorisé : {host}',
    netAnsweredDeny: 'Refusé : {host}',
    netAnsweredTimeout: 'Pas de réponse à temps, refusé : {host}',
    netAskFailed: 'La réponse n’a pas pu être envoyée. Réessayez.',
    sandboxCredentialWaiting: 'En attente de votre connexion pour {tool}…',
    credAskTitle: '{tool} a besoin de votre connexion',
    credAskSite: 'Connexion à {site}',
    credAskEnter: 'Saisir',
    credAskSkip: 'Pas maintenant',
    credAskWait: 'En attente. Sans saisie en {minutes} minutes, c’est considéré comme non fourni.',
    credAnsweredSaved: 'Connexion pour {tool} enregistrée',
    credAnsweredCancel: 'Connexion pour {tool} non fournie',
    credAnsweredTimeout: 'Non saisie à temps : connexion pour {tool} non fournie',
    sandboxDownloading: 'Préparation de Python (environ 30 Mo la première fois)… {mb} Mo téléchargés',
    sandboxPackages: 'Chargement des modules Python…',
    sandboxRunning: 'Exécution du code : {title}',
    sandboxRunningUntitled: 'Exécution du code…',
    sandboxThinking: 'Suite à partir des résultats…',
    sandboxAsking: 'Réflexion…',
    sandboxFixing: 'Le code a échoué ; correction en cours…',
    sandboxWriting: 'Écriture du code…',
    sandboxNextStep: 'Préparation de l’étape suivante…',
    sandboxContinuedFiles: '{count} fichier(s) créé(s) ; suite…',
    sandboxFinishing: 'Préparation des fichiers…',
    thinkingLive: 'Réflexion…', thinkingDoneSummary: 'Résumé de la réflexion · {s} s', thinkingDoneRaw: 'Réflexion · {s} s', thinkingInterrupted: 'Réflexion interrompue',
    sandboxThought: 'Réflexion',
    ledgerThought: 'Réflexion terminée', ledgerRan: 'Code exécuté : {title}', ledgerRanUntitled: 'Code exécuté',
    sandboxDone: 'Code exécuté {n} fois',
    processedIn: 'Traité en {t}',
    copyCode: 'Copier le code',
    sandboxSearching: 'Recherche sur le web…',
    processWorking: 'En cours',
    processOpenSetting: 'Afficher les étapes par défaut',
    processOpenHint: 'Pendant une réponse, ses étapes sont réduites à une ligne, « En cours », qui s’ouvre au toucher. Activez pour les voir ouvertes.',
    webSearchingFor: 'Recherche : {query}',
    webOpeningPage: 'Lecture de la page : {host}',
    skillLoading: 'Chargement de la compétence : {name}',
    skillFileReading: 'Lecture du fichier de la compétence : {path}',
    sourcesSearched: '{n} sites consultés',
    sourcesRead: '{n} pages lues',
    citeSources: '{n} sources',
    sourcesTab: 'Sources',
    timelineTab: 'Chronologie',
    sourcesPanelCount: 'Sources · {n}',
    closePanel: 'Fermer',
    noSourcesInReply: 'Pas encore de sources.',
    panelToggle: 'Chronologie et sources',
    timelineYou: 'Vous',
    timelineReply: 'Noureon',
    timelineEmpty: 'Aucun message',
    timelineYourMessage: '(sans texte)',
    timelineEmptyReply: '(sans texte)',
    sandboxStopped: 'Arrêté',
    sandboxFailed: 'Échec de l’exécution',
    sandboxStep: 'Exécution {n}',
    sandboxError: 'Erreur',
    sandboxOutput: 'Sortie',
    sandboxProduced: 'Créé',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Arrêté à la limite de temps',
    sandboxOutputTrimmed: '(Sortie trop longue ; une partie est omise)',
    fallbackNotice: 'Passé en mode Standard : {reason}',
    'reason.model-unsupported': 'le modèle actuel ne peut pas exécuter de code',
    'reason.council': 'le conseil de modèles ne prend pas en charge le mode Avancé',
    'reason.learning': 'le mode apprentissage ne prend pas en charge le mode Avancé',
    'reason.browser-unsupported': 'ce navigateur ne peut pas exécuter Python (WebAssembly et Web Workers sont nécessaires)',
    'reason.sandbox-load-failed': 'Python n’a pas pu être chargé (vous êtes peut-être hors ligne ou la connexion est bloquée)',
    'reason.sandbox-crashed': 'l’environnement Python a rencontré une erreur irrécupérable',
    'reason.search-conflict': 'ce modèle ne peut pas utiliser la recherche web et exécuter du code en même temps'
  },
  ru: {
    fileModeLabel: 'Режим',
    fileModeStandard: 'Стандартный',
    fileModeAdvanced: 'Расширенный',
    fileModeStandardNote: 'Работает со всеми моделями и быстрее всего.',
    fileModeAdvancedNote: 'ИИ запускает Python в вашем браузере, чтобы анализировать загруженные файлы и строить точные графики. При первом использовании загружается около 30 МБ.',
    fileModeAdvancedReady: 'ИИ запускает Python в вашем браузере, чтобы анализировать загруженные файлы и строить точные графики. Среда Python загружена.',
    fileModeUnavailable: 'Расширенный режим недоступен: {reason}',
    fileModeDefaultSetting: 'Режим новых чатов',
    fileModeDefaultSettingNote: 'В расширенном режиме ИИ запускает Python в вашем браузере; модели без поддержки автоматически переходят на стандартный режим.',
    sandboxPreparing: 'Подготовка Python…',
    sandboxCliPreparing: 'Подготовка CLI-инструментов…',
    sandboxCliInstalling: 'Установка {name}…',
    sandboxNetWaiting: 'Ждём вашего ответа: разрешить {host}?',
    sandboxSkippedLarge: 'Не предложен для скачивания: {name} ({size}, больше лимита {limit} на файл)',
    sandboxSkippedTotal: 'Не предложен для скачивания: {name} (файлы этого шага превышают общий лимит)',
    sandboxSkippedCount: 'Не предложен для скачивания: {name} (слишком много файлов в этом шаге)',
    sandboxSkippedBlocked: 'Не предложен для скачивания: {name} (недопустимый тип файла)',
    sandboxSkippedNotSaved: 'Не предложен для скачивания: {name} (не удалось сохранить в облачное хранилище)',
    sandboxSkippedQuota: 'Не предложен для скачивания: {name} (облачное хранилище заполнено: освободите место)',
    netAskTitle: 'Инструмент командной строки хочет подключиться к {host}',
    netAskOnce: 'Разрешить на этот раз',
    netAskAlways: 'Всегда разрешать',
    netAskDeny: 'Отказать',
    netAskWait: 'Ждём вашего ответа. Если его не будет в течение {minutes} мин., сайт будет отклонён.',
    netAnsweredOnce: 'Разрешено на этот раз: {host}',
    netAnsweredAlways: 'Всегда разрешено: {host}',
    netAnsweredDeny: 'Отклонено: {host}',
    netAnsweredTimeout: 'Ответа не было, отклонено: {host}',
    netAskFailed: 'Не удалось отправить ответ. Попробуйте ещё раз.',
    sandboxCredentialWaiting: 'Ждём ваши данные для входа в {tool}…',
    credAskTitle: '{tool} нужны ваши данные для входа',
    credAskSite: 'Вход на {site}',
    credAskEnter: 'Ввести',
    credAskSkip: 'Не сейчас',
    credAskWait: 'Ждём вас. Если за {minutes} мин. ничего не введено, данные считаются не предоставленными.',
    credAnsweredSaved: 'Данные для входа в {tool} сохранены',
    credAnsweredCancel: 'Данные для входа в {tool} не предоставлены',
    credAnsweredTimeout: 'Не введены вовремя: данные для входа в {tool} не предоставлены',
    sandboxDownloading: 'Подготовка Python (около 30 МБ в первый раз)… загружено {mb} МБ',
    sandboxPackages: 'Загрузка пакетов Python…',
    sandboxRunning: 'Выполнение кода: {title}',
    sandboxRunningUntitled: 'Выполнение кода…',
    sandboxThinking: 'Продолжение по результатам…',
    sandboxAsking: 'Размышление…',
    sandboxFixing: 'Код завершился ошибкой; исправление…',
    sandboxWriting: 'Написание кода…',
    sandboxNextStep: 'Подготовка следующего шага…',
    sandboxContinuedFiles: 'Создано файлов: {count}; продолжение…',
    sandboxFinishing: 'Подготовка файлов…',
    thinkingLive: 'Размышление…', thinkingDoneSummary: 'Краткое изложение размышлений · {s} с', thinkingDoneRaw: 'Размышление · {s} с', thinkingInterrupted: 'Размышление прервано',
    sandboxThought: 'Ход мысли',
    ledgerThought: 'Размышление завершено', ledgerRan: 'Код выполнен: {title}', ledgerRanUntitled: 'Код выполнен',
    sandboxDone: 'Код выполнен {n} раз(а)',
    processedIn: 'Время обработки: {t}',
    copyCode: 'Копировать код',
    sandboxSearching: 'Поиск в интернете…',
    processWorking: 'В работе',
    processOpenSetting: 'Показывать шаги по умолчанию',
    processOpenHint: 'Пока готовится ответ, его шаги свёрнуты в одну строку «В работе», которая раскрывается по нажатию. Включите, чтобы шаги были раскрыты.',
    webSearchingFor: 'Поиск: {query}',
    webOpeningPage: 'Чтение страницы: {host}',
    skillLoading: 'Загрузка навыка: {name}',
    skillFileReading: 'Чтение файла навыка: {path}',
    sourcesSearched: 'Просмотрено сайтов: {n}',
    sourcesRead: 'Прочитано страниц: {n}',
    citeSources: 'Источников: {n}',
    sourcesTab: 'Источники',
    timelineTab: 'Хронология',
    sourcesPanelCount: 'Источники · {n}',
    closePanel: 'Закрыть',
    noSourcesInReply: 'Источников пока нет.',
    panelToggle: 'Хронология и источники',
    timelineYou: 'Вы',
    timelineReply: 'Noureon',
    timelineEmpty: 'Нет сообщений',
    timelineYourMessage: '(без текста)',
    timelineEmptyReply: '(без текста)',
    sandboxStopped: 'Остановлено',
    sandboxFailed: 'Ошибка выполнения',
    sandboxStep: 'Запуск {n}',
    sandboxError: 'Ошибка',
    sandboxOutput: 'Вывод',
    sandboxProduced: 'Создано',
    sandboxSeconds: '{s} с',
    sandboxTimedOut: 'Остановлено по лимиту времени',
    sandboxOutputTrimmed: '(Вывод слишком длинный; часть пропущена)',
    fallbackNotice: 'Переключено на стандартный режим: {reason}',
    'reason.model-unsupported': 'текущая модель не умеет выполнять код',
    'reason.council': 'совет моделей не поддерживает расширенный режим',
    'reason.learning': 'режим обучения не поддерживает расширенный режим',
    'reason.browser-unsupported': 'этот браузер не может запускать Python (нужны WebAssembly и Web Workers)',
    'reason.sandbox-load-failed': 'не удалось загрузить Python (возможно, нет сети или соединение заблокировано)',
    'reason.sandbox-crashed': 'в среде Python произошла неустранимая ошибка',
    'reason.search-conflict': 'эта модель не может одновременно искать в интернете и выполнять код'
  },
  es: {
    fileModeLabel: 'Modo',
    fileModeStandard: 'Estándar',
    fileModeAdvanced: 'Avanzado',
    fileModeStandardNote: 'Funciona con todos los modelos y es el más rápido.',
    fileModeAdvancedNote: 'La IA ejecuta Python en tu navegador para analizar los archivos subidos y crear gráficos precisos. El primer uso descarga unos 30 MB.',
    fileModeAdvancedReady: 'La IA ejecuta Python en tu navegador para analizar los archivos subidos y crear gráficos precisos. El entorno de Python ya está descargado.',
    fileModeUnavailable: 'El modo Avanzado no está disponible: {reason}',
    fileModeDefaultSetting: 'Modo de los chats nuevos',
    fileModeDefaultSettingNote: 'El modo Avanzado permite que la IA ejecute Python en tu navegador; los modelos sin compatibilidad pasan al modo Estándar automáticamente.',
    sandboxPreparing: 'Preparando Python…',
    sandboxCliPreparing: 'Preparando las herramientas CLI…',
    sandboxCliInstalling: 'Instalando {name}…',
    sandboxNetWaiting: 'Esperando tu respuesta: ¿permitir {host}?',
    sandboxSkippedLarge: 'No se ofrece para descargar: {name} ({size}, supera el límite de {limit} por archivo)',
    sandboxSkippedTotal: 'No se ofrece para descargar: {name} (los archivos de este paso superan el límite total)',
    sandboxSkippedCount: 'No se ofrece para descargar: {name} (demasiados archivos en este paso)',
    sandboxSkippedBlocked: 'No se ofrece para descargar: {name} (tipo de archivo no permitido)',
    sandboxSkippedNotSaved: 'No se ofrece para descargar: {name} (no se pudo guardar en tu espacio en la nube)',
    sandboxSkippedQuota: 'No se ofrece para descargar: {name} (tu espacio en la nube está lleno: libera espacio)',
    netAskTitle: 'Una herramienta de línea de comandos quiere conectarse a {host}',
    netAskOnce: 'Permitir esta vez',
    netAskAlways: 'Permitir siempre',
    netAskDeny: 'Rechazar',
    netAskWait: 'Esperando tu respuesta. Si no hay ninguna en {minutes} minutos, el sitio se rechaza.',
    netAnsweredOnce: 'Permitido esta vez: {host}',
    netAnsweredAlways: 'Permitido siempre: {host}',
    netAnsweredDeny: 'Rechazado: {host}',
    netAnsweredTimeout: 'Sin respuesta a tiempo, rechazado: {host}',
    netAskFailed: 'No se pudo enviar la respuesta. Inténtalo de nuevo.',
    sandboxCredentialWaiting: 'Esperando tu inicio de sesión para {tool}…',
    credAskTitle: '{tool} necesita tu inicio de sesión',
    credAskSite: 'Iniciar sesión en {site}',
    credAskEnter: 'Introducir',
    credAskSkip: 'Ahora no',
    credAskWait: 'Esperándote. Si no introduces nada en {minutes} minutos, cuenta como no proporcionado.',
    credAnsweredSaved: 'Inicio de sesión de {tool} guardado',
    credAnsweredCancel: 'Inicio de sesión de {tool} no proporcionado',
    credAnsweredTimeout: 'No introducido a tiempo: inicio de sesión de {tool} no proporcionado',
    sandboxDownloading: 'Preparando Python (unos 30 MB la primera vez)… {mb} MB descargados',
    sandboxPackages: 'Cargando paquetes de Python…',
    sandboxRunning: 'Ejecutando código: {title}',
    sandboxRunningUntitled: 'Ejecutando código…',
    sandboxThinking: 'Continuando a partir de los resultados…',
    sandboxAsking: 'Pensando…',
    sandboxFixing: 'El código falló; corrigiéndolo…',
    sandboxWriting: 'Escribiendo el código…',
    sandboxNextStep: 'Preparando el siguiente paso…',
    sandboxContinuedFiles: '{count} archivo(s) creado(s); continuando…',
    sandboxFinishing: 'Preparando los archivos…',
    thinkingLive: 'Pensando…', thinkingDoneSummary: 'Resumen del razonamiento · {s} s', thinkingDoneRaw: 'Razonamiento · {s} s', thinkingInterrupted: 'Razonamiento interrumpido',
    sandboxThought: 'Razonamiento',
    ledgerThought: 'Pensamiento terminado', ledgerRan: 'Código ejecutado: {title}', ledgerRanUntitled: 'Código ejecutado',
    sandboxDone: 'Código ejecutado {n} veces',
    processedIn: 'Procesado en {t}',
    copyCode: 'Copiar código',
    sandboxSearching: 'Buscando en la web…',
    processWorking: 'En curso',
    processOpenSetting: 'Mostrar los pasos por defecto',
    processOpenHint: 'Mientras se prepara una respuesta, sus pasos se pliegan en una línea, «En curso», que se abre al tocarla. Actívelo para verlos abiertos.',
    webSearchingFor: 'Buscando: {query}',
    webOpeningPage: 'Leyendo la página: {host}',
    skillLoading: 'Cargando la habilidad: {name}',
    skillFileReading: 'Leyendo el archivo de la habilidad: {path}',
    sourcesSearched: '{n} sitios consultados',
    sourcesRead: '{n} páginas leídas',
    citeSources: '{n} fuentes',
    sourcesTab: 'Fuentes',
    timelineTab: 'Cronología',
    sourcesPanelCount: 'Fuentes · {n}',
    closePanel: 'Cerrar',
    noSourcesInReply: 'Aún no hay fuentes.',
    panelToggle: 'Cronología y fuentes',
    timelineYou: 'Tú',
    timelineReply: 'Noureon',
    timelineEmpty: 'Aún no hay mensajes',
    timelineYourMessage: '(sin texto)',
    timelineEmptyReply: '(sin texto)',
    sandboxStopped: 'Detenido',
    sandboxFailed: 'Error de ejecución',
    sandboxStep: 'Ejecución {n}',
    sandboxError: 'Error',
    sandboxOutput: 'Salida',
    sandboxProduced: 'Creado',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Detenido al alcanzar el límite de tiempo',
    sandboxOutputTrimmed: '(Salida demasiado larga; se omite una parte)',
    fallbackNotice: 'Se cambió al modo Estándar: {reason}',
    'reason.model-unsupported': 'el modelo actual no puede ejecutar código',
    'reason.council': 'el consejo de modelos no admite el modo Avanzado',
    'reason.learning': 'el modo de aprendizaje no admite el modo Avanzado',
    'reason.browser-unsupported': 'este navegador no puede ejecutar Python (necesita WebAssembly y Web Workers)',
    'reason.sandbox-load-failed': 'no se pudo cargar Python (puede que no haya conexión o que esté bloqueada)',
    'reason.sandbox-crashed': 'el entorno de Python tuvo un error del que no puede recuperarse',
    'reason.search-conflict': 'este modelo no puede usar la búsqueda web y ejecutar código a la vez'
  }
});

export const SANDBOX_TEXT_LANGUAGES = Object.freeze(Object.keys(TEXTS));
export const SANDBOX_TEXT_KEYS = Object.freeze(Object.keys(TEXTS['zh-TW']));

export function sandboxText(language, key, values = {}) {
  const table = TEXTS[language] || TEXTS['zh-TW'];
  const template = table[key] ?? TEXTS['zh-TW'][key] ?? key;
  return template.replace(/\{(\w+)\}/g, (match, name) => (name in values ? String(values[name]) : match));
}

export const sandboxTextsFor = (language) => TEXTS[language] || TEXTS['zh-TW'];

/** The row of the step list for a call about a skill (loader.noteFor in data/skill-tool.js): the skill being loaded, or one of its files being read. */
export const skillStepEvent = (language, note) => (note ? { type: 'skill', name: note.name, ...(note.path ? { path: note.path } : {}), label: sandboxText(language, note.path ? 'skillFileReading' : 'skillLoading', note) } : null);

/** The row of the step list for a call of any loader: the loader's own (the connectors') or the one of a skill. */
export const loaderStepEvent = (loader, call, language) => loader.stepEvent?.(call, language) ?? skillStepEvent(language, loader.noteFor(call));

const SKIPPED_KEYS = Object.freeze({ 'file-too-large': 'sandboxSkippedLarge', 'total-too-large': 'sandboxSkippedTotal', 'too-many-files': 'sandboxSkippedCount', 'blocked-type': 'sandboxSkippedBlocked', 'not-saved': 'sandboxSkippedNotSaved', quota: 'sandboxSkippedQuota' });
const megabytes = (bytes) => `${Math.max(1, Math.round(Number(bytes) / (1024 * 1024)))} MB`;

/** The line that says a file was made but not offered for download, and why ({ name, reason, size?, limit? } as the sandbox reports it). */
export function skippedFileText(language, file) {
  const key = SKIPPED_KEYS[file?.reason] || 'sandboxSkippedNotSaved';
  return sandboxText(language, key, { name: String(file?.name || ''), size: file?.size ? megabytes(file.size) : '', limit: file?.limit ? megabytes(file.limit) : '' });
}
