// Interface texts for Advanced mode (Python in the browser), in the app's
// five interface languages. {name} placeholders are filled by sandboxText.

const TEXTS = Object.freeze({
  'zh-TW': {
    fileModeLabel: '製作方式',
    fileModeStandard: '標準',
    fileModeAdvanced: '進階',
    fileModeStandardNote: '所有模型都能用，速度最快。',
    fileModeAdvancedNote: 'AI 在你的瀏覽器執行 Python，可分析上傳的檔案、精算圖表。第一次使用需下載約 30 MB。',
    fileModeAdvancedReady: 'AI 在你的瀏覽器執行 Python，可分析上傳的檔案、精算圖表。Python 環境已下載。',
    fileModeUnavailable: '目前無法使用進階模式：{reason}',
    fileModeDefaultSetting: '新對話的製作方式',
    fileModeDefaultSettingNote: '進階模式讓 AI 在你的瀏覽器執行 Python；不支援的模型會自動改用標準。',
    sandboxPreparing: '正在準備 Python 環境……',
    sandboxDownloading: '正在準備 Python 環境（第一次約 30 MB）…… 已下載 {mb} MB',
    sandboxPackages: '正在載入 Python 套件……',
    sandboxRunning: '正在執行程式：{title}',
    sandboxRunningUntitled: '正在執行程式……',
    sandboxThinking: '正在根據執行結果繼續……',
    sandboxAsking: '正在思考……',
    sandboxFixing: '程式出錯了，正在修正……',
    sandboxWriting: '正在撰寫程式……',
    sandboxNextStep: '正在準備下一步……',
    sandboxContinuedFiles: '已產生 {count} 個檔案，正在繼續……',
    sandboxFinishing: '正在整理產出的檔案……',
    thinkingLive: '正在思考……', thinkingDoneSummary: '思考摘要 · {s} 秒', thinkingDoneRaw: '思考過程 · {s} 秒', thinkingInterrupted: '思考中斷',
    sandboxThought: '思考',
    ledgerThought: '思考完成', ledgerRan: '已執行程式：{title}', ledgerRanUntitled: '已執行程式',
    sandboxDone: '已執行程式 {n} 次',
    processedIn: '處理時間為 {t}',
    copyCode: '複製程式碼',
    sandboxSearching: '正在搜尋網路……',
    processWorking: '執行中',
    processOpenSetting: '處理過程預設展開',
    processOpenHint: '回覆進行時，處理過程預設收成一行「執行中」，點一下才展開；開啟後會直接展開每一步。',
    webSearchingFor: '正在搜尋：{query}',
    webOpeningPage: '正在讀取網頁：{host}',
    sourcesSearched: '已搜尋 {n} 個網站',
    sourcesRead: '已讀取 {n} 個網頁',
    citeSources: '{n} 個資料來源',
    sourcesTab: '來源',
    timelineTab: '時間線',
    sourcesPanelCount: '資料來源 · {n}',
    closePanel: '關閉',
    noSourcesInReply: '這則回覆沒有來源。',
    timelineYou: '你',
    timelineReply: 'Noureon',
    timelineEmpty: '沒有歷史訊息',
    timelineYourMessage: '（沒有文字）',
    timelineEmptyReply: '（沒有文字）',
    sandboxStopped: '已停止',
    sandboxFailed: '執行失敗',
    sandboxStep: '第 {n} 次',
    sandboxError: '錯誤',
    sandboxOutput: '輸出',
    sandboxProduced: '產生',
    sandboxSeconds: '{s} 秒',
    sandboxTimedOut: '超過時間上限，已停止',
    sandboxOutputTrimmed: '（輸出過長，已省略部分內容）',
    fallbackNotice: '已改用標準模式：{reason}',
    'reason.model-unsupported': '目前的模型不支援執行程式',
    'reason.council': '模型理事會不支援進階模式',
    'reason.learning': '學習模式不支援進階模式',
    'reason.browser-unsupported': '這個瀏覽器無法執行 Python（需要 WebAssembly 與 Web Worker）',
    'reason.sandbox-load-failed': 'Python 環境載入失敗（可能離線或連線被阻擋）',
    'reason.sandbox-crashed': 'Python 環境發生無法恢復的錯誤',
    'reason.search-conflict': '此模型無法同時使用網路搜尋與執行程式'
  },
  en: {
    fileModeLabel: 'Mode',
    fileModeStandard: 'Standard',
    fileModeAdvanced: 'Advanced',
    fileModeStandardNote: 'Works with every model and is the fastest.',
    fileModeAdvancedNote: 'The AI runs Python in your browser to analyse uploaded files and build precise charts. The first use downloads about 30 MB.',
    fileModeAdvancedReady: 'The AI runs Python in your browser to analyse uploaded files and build precise charts. The Python environment is downloaded.',
    fileModeUnavailable: 'Advanced mode is unavailable: {reason}',
    fileModeDefaultSetting: 'Mode for new chats',
    fileModeDefaultSettingNote: 'Advanced mode lets the AI run Python in your browser; models without support switch to Standard automatically.',
    sandboxPreparing: 'Preparing Python…',
    sandboxDownloading: 'Preparing Python (about 30 MB the first time)… {mb} MB downloaded',
    sandboxPackages: 'Loading Python packages…',
    sandboxRunning: 'Running code: {title}',
    sandboxRunningUntitled: 'Running code…',
    sandboxThinking: 'Continuing from the results…',
    sandboxAsking: 'Thinking…',
    sandboxFixing: 'The code failed; fixing it…',
    sandboxWriting: 'Writing the code…',
    sandboxNextStep: 'Preparing the next step…',
    sandboxContinuedFiles: '{count} file(s) made; continuing…',
    sandboxFinishing: 'Preparing the files…',
    thinkingLive: 'Thinking…', thinkingDoneSummary: 'Thinking summary · {s}s', thinkingDoneRaw: 'Thinking · {s}s', thinkingInterrupted: 'Thinking interrupted',
    sandboxThought: 'Thinking',
    ledgerThought: 'Finished thinking', ledgerRan: 'Ran code: {title}', ledgerRanUntitled: 'Ran code',
    sandboxDone: 'Ran code {n} times',
    processedIn: 'Processed for {t}',
    copyCode: 'Copy code',
    sandboxSearching: 'Searching the web…',
    processWorking: 'Working',
    processOpenSetting: 'Show the steps by default',
    processOpenHint: 'While a reply is made, its steps are folded into one line, "Working", that opens when tapped. Turn this on to have them open.',
    webSearchingFor: 'Searching: {query}',
    webOpeningPage: 'Reading page: {host}',
    sourcesSearched: 'Searched {n} sites',
    sourcesRead: 'Read {n} pages',
    citeSources: '{n} sources',
    sourcesTab: 'Sources',
    timelineTab: 'Timeline',
    sourcesPanelCount: 'Sources · {n}',
    closePanel: 'Close',
    noSourcesInReply: 'This reply has no sources.',
    timelineYou: 'You',
    timelineReply: 'Noureon',
    timelineEmpty: 'No messages yet',
    timelineYourMessage: '(no text)',
    timelineEmptyReply: '(no text)',
    sandboxStopped: 'Stopped',
    sandboxFailed: 'Run failed',
    sandboxStep: 'Run {n}',
    sandboxError: 'Error',
    sandboxOutput: 'Output',
    sandboxProduced: 'Created',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Stopped at the time limit',
    sandboxOutputTrimmed: '(Output too long; part of it is left out)',
    fallbackNotice: 'Switched to Standard mode: {reason}',
    'reason.model-unsupported': 'the current model cannot run code',
    'reason.council': 'the model council does not support Advanced mode',
    'reason.learning': 'learning mode does not support Advanced mode',
    'reason.browser-unsupported': 'this browser cannot run Python (it needs WebAssembly and Web Workers)',
    'reason.sandbox-load-failed': 'Python could not be loaded (you may be offline or the connection is blocked)',
    'reason.sandbox-crashed': 'the Python environment hit an error it cannot recover from',
    'reason.search-conflict': 'this model cannot use web search and run code at the same time'
  },
  fr: {
    fileModeLabel: 'Mode',
    fileModeStandard: 'Standard',
    fileModeAdvanced: 'Avancé',
    fileModeStandardNote: 'Fonctionne avec tous les modèles et c’est le plus rapide.',
    fileModeAdvancedNote: 'L’IA exécute Python dans votre navigateur pour analyser les fichiers envoyés et créer des graphiques précis. La première utilisation télécharge environ 30 Mo.',
    fileModeAdvancedReady: 'L’IA exécute Python dans votre navigateur pour analyser les fichiers envoyés et créer des graphiques précis. L’environnement Python est téléchargé.',
    fileModeUnavailable: 'Le mode Avancé est indisponible : {reason}',
    fileModeDefaultSetting: 'Mode des nouvelles conversations',
    fileModeDefaultSettingNote: 'Le mode Avancé permet à l’IA d’exécuter Python dans votre navigateur ; les modèles incompatibles passent automatiquement en mode Standard.',
    sandboxPreparing: 'Préparation de Python…',
    sandboxDownloading: 'Préparation de Python (environ 30 Mo la première fois)… {mb} Mo téléchargés',
    sandboxPackages: 'Chargement des modules Python…',
    sandboxRunning: 'Exécution du code : {title}',
    sandboxRunningUntitled: 'Exécution du code…',
    sandboxThinking: 'Suite à partir des résultats…',
    sandboxAsking: 'Réflexion…',
    sandboxFixing: 'Le code a échoué ; correction en cours…',
    sandboxWriting: 'Écriture du code…',
    sandboxNextStep: 'Préparation de l’étape suivante…',
    sandboxContinuedFiles: '{count} fichier(s) créé(s) ; suite…',
    sandboxFinishing: 'Préparation des fichiers…',
    thinkingLive: 'Réflexion…', thinkingDoneSummary: 'Résumé de la réflexion · {s} s', thinkingDoneRaw: 'Réflexion · {s} s', thinkingInterrupted: 'Réflexion interrompue',
    sandboxThought: 'Réflexion',
    ledgerThought: 'Réflexion terminée', ledgerRan: 'Code exécuté : {title}', ledgerRanUntitled: 'Code exécuté',
    sandboxDone: 'Code exécuté {n} fois',
    processedIn: 'Traité en {t}',
    copyCode: 'Copier le code',
    sandboxSearching: 'Recherche sur le web…',
    processWorking: 'En cours',
    processOpenSetting: 'Afficher les étapes par défaut',
    processOpenHint: 'Pendant une réponse, ses étapes sont réduites à une ligne, « En cours », qui s’ouvre au toucher. Activez pour les voir ouvertes.',
    webSearchingFor: 'Recherche : {query}',
    webOpeningPage: 'Lecture de la page : {host}',
    sourcesSearched: '{n} sites consultés',
    sourcesRead: '{n} pages lues',
    citeSources: '{n} sources',
    sourcesTab: 'Sources',
    timelineTab: 'Chronologie',
    sourcesPanelCount: 'Sources · {n}',
    closePanel: 'Fermer',
    noSourcesInReply: 'Cette réponse n’a pas de sources.',
    timelineYou: 'Vous',
    timelineReply: 'Noureon',
    timelineEmpty: 'Aucun message',
    timelineYourMessage: '(sans texte)',
    timelineEmptyReply: '(sans texte)',
    sandboxStopped: 'Arrêté',
    sandboxFailed: 'Échec de l’exécution',
    sandboxStep: 'Exécution {n}',
    sandboxError: 'Erreur',
    sandboxOutput: 'Sortie',
    sandboxProduced: 'Créé',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Arrêté à la limite de temps',
    sandboxOutputTrimmed: '(Sortie trop longue ; une partie est omise)',
    fallbackNotice: 'Passé en mode Standard : {reason}',
    'reason.model-unsupported': 'le modèle actuel ne peut pas exécuter de code',
    'reason.council': 'le conseil de modèles ne prend pas en charge le mode Avancé',
    'reason.learning': 'le mode apprentissage ne prend pas en charge le mode Avancé',
    'reason.browser-unsupported': 'ce navigateur ne peut pas exécuter Python (WebAssembly et Web Workers sont nécessaires)',
    'reason.sandbox-load-failed': 'Python n’a pas pu être chargé (vous êtes peut-être hors ligne ou la connexion est bloquée)',
    'reason.sandbox-crashed': 'l’environnement Python a rencontré une erreur irrécupérable',
    'reason.search-conflict': 'ce modèle ne peut pas utiliser la recherche web et exécuter du code en même temps'
  },
  ru: {
    fileModeLabel: 'Режим',
    fileModeStandard: 'Стандартный',
    fileModeAdvanced: 'Расширенный',
    fileModeStandardNote: 'Работает со всеми моделями и быстрее всего.',
    fileModeAdvancedNote: 'ИИ запускает Python в вашем браузере, чтобы анализировать загруженные файлы и строить точные графики. При первом использовании загружается около 30 МБ.',
    fileModeAdvancedReady: 'ИИ запускает Python в вашем браузере, чтобы анализировать загруженные файлы и строить точные графики. Среда Python загружена.',
    fileModeUnavailable: 'Расширенный режим недоступен: {reason}',
    fileModeDefaultSetting: 'Режим новых чатов',
    fileModeDefaultSettingNote: 'В расширенном режиме ИИ запускает Python в вашем браузере; модели без поддержки автоматически переходят на стандартный режим.',
    sandboxPreparing: 'Подготовка Python…',
    sandboxDownloading: 'Подготовка Python (около 30 МБ в первый раз)… загружено {mb} МБ',
    sandboxPackages: 'Загрузка пакетов Python…',
    sandboxRunning: 'Выполнение кода: {title}',
    sandboxRunningUntitled: 'Выполнение кода…',
    sandboxThinking: 'Продолжение по результатам…',
    sandboxAsking: 'Размышление…',
    sandboxFixing: 'Код завершился ошибкой; исправление…',
    sandboxWriting: 'Написание кода…',
    sandboxNextStep: 'Подготовка следующего шага…',
    sandboxContinuedFiles: 'Создано файлов: {count}; продолжение…',
    sandboxFinishing: 'Подготовка файлов…',
    thinkingLive: 'Размышление…', thinkingDoneSummary: 'Краткое изложение размышлений · {s} с', thinkingDoneRaw: 'Размышление · {s} с', thinkingInterrupted: 'Размышление прервано',
    sandboxThought: 'Ход мысли',
    ledgerThought: 'Размышление завершено', ledgerRan: 'Код выполнен: {title}', ledgerRanUntitled: 'Код выполнен',
    sandboxDone: 'Код выполнен {n} раз(а)',
    processedIn: 'Время обработки: {t}',
    copyCode: 'Копировать код',
    sandboxSearching: 'Поиск в интернете…',
    processWorking: 'В работе',
    processOpenSetting: 'Показывать шаги по умолчанию',
    processOpenHint: 'Пока готовится ответ, его шаги свёрнуты в одну строку «В работе», которая раскрывается по нажатию. Включите, чтобы шаги были раскрыты.',
    webSearchingFor: 'Поиск: {query}',
    webOpeningPage: 'Чтение страницы: {host}',
    sourcesSearched: 'Просмотрено сайтов: {n}',
    sourcesRead: 'Прочитано страниц: {n}',
    citeSources: 'Источников: {n}',
    sourcesTab: 'Источники',
    timelineTab: 'Хронология',
    sourcesPanelCount: 'Источники · {n}',
    closePanel: 'Закрыть',
    noSourcesInReply: 'У этого ответа нет источников.',
    timelineYou: 'Вы',
    timelineReply: 'Noureon',
    timelineEmpty: 'Нет сообщений',
    timelineYourMessage: '(без текста)',
    timelineEmptyReply: '(без текста)',
    sandboxStopped: 'Остановлено',
    sandboxFailed: 'Ошибка выполнения',
    sandboxStep: 'Запуск {n}',
    sandboxError: 'Ошибка',
    sandboxOutput: 'Вывод',
    sandboxProduced: 'Создано',
    sandboxSeconds: '{s} с',
    sandboxTimedOut: 'Остановлено по лимиту времени',
    sandboxOutputTrimmed: '(Вывод слишком длинный; часть пропущена)',
    fallbackNotice: 'Переключено на стандартный режим: {reason}',
    'reason.model-unsupported': 'текущая модель не умеет выполнять код',
    'reason.council': 'совет моделей не поддерживает расширенный режим',
    'reason.learning': 'режим обучения не поддерживает расширенный режим',
    'reason.browser-unsupported': 'этот браузер не может запускать Python (нужны WebAssembly и Web Workers)',
    'reason.sandbox-load-failed': 'не удалось загрузить Python (возможно, нет сети или соединение заблокировано)',
    'reason.sandbox-crashed': 'в среде Python произошла неустранимая ошибка',
    'reason.search-conflict': 'эта модель не может одновременно искать в интернете и выполнять код'
  },
  es: {
    fileModeLabel: 'Modo',
    fileModeStandard: 'Estándar',
    fileModeAdvanced: 'Avanzado',
    fileModeStandardNote: 'Funciona con todos los modelos y es el más rápido.',
    fileModeAdvancedNote: 'La IA ejecuta Python en tu navegador para analizar los archivos subidos y crear gráficos precisos. El primer uso descarga unos 30 MB.',
    fileModeAdvancedReady: 'La IA ejecuta Python en tu navegador para analizar los archivos subidos y crear gráficos precisos. El entorno de Python ya está descargado.',
    fileModeUnavailable: 'El modo Avanzado no está disponible: {reason}',
    fileModeDefaultSetting: 'Modo de los chats nuevos',
    fileModeDefaultSettingNote: 'El modo Avanzado permite que la IA ejecute Python en tu navegador; los modelos sin compatibilidad pasan al modo Estándar automáticamente.',
    sandboxPreparing: 'Preparando Python…',
    sandboxDownloading: 'Preparando Python (unos 30 MB la primera vez)… {mb} MB descargados',
    sandboxPackages: 'Cargando paquetes de Python…',
    sandboxRunning: 'Ejecutando código: {title}',
    sandboxRunningUntitled: 'Ejecutando código…',
    sandboxThinking: 'Continuando a partir de los resultados…',
    sandboxAsking: 'Pensando…',
    sandboxFixing: 'El código falló; corrigiéndolo…',
    sandboxWriting: 'Escribiendo el código…',
    sandboxNextStep: 'Preparando el siguiente paso…',
    sandboxContinuedFiles: '{count} archivo(s) creado(s); continuando…',
    sandboxFinishing: 'Preparando los archivos…',
    thinkingLive: 'Pensando…', thinkingDoneSummary: 'Resumen del razonamiento · {s} s', thinkingDoneRaw: 'Razonamiento · {s} s', thinkingInterrupted: 'Razonamiento interrumpido',
    sandboxThought: 'Razonamiento',
    ledgerThought: 'Pensamiento terminado', ledgerRan: 'Código ejecutado: {title}', ledgerRanUntitled: 'Código ejecutado',
    sandboxDone: 'Código ejecutado {n} veces',
    processedIn: 'Procesado en {t}',
    copyCode: 'Copiar código',
    sandboxSearching: 'Buscando en la web…',
    processWorking: 'En curso',
    processOpenSetting: 'Mostrar los pasos por defecto',
    processOpenHint: 'Mientras se prepara una respuesta, sus pasos se pliegan en una línea, «En curso», que se abre al tocarla. Actívelo para verlos abiertos.',
    webSearchingFor: 'Buscando: {query}',
    webOpeningPage: 'Leyendo la página: {host}',
    sourcesSearched: '{n} sitios consultados',
    sourcesRead: '{n} páginas leídas',
    citeSources: '{n} fuentes',
    sourcesTab: 'Fuentes',
    timelineTab: 'Cronología',
    sourcesPanelCount: 'Fuentes · {n}',
    closePanel: 'Cerrar',
    noSourcesInReply: 'Esta respuesta no tiene fuentes.',
    timelineYou: 'Tú',
    timelineReply: 'Noureon',
    timelineEmpty: 'Aún no hay mensajes',
    timelineYourMessage: '(sin texto)',
    timelineEmptyReply: '(sin texto)',
    sandboxStopped: 'Detenido',
    sandboxFailed: 'Error de ejecución',
    sandboxStep: 'Ejecución {n}',
    sandboxError: 'Error',
    sandboxOutput: 'Salida',
    sandboxProduced: 'Creado',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Detenido al alcanzar el límite de tiempo',
    sandboxOutputTrimmed: '(Salida demasiado larga; se omite una parte)',
    fallbackNotice: 'Se cambió al modo Estándar: {reason}',
    'reason.model-unsupported': 'el modelo actual no puede ejecutar código',
    'reason.council': 'el consejo de modelos no admite el modo Avanzado',
    'reason.learning': 'el modo de aprendizaje no admite el modo Avanzado',
    'reason.browser-unsupported': 'este navegador no puede ejecutar Python (necesita WebAssembly y Web Workers)',
    'reason.sandbox-load-failed': 'no se pudo cargar Python (puede que no haya conexión o que esté bloqueada)',
    'reason.sandbox-crashed': 'el entorno de Python tuvo un error del que no puede recuperarse',
    'reason.search-conflict': 'este modelo no puede usar la búsqueda web y ejecutar código a la vez'
  }
});

export const SANDBOX_TEXT_LANGUAGES = Object.freeze(Object.keys(TEXTS));
export const SANDBOX_TEXT_KEYS = Object.freeze(Object.keys(TEXTS['zh-TW']));

export function sandboxText(language, key, values = {}) {
  const table = TEXTS[language] || TEXTS['zh-TW'];
  const template = table[key] ?? TEXTS['zh-TW'][key] ?? key;
  return template.replace(/\{(\w+)\}/g, (match, name) => (name in values ? String(values[name]) : match));
}

export const sandboxTextsFor = (language) => TEXTS[language] || TEXTS['zh-TW'];
