// Interface texts for Advanced mode (Python in the browser), in the app's
// five interface languages. {name} placeholders are filled by sandboxText.

const TEXTS = Object.freeze({
  'zh-TW': {
    fileModeLabel: '製作方式',
    fileModeStandard: '標準',
    fileModeAdvanced: '進階',
    fileModeStandardNote: '所有模型都能用，速度最快。',
    fileModeAdvancedNote: 'AI 在你的瀏覽器執行 Python，可分析上傳的檔案、精算圖表。第一次使用需下載約 30 MB。',
    fileModeAdvancedReady: 'AI 在你的瀏覽器執行 Python，可分析上傳的檔案、精算圖表。Python 環境已下載。',
    fileModeUnavailable: '目前無法使用進階模式：{reason}',
    fileModeDefaultSetting: '新對話的製作方式',
    fileModeDefaultSettingNote: '進階模式讓 AI 在你的瀏覽器執行 Python；不支援的模型會自動改用標準。',
    sandboxPreparing: '正在準備 Python 環境……',
    sandboxDownloading: '正在準備 Python 環境（第一次約 30 MB）…… 已下載 {mb} MB',
    sandboxPackages: '正在載入 Python 套件……',
    sandboxRunning: '正在執行程式（第 {n} 次）：{title}',
    sandboxRunningUntitled: '正在執行程式（第 {n} 次）……',
    sandboxThinking: '{model} 正在根據執行結果繼續……',
    sandboxAsking: '{model} 正在思考並撰寫程式……',
    sandboxFixing: '程式出錯了，{model} 正在修正……',
    sandboxContinuedFiles: '已產生 {count} 個檔案，{model} 正在繼續……',
    sandboxFinishing: '正在整理產出的檔案……',
    ledgerThought: '{model} 思考完成', ledgerRan: '已執行程式（第 {n} 次）：{title}', ledgerRanUntitled: '已執行程式（第 {n} 次）',
    sandboxDone: '已執行程式 {n} 次',
    sandboxStopped: '已停止',
    sandboxFailed: '執行失敗',
    sandboxStep: '第 {n} 次',
    sandboxError: '錯誤',
    sandboxOutput: '輸出',
    sandboxProduced: '產生',
    sandboxSeconds: '{s} 秒',
    sandboxTimedOut: '超過時間上限，已停止',
    sandboxOutputTrimmed: '（輸出過長，已省略部分內容）',
    fallbackNotice: '已改用標準模式：{reason}',
    'reason.model-unsupported': '目前的模型不支援執行程式',
    'reason.council': '模型理事會不支援進階模式',
    'reason.learning': '學習模式不支援進階模式',
    'reason.browser-unsupported': '這個瀏覽器無法執行 Python（需要 WebAssembly 與 Web Worker）',
    'reason.sandbox-load-failed': 'Python 環境載入失敗（可能離線或連線被阻擋）',
    'reason.sandbox-crashed': 'Python 環境發生無法恢復的錯誤',
    'reason.search-conflict': '此模型無法同時使用網路搜尋與執行程式'
  },
  en: {
    fileModeLabel: 'Mode',
    fileModeStandard: 'Standard',
    fileModeAdvanced: 'Advanced',
    fileModeStandardNote: 'Works with every model and is the fastest.',
    fileModeAdvancedNote: 'The AI runs Python in your browser to analyse uploaded files and build precise charts. The first use downloads about 30 MB.',
    fileModeAdvancedReady: 'The AI runs Python in your browser to analyse uploaded files and build precise charts. The Python environment is downloaded.',
    fileModeUnavailable: 'Advanced mode is unavailable: {reason}',
    fileModeDefaultSetting: 'Mode for new chats',
    fileModeDefaultSettingNote: 'Advanced mode lets the AI run Python in your browser; models without support switch to Standard automatically.',
    sandboxPreparing: 'Preparing Python…',
    sandboxDownloading: 'Preparing Python (about 30 MB the first time)… {mb} MB downloaded',
    sandboxPackages: 'Loading Python packages…',
    sandboxRunning: 'Running code ({n}): {title}',
    sandboxRunningUntitled: 'Running code ({n})…',
    sandboxThinking: '{model} is continuing from the results…',
    sandboxAsking: '{model} is thinking and writing code…',
    sandboxFixing: 'The code failed; {model} is fixing it…',
    sandboxContinuedFiles: '{count} file(s) made; {model} is continuing…',
    sandboxFinishing: 'Preparing the files…',
    ledgerThought: '{model} finished thinking', ledgerRan: 'Ran code ({n}): {title}', ledgerRanUntitled: 'Ran code ({n})',
    sandboxDone: 'Ran code {n} times',
    sandboxStopped: 'Stopped',
    sandboxFailed: 'Run failed',
    sandboxStep: 'Run {n}',
    sandboxError: 'Error',
    sandboxOutput: 'Output',
    sandboxProduced: 'Created',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Stopped at the time limit',
    sandboxOutputTrimmed: '(Output too long; part of it is left out)',
    fallbackNotice: 'Switched to Standard mode: {reason}',
    'reason.model-unsupported': 'the current model cannot run code',
    'reason.council': 'the model council does not support Advanced mode',
    'reason.learning': 'learning mode does not support Advanced mode',
    'reason.browser-unsupported': 'this browser cannot run Python (it needs WebAssembly and Web Workers)',
    'reason.sandbox-load-failed': 'Python could not be loaded (you may be offline or the connection is blocked)',
    'reason.sandbox-crashed': 'the Python environment hit an error it cannot recover from',
    'reason.search-conflict': 'this model cannot use web search and run code at the same time'
  },
  fr: {
    fileModeLabel: 'Mode',
    fileModeStandard: 'Standard',
    fileModeAdvanced: 'Avancé',
    fileModeStandardNote: 'Fonctionne avec tous les modèles et c’est le plus rapide.',
    fileModeAdvancedNote: 'L’IA exécute Python dans votre navigateur pour analyser les fichiers envoyés et créer des graphiques précis. La première utilisation télécharge environ 30 Mo.',
    fileModeAdvancedReady: 'L’IA exécute Python dans votre navigateur pour analyser les fichiers envoyés et créer des graphiques précis. L’environnement Python est téléchargé.',
    fileModeUnavailable: 'Le mode Avancé est indisponible : {reason}',
    fileModeDefaultSetting: 'Mode des nouvelles conversations',
    fileModeDefaultSettingNote: 'Le mode Avancé permet à l’IA d’exécuter Python dans votre navigateur ; les modèles incompatibles passent automatiquement en mode Standard.',
    sandboxPreparing: 'Préparation de Python…',
    sandboxDownloading: 'Préparation de Python (environ 30 Mo la première fois)… {mb} Mo téléchargés',
    sandboxPackages: 'Chargement des modules Python…',
    sandboxRunning: 'Exécution du code ({n}) : {title}',
    sandboxRunningUntitled: 'Exécution du code ({n})…',
    sandboxThinking: '{model} poursuit à partir des résultats…',
    sandboxAsking: '{model} réfléchit et écrit le code…',
    sandboxFixing: 'Le code a échoué ; {model} le corrige…',
    sandboxContinuedFiles: '{count} fichier(s) créé(s) ; {model} continue…',
    sandboxFinishing: 'Préparation des fichiers…',
    ledgerThought: '{model} a fini de réfléchir', ledgerRan: 'Code exécuté ({n}) : {title}', ledgerRanUntitled: 'Code exécuté ({n})',
    sandboxDone: 'Code exécuté {n} fois',
    sandboxStopped: 'Arrêté',
    sandboxFailed: 'Échec de l’exécution',
    sandboxStep: 'Exécution {n}',
    sandboxError: 'Erreur',
    sandboxOutput: 'Sortie',
    sandboxProduced: 'Créé',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Arrêté à la limite de temps',
    sandboxOutputTrimmed: '(Sortie trop longue ; une partie est omise)',
    fallbackNotice: 'Passé en mode Standard : {reason}',
    'reason.model-unsupported': 'le modèle actuel ne peut pas exécuter de code',
    'reason.council': 'le conseil de modèles ne prend pas en charge le mode Avancé',
    'reason.learning': 'le mode apprentissage ne prend pas en charge le mode Avancé',
    'reason.browser-unsupported': 'ce navigateur ne peut pas exécuter Python (WebAssembly et Web Workers sont nécessaires)',
    'reason.sandbox-load-failed': 'Python n’a pas pu être chargé (vous êtes peut-être hors ligne ou la connexion est bloquée)',
    'reason.sandbox-crashed': 'l’environnement Python a rencontré une erreur irrécupérable',
    'reason.search-conflict': 'ce modèle ne peut pas utiliser la recherche web et exécuter du code en même temps'
  },
  ru: {
    fileModeLabel: 'Режим',
    fileModeStandard: 'Стандартный',
    fileModeAdvanced: 'Расширенный',
    fileModeStandardNote: 'Работает со всеми моделями и быстрее всего.',
    fileModeAdvancedNote: 'ИИ запускает Python в вашем браузере, чтобы анализировать загруженные файлы и строить точные графики. При первом использовании загружается около 30 МБ.',
    fileModeAdvancedReady: 'ИИ запускает Python в вашем браузере, чтобы анализировать загруженные файлы и строить точные графики. Среда Python загружена.',
    fileModeUnavailable: 'Расширенный режим недоступен: {reason}',
    fileModeDefaultSetting: 'Режим новых чатов',
    fileModeDefaultSettingNote: 'В расширенном режиме ИИ запускает Python в вашем браузере; модели без поддержки автоматически переходят на стандартный режим.',
    sandboxPreparing: 'Подготовка Python…',
    sandboxDownloading: 'Подготовка Python (около 30 МБ в первый раз)… загружено {mb} МБ',
    sandboxPackages: 'Загрузка пакетов Python…',
    sandboxRunning: 'Выполнение кода ({n}): {title}',
    sandboxRunningUntitled: 'Выполнение кода ({n})…',
    sandboxThinking: '{model} продолжает по результатам…',
    sandboxAsking: '{model} думает и пишет код…',
    sandboxFixing: 'Код завершился ошибкой; {model} исправляет…',
    sandboxContinuedFiles: 'Создано файлов: {count}; {model} продолжает…',
    sandboxFinishing: 'Подготовка файлов…',
    ledgerThought: '{model} закончил думать', ledgerRan: 'Код выполнен ({n}): {title}', ledgerRanUntitled: 'Код выполнен ({n})',
    sandboxDone: 'Код выполнен {n} раз(а)',
    sandboxStopped: 'Остановлено',
    sandboxFailed: 'Ошибка выполнения',
    sandboxStep: 'Запуск {n}',
    sandboxError: 'Ошибка',
    sandboxOutput: 'Вывод',
    sandboxProduced: 'Создано',
    sandboxSeconds: '{s} с',
    sandboxTimedOut: 'Остановлено по лимиту времени',
    sandboxOutputTrimmed: '(Вывод слишком длинный; часть пропущена)',
    fallbackNotice: 'Переключено на стандартный режим: {reason}',
    'reason.model-unsupported': 'текущая модель не умеет выполнять код',
    'reason.council': 'совет моделей не поддерживает расширенный режим',
    'reason.learning': 'режим обучения не поддерживает расширенный режим',
    'reason.browser-unsupported': 'этот браузер не может запускать Python (нужны WebAssembly и Web Workers)',
    'reason.sandbox-load-failed': 'не удалось загрузить Python (возможно, нет сети или соединение заблокировано)',
    'reason.sandbox-crashed': 'в среде Python произошла неустранимая ошибка',
    'reason.search-conflict': 'эта модель не может одновременно искать в интернете и выполнять код'
  },
  es: {
    fileModeLabel: 'Modo',
    fileModeStandard: 'Estándar',
    fileModeAdvanced: 'Avanzado',
    fileModeStandardNote: 'Funciona con todos los modelos y es el más rápido.',
    fileModeAdvancedNote: 'La IA ejecuta Python en tu navegador para analizar los archivos subidos y crear gráficos precisos. El primer uso descarga unos 30 MB.',
    fileModeAdvancedReady: 'La IA ejecuta Python en tu navegador para analizar los archivos subidos y crear gráficos precisos. El entorno de Python ya está descargado.',
    fileModeUnavailable: 'El modo Avanzado no está disponible: {reason}',
    fileModeDefaultSetting: 'Modo de los chats nuevos',
    fileModeDefaultSettingNote: 'El modo Avanzado permite que la IA ejecute Python en tu navegador; los modelos sin compatibilidad pasan al modo Estándar automáticamente.',
    sandboxPreparing: 'Preparando Python…',
    sandboxDownloading: 'Preparando Python (unos 30 MB la primera vez)… {mb} MB descargados',
    sandboxPackages: 'Cargando paquetes de Python…',
    sandboxRunning: 'Ejecutando código ({n}): {title}',
    sandboxRunningUntitled: 'Ejecutando código ({n})…',
    sandboxThinking: '{model} continúa a partir de los resultados…',
    sandboxAsking: '{model} está pensando y escribiendo el código…',
    sandboxFixing: 'El código falló; {model} lo está corrigiendo…',
    sandboxContinuedFiles: '{count} archivo(s) creado(s); {model} continúa…',
    sandboxFinishing: 'Preparando los archivos…',
    ledgerThought: '{model} terminó de pensar', ledgerRan: 'Código ejecutado ({n}): {title}', ledgerRanUntitled: 'Código ejecutado ({n})',
    sandboxDone: 'Código ejecutado {n} veces',
    sandboxStopped: 'Detenido',
    sandboxFailed: 'Error de ejecución',
    sandboxStep: 'Ejecución {n}',
    sandboxError: 'Error',
    sandboxOutput: 'Salida',
    sandboxProduced: 'Creado',
    sandboxSeconds: '{s} s',
    sandboxTimedOut: 'Detenido al alcanzar el límite de tiempo',
    sandboxOutputTrimmed: '(Salida demasiado larga; se omite una parte)',
    fallbackNotice: 'Se cambió al modo Estándar: {reason}',
    'reason.model-unsupported': 'el modelo actual no puede ejecutar código',
    'reason.council': 'el consejo de modelos no admite el modo Avanzado',
    'reason.learning': 'el modo de aprendizaje no admite el modo Avanzado',
    'reason.browser-unsupported': 'este navegador no puede ejecutar Python (necesita WebAssembly y Web Workers)',
    'reason.sandbox-load-failed': 'no se pudo cargar Python (puede que no haya conexión o que esté bloqueada)',
    'reason.sandbox-crashed': 'el entorno de Python tuvo un error del que no puede recuperarse',
    'reason.search-conflict': 'este modelo no puede usar la búsqueda web y ejecutar código a la vez'
  }
});

export const SANDBOX_TEXT_LANGUAGES = Object.freeze(Object.keys(TEXTS));
export const SANDBOX_TEXT_KEYS = Object.freeze(Object.keys(TEXTS['zh-TW']));

export function sandboxText(language, key, values = {}) {
  const table = TEXTS[language] || TEXTS['zh-TW'];
  const template = table[key] ?? TEXTS['zh-TW'][key] ?? key;
  return template.replace(/\{(\w+)\}/g, (match, name) => (name in values ? String(values[name]) : match));
}

export const sandboxTextsFor = (language) => TEXTS[language] || TEXTS['zh-TW'];
