// The words of the connectors part of the Extensions page (連接器: the list, the sheet that begins a login, the tools and what the person lets each do, the notices) in the
// app's five languages. Apart from the other words of the page (cli-texts.js) because they are only needed when the page is opened. {name} and {count} placeholders are
// filled by connectorText. The words of the rows of the step list and of the card that asks about a tool are here too: the server writes the rows, and the card is a file of its own.

export const CONNECTOR_TEXTS = Object.freeze({
  'zh-TW': {
    connectorPermissions: '權限',
    connectorFeatures: '功能',
    connectorKindRead: '讀取',
    connectorKindWrite: '寫入',
    connectorManage: '管理工具權限',
    connectorNoFeatures: '還沒有讀到這個服務的工具。',
    connectorCalling: '使用連接器：{connector} · {tool}',
    connectorListing: '查看連接器的工具：{connector}',
    connectorWaiting: '等你回答：要不要讓 {connector} 執行 {tool}？',
    connectorAskTitle: '{connector} 想執行：{tool}',
    connectorAskOnce: '同意一次',
    connectorAskAlways: '永遠同意',
    connectorAskDeny: '拒絕',
    connectorAskParams: '看全部參數',
    connectorAskHideParams: '收合參數',
    connectorAskWait: '等你回答，{minutes} 分鐘內沒有回答就當作拒絕。',
    connectorAnsweredOnce: '已同意一次：{connector} · {tool}',
    connectorAnsweredAlways: '已永遠同意：{connector} · {tool}',
    connectorAnsweredDeny: '已拒絕：{connector} · {tool}',
    connectorAnsweredTimeout: '沒有及時回答，已拒絕：{connector} · {tool}',
    connectorAskFailed: '答案沒有送出，請再試一次。',
    connectorKind: '連接器',
    connectorSearchPlaceholder: '搜尋連接器',
    connectorCategory_notes: '筆記與專案',
    connectorCategory_dev: '開發',
    connectorConnect: '連線',
    connectorConnected: '已連線',
    connectorNeedsLogin: '需要重新登入',
    connectorReconnect: '重新登入',
    connectorDisconnect: '中斷連線',
    connectorDisconnectSure: '確定中斷連線',
    connectorCancel: '取消',
    connectorNoneMine: '還沒有連線任何連接器。',
    connectorNoResults: '找不到符合的連接器。',
    connectorNeedAccount: '連接器需要先登入雲端帳號，登入資料會加密保存在伺服器。',
    connectorLoading: '讀取中……',
    connectorLoadFailed: '暫時無法讀取連接器的狀態，請稍後再試。',
    connectorRetry: '再試一次',
    connectorScopeTitle: '連線範圍',
    connectorScopeReadonly: '唯讀連線',
    connectorScopeReadwrite: '可讀寫連線',
    connectorScopeNoteReadonly: '選「唯讀連線」時，{name} 發給 Noureon 的令牌本身就無法寫入。',
    connectorScopeNoteReadwrite: '這個連線可以讀取也可以寫入；實際能做什麼，由下面每個工具的設定決定。',
    connectorScopeFixed: '這個服務的授權包含寫入權限，Noureon 只會在你允許的時候使用。',
    connectorScopeSwitch: '切換連線範圍需要重新登入 {name}。',
    connectorGroupRead: '讀取工具',
    connectorGroupWrite: '寫入工具',
    connectorStateAllow: '允許',
    connectorStateAsk: '詢問',
    connectorStateDeny: '拒絕',
    connectorIndividual: '個別設定',
    connectorDiffers: '{count} 個與整組不同',
    connectorChanged: '內容已變更，需要你重新確認（目前已停用）',
    connectorNoTools: '這個連接器目前沒有可用的工具。',
    connectorRefresh: '重新整理工具',
    connectorRefreshed: '已重新整理 {name} 的工具。',
    connectorSheetTitle: '連線 {name}',
    connectorSheetNote: '接著會前往 {name} 登入並授權，完成後回到 Noureon。',
    connectorSheetPrivacy: '連線後，模型讀到的內容會經由 Noureon 的伺服器送給你選用的模型供應商。',
    connectorSheetGo: '前往登入',
    connectorSheetBusy: '正在前往……',
    connectorSheetFailed: '無法開始登入，請稍後再試。',
    connectorConnected_notice: '已連線：{name}',
    connectorDisconnected_notice: '已中斷連線：{name}',
    connectorErr_denied: '你取消了登入。',
    connectorErr_expired: '登入逾時，請再試一次。',
    connectorErr_bad_state: '這個登入連結已失效，請重新連線。',
    connectorErr_failed: '連線失敗，請稍後再試。',
    connectorErr_busy: '現在連線的人太多，請稍後再試。',
    connectorSaveFailed: '設定沒有儲存，請再試一次。'
  },
  en: {
    connectorPermissions: 'Permissions',
    connectorFeatures: 'Features',
    connectorKindRead: 'Read',
    connectorKindWrite: 'Write',
    connectorManage: 'Manage tool permissions',
    connectorNoFeatures: 'The tools of this service have not been read yet.',
    connectorCalling: 'Using connector: {connector} · {tool}',
    connectorListing: 'Looking at the tools of {connector}',
    connectorWaiting: 'Waiting for you: may {connector} run {tool}?',
    connectorAskTitle: '{connector} wants to run: {tool}',
    connectorAskOnce: 'Allow once',
    connectorAskAlways: 'Always allow',
    connectorAskDeny: 'Refuse',
    connectorAskParams: 'See all parameters',
    connectorAskHideParams: 'Hide parameters',
    connectorAskWait: 'Waiting for your answer. With none in {minutes} minutes it is refused.',
    connectorAnsweredOnce: 'Allowed once: {connector} · {tool}',
    connectorAnsweredAlways: 'Always allowed: {connector} · {tool}',
    connectorAnsweredDeny: 'Refused: {connector} · {tool}',
    connectorAnsweredTimeout: 'No answer in time, refused: {connector} · {tool}',
    connectorAskFailed: 'The answer could not be sent. Try again.',
    connectorKind: 'Connectors',
    connectorSearchPlaceholder: 'Search connectors',
    connectorCategory_notes: 'Notes and projects',
    connectorCategory_dev: 'Development',
    connectorConnect: 'Connect',
    connectorConnected: 'Connected',
    connectorNeedsLogin: 'Login needed',
    connectorReconnect: 'Log in again',
    connectorDisconnect: 'Disconnect',
    connectorDisconnectSure: 'Confirm disconnect',
    connectorCancel: 'Cancel',
    connectorNoneMine: 'No connector is connected yet.',
    connectorNoResults: 'No connector matches.',
    connectorNeedAccount: 'Connectors need you to be signed in to your cloud account; the logins are kept encrypted on the server.',
    connectorLoading: 'Loading…',
    connectorLoadFailed: 'The state of the connectors cannot be read now. Try again in a moment.',
    connectorRetry: 'Try again',
    connectorScopeTitle: 'Access',
    connectorScopeReadonly: 'Read-only',
    connectorScopeReadwrite: 'Read and write',
    connectorScopeNoteReadonly: 'With "Read-only", the token {name} gives Noureon cannot write at all.',
    connectorScopeNoteReadwrite: 'This connection can read and write; what is actually done is decided by the setting of each tool below.',
    connectorScopeFixed: 'This service\'s login includes the right to write; Noureon uses it only when you allow.',
    connectorScopeSwitch: 'Changing the access means logging in to {name} again.',
    connectorGroupRead: 'Read tools',
    connectorGroupWrite: 'Write tools',
    connectorStateAllow: 'Allow',
    connectorStateAsk: 'Ask',
    connectorStateDeny: 'Refuse',
    connectorIndividual: 'Each tool',
    connectorDiffers: '{count} differ from the group',
    connectorChanged: 'Changed: confirm it again (it is switched off for now)',
    connectorNoTools: 'This connector has no tools to use now.',
    connectorRefresh: 'Refresh tools',
    connectorRefreshed: 'The tools of {name} were refreshed.',
    connectorSheetTitle: 'Connect {name}',
    connectorSheetNote: 'You will go to {name} to log in and authorise, then come back to Noureon.',
    connectorSheetPrivacy: 'Once connected, what the model reads goes through Noureon\'s server to the model provider you chose.',
    connectorSheetGo: 'Go to log in',
    connectorSheetBusy: 'Going there…',
    connectorSheetFailed: 'The login could not begin. Try again in a moment.',
    connectorConnected_notice: 'Connected: {name}',
    connectorDisconnected_notice: 'Disconnected: {name}',
    connectorErr_denied: 'You cancelled the login.',
    connectorErr_expired: 'The login took too long. Try again.',
    connectorErr_bad_state: 'This login link is no longer valid. Connect again.',
    connectorErr_failed: 'The connection failed. Try again in a moment.',
    connectorErr_busy: 'Too many people are connecting now. Try again in a moment.',
    connectorSaveFailed: 'The setting was not saved. Try again.'
  },
  fr: {
    connectorPermissions: 'Autorisations',
    connectorFeatures: 'Fonctions',
    connectorKindRead: 'Lecture',
    connectorKindWrite: 'Écriture',
    connectorManage: 'Gérer les autorisations des outils',
    connectorNoFeatures: 'Les outils de ce service n’ont pas encore été lus.',
    connectorCalling: 'Connecteur utilisé : {connector} · {tool}',
    connectorListing: 'Consultation des outils de {connector}',
    connectorWaiting: 'En attente de vous : {connector} peut-il exécuter {tool} ?',
    connectorAskTitle: '{connector} veut exécuter : {tool}',
    connectorAskOnce: 'Autoriser une fois',
    connectorAskAlways: 'Toujours autoriser',
    connectorAskDeny: 'Refuser',
    connectorAskParams: 'Voir tous les paramètres',
    connectorAskHideParams: 'Masquer les paramètres',
    connectorAskWait: 'En attente de votre réponse. Sans réponse en {minutes} minutes, c’est refusé.',
    connectorAnsweredOnce: 'Autorisé une fois : {connector} · {tool}',
    connectorAnsweredAlways: 'Toujours autorisé : {connector} · {tool}',
    connectorAnsweredDeny: 'Refusé : {connector} · {tool}',
    connectorAnsweredTimeout: 'Pas de réponse à temps, refusé : {connector} · {tool}',
    connectorAskFailed: 'La réponse n’a pas pu être envoyée. Réessayez.',
    connectorKind: 'Connecteurs',
    connectorSearchPlaceholder: 'Rechercher un connecteur',
    connectorCategory_notes: 'Notes et projets',
    connectorCategory_dev: 'Développement',
    connectorConnect: 'Connecter',
    connectorConnected: 'Connecté',
    connectorNeedsLogin: 'Reconnexion nécessaire',
    connectorReconnect: 'Se reconnecter',
    connectorDisconnect: 'Déconnecter',
    connectorDisconnectSure: 'Confirmer la déconnexion',
    connectorCancel: 'Annuler',
    connectorNoneMine: 'Aucun connecteur n’est encore connecté.',
    connectorNoResults: 'Aucun connecteur ne correspond.',
    connectorNeedAccount: 'Les connecteurs demandent d’être connecté à votre compte cloud ; les connexions sont conservées chiffrées sur le serveur.',
    connectorLoading: 'Chargement…',
    connectorLoadFailed: 'L’état des connecteurs ne peut pas être lu pour le moment. Réessayez dans un instant.',
    connectorRetry: 'Réessayer',
    connectorScopeTitle: 'Accès',
    connectorScopeReadonly: 'Lecture seule',
    connectorScopeReadwrite: 'Lecture et écriture',
    connectorScopeNoteReadonly: 'Avec « Lecture seule », le jeton que {name} donne à Noureon ne peut pas écrire du tout.',
    connectorScopeNoteReadwrite: 'Cette connexion peut lire et écrire ; ce qui est réellement fait dépend du réglage de chaque outil ci-dessous.',
    connectorScopeFixed: 'La connexion à ce service inclut le droit d’écrire ; Noureon ne l’utilise que si vous l’autorisez.',
    connectorScopeSwitch: 'Changer l’accès demande de se reconnecter à {name}.',
    connectorGroupRead: 'Outils de lecture',
    connectorGroupWrite: 'Outils d’écriture',
    connectorStateAllow: 'Autoriser',
    connectorStateAsk: 'Demander',
    connectorStateDeny: 'Refuser',
    connectorIndividual: 'Outil par outil',
    connectorDiffers: '{count} différent(s) du groupe',
    connectorChanged: 'Modifié : à confirmer de nouveau (désactivé pour l’instant)',
    connectorNoTools: 'Ce connecteur n’a pas d’outil utilisable pour le moment.',
    connectorRefresh: 'Actualiser les outils',
    connectorRefreshed: 'Les outils de {name} ont été actualisés.',
    connectorSheetTitle: 'Connecter {name}',
    connectorSheetNote: 'Vous allez vous connecter et autoriser l’accès sur {name}, puis revenir à Noureon.',
    connectorSheetPrivacy: 'Une fois connecté, ce que le modèle lit passe par le serveur de Noureon jusqu’au fournisseur de modèle que vous avez choisi.',
    connectorSheetGo: 'Aller se connecter',
    connectorSheetBusy: 'Redirection…',
    connectorSheetFailed: 'La connexion n’a pas pu commencer. Réessayez dans un instant.',
    connectorConnected_notice: 'Connecté : {name}',
    connectorDisconnected_notice: 'Déconnecté : {name}',
    connectorErr_denied: 'Vous avez annulé la connexion.',
    connectorErr_expired: 'La connexion a pris trop de temps. Réessayez.',
    connectorErr_bad_state: 'Ce lien de connexion n’est plus valable. Reconnectez-vous.',
    connectorErr_failed: 'La connexion a échoué. Réessayez dans un instant.',
    connectorErr_busy: 'Trop de personnes se connectent en ce moment. Réessayez dans un instant.',
    connectorSaveFailed: 'Le réglage n’a pas été enregistré. Réessayez.'
  },
  ru: {
    connectorPermissions: 'Разрешения',
    connectorFeatures: 'Возможности',
    connectorKindRead: 'Чтение',
    connectorKindWrite: 'Запись',
    connectorManage: 'Управление разрешениями инструментов',
    connectorNoFeatures: 'Инструменты этого сервиса ещё не прочитаны.',
    connectorCalling: 'Используется коннектор: {connector} · {tool}',
    connectorListing: 'Просмотр инструментов {connector}',
    connectorWaiting: 'Ждём вас: может ли {connector} выполнить {tool}?',
    connectorAskTitle: '{connector} хочет выполнить: {tool}',
    connectorAskOnce: 'Разрешить один раз',
    connectorAskAlways: 'Всегда разрешать',
    connectorAskDeny: 'Отказать',
    connectorAskParams: 'Показать все параметры',
    connectorAskHideParams: 'Скрыть параметры',
    connectorAskWait: 'Ждём вашего ответа. Если за {minutes} мин ответа не будет, запрос отклоняется.',
    connectorAnsweredOnce: 'Разрешено один раз: {connector} · {tool}',
    connectorAnsweredAlways: 'Всегда разрешено: {connector} · {tool}',
    connectorAnsweredDeny: 'Отклонено: {connector} · {tool}',
    connectorAnsweredTimeout: 'Ответа вовремя не было, отклонено: {connector} · {tool}',
    connectorAskFailed: 'Не удалось отправить ответ. Попробуйте ещё раз.',
    connectorKind: 'Коннекторы',
    connectorSearchPlaceholder: 'Поиск коннекторов',
    connectorCategory_notes: 'Заметки и проекты',
    connectorCategory_dev: 'Разработка',
    connectorConnect: 'Подключить',
    connectorConnected: 'Подключено',
    connectorNeedsLogin: 'Нужен повторный вход',
    connectorReconnect: 'Войти снова',
    connectorDisconnect: 'Отключить',
    connectorDisconnectSure: 'Подтвердить отключение',
    connectorCancel: 'Отмена',
    connectorNoneMine: 'Пока не подключён ни один коннектор.',
    connectorNoResults: 'Подходящих коннекторов нет.',
    connectorNeedAccount: 'Для коннекторов нужно войти в облачный аккаунт; данные входа хранятся на сервере в зашифрованном виде.',
    connectorLoading: 'Загрузка…',
    connectorLoadFailed: 'Сейчас не удаётся прочитать состояние коннекторов. Попробуйте чуть позже.',
    connectorRetry: 'Повторить',
    connectorScopeTitle: 'Доступ',
    connectorScopeReadonly: 'Только чтение',
    connectorScopeReadwrite: 'Чтение и запись',
    connectorScopeNoteReadonly: 'При «Только чтение» токен, который {name} выдаёт Noureon, вообще не может записывать.',
    connectorScopeNoteReadwrite: 'Это подключение может читать и записывать; что именно будет сделано, определяет настройка каждого инструмента ниже.',
    connectorScopeFixed: 'Вход в этот сервис даёт право записи; Noureon использует его только с вашего разрешения.',
    connectorScopeSwitch: 'Чтобы изменить доступ, нужно снова войти в {name}.',
    connectorGroupRead: 'Инструменты чтения',
    connectorGroupWrite: 'Инструменты записи',
    connectorStateAllow: 'Разрешить',
    connectorStateAsk: 'Спрашивать',
    connectorStateDeny: 'Отказать',
    connectorIndividual: 'По каждому инструменту',
    connectorDiffers: 'Отличаются от группы: {count}',
    connectorChanged: 'Изменён: подтвердите заново (пока отключён)',
    connectorNoTools: 'У этого коннектора сейчас нет доступных инструментов.',
    connectorRefresh: 'Обновить инструменты',
    connectorRefreshed: 'Инструменты {name} обновлены.',
    connectorSheetTitle: 'Подключить {name}',
    connectorSheetNote: 'Вы перейдёте в {name}, войдёте и дадите доступ, а затем вернётесь в Noureon.',
    connectorSheetPrivacy: 'После подключения то, что читает модель, передаётся через сервер Noureon выбранному вами поставщику моделей.',
    connectorSheetGo: 'Перейти ко входу',
    connectorSheetBusy: 'Переходим…',
    connectorSheetFailed: 'Не удалось начать вход. Попробуйте чуть позже.',
    connectorConnected_notice: 'Подключено: {name}',
    connectorDisconnected_notice: 'Отключено: {name}',
    connectorErr_denied: 'Вы отменили вход.',
    connectorErr_expired: 'Вход занял слишком много времени. Попробуйте снова.',
    connectorErr_bad_state: 'Эта ссылка для входа больше не действует. Подключите снова.',
    connectorErr_failed: 'Не удалось подключиться. Попробуйте чуть позже.',
    connectorErr_busy: 'Сейчас подключается слишком много людей. Попробуйте чуть позже.',
    connectorSaveFailed: 'Настройка не сохранена. Попробуйте ещё раз.'
  },
  es: {
    connectorPermissions: 'Permisos',
    connectorFeatures: 'Funciones',
    connectorKindRead: 'Lectura',
    connectorKindWrite: 'Escritura',
    connectorManage: 'Gestionar permisos de herramientas',
    connectorNoFeatures: 'Aún no se han leído las herramientas de este servicio.',
    connectorCalling: 'Usando conector: {connector} · {tool}',
    connectorListing: 'Consultando las herramientas de {connector}',
    connectorWaiting: 'Esperando por ti: ¿puede {connector} ejecutar {tool}?',
    connectorAskTitle: '{connector} quiere ejecutar: {tool}',
    connectorAskOnce: 'Permitir una vez',
    connectorAskAlways: 'Permitir siempre',
    connectorAskDeny: 'Rechazar',
    connectorAskParams: 'Ver todos los parámetros',
    connectorAskHideParams: 'Ocultar parámetros',
    connectorAskWait: 'Esperando tu respuesta. Sin respuesta en {minutes} minutos, se rechaza.',
    connectorAnsweredOnce: 'Permitido una vez: {connector} · {tool}',
    connectorAnsweredAlways: 'Permitido siempre: {connector} · {tool}',
    connectorAnsweredDeny: 'Rechazado: {connector} · {tool}',
    connectorAnsweredTimeout: 'Sin respuesta a tiempo, rechazado: {connector} · {tool}',
    connectorAskFailed: 'La respuesta no pudo enviarse. Inténtalo de nuevo.',
    connectorKind: 'Conectores',
    connectorSearchPlaceholder: 'Buscar conectores',
    connectorCategory_notes: 'Notas y proyectos',
    connectorCategory_dev: 'Desarrollo',
    connectorConnect: 'Conectar',
    connectorConnected: 'Conectado',
    connectorNeedsLogin: 'Requiere iniciar sesión de nuevo',
    connectorReconnect: 'Iniciar sesión de nuevo',
    connectorDisconnect: 'Desconectar',
    connectorDisconnectSure: 'Confirmar desconexión',
    connectorCancel: 'Cancelar',
    connectorNoneMine: 'Aún no hay ningún conector conectado.',
    connectorNoResults: 'Ningún conector coincide.',
    connectorNeedAccount: 'Los conectores requieren haber iniciado sesión en tu cuenta en la nube; los accesos se guardan cifrados en el servidor.',
    connectorLoading: 'Cargando…',
    connectorLoadFailed: 'Ahora no se puede leer el estado de los conectores. Inténtalo de nuevo en un momento.',
    connectorRetry: 'Reintentar',
    connectorScopeTitle: 'Acceso',
    connectorScopeReadonly: 'Solo lectura',
    connectorScopeReadwrite: 'Lectura y escritura',
    connectorScopeNoteReadonly: 'Con «Solo lectura», el token que {name} da a Noureon no puede escribir en absoluto.',
    connectorScopeNoteReadwrite: 'Esta conexión puede leer y escribir; lo que se hace de verdad lo decide el ajuste de cada herramienta de abajo.',
    connectorScopeFixed: 'El acceso a este servicio incluye el permiso de escribir; Noureon solo lo usa cuando tú lo permites.',
    connectorScopeSwitch: 'Cambiar el acceso requiere iniciar sesión de nuevo en {name}.',
    connectorGroupRead: 'Herramientas de lectura',
    connectorGroupWrite: 'Herramientas de escritura',
    connectorStateAllow: 'Permitir',
    connectorStateAsk: 'Preguntar',
    connectorStateDeny: 'Rechazar',
    connectorIndividual: 'Una por una',
    connectorDiffers: '{count} distinta(s) del grupo',
    connectorChanged: 'Cambiada: confírmala de nuevo (está desactivada por ahora)',
    connectorNoTools: 'Este conector no tiene herramientas disponibles ahora.',
    connectorRefresh: 'Actualizar herramientas',
    connectorRefreshed: 'Se actualizaron las herramientas de {name}.',
    connectorSheetTitle: 'Conectar {name}',
    connectorSheetNote: 'Irás a {name} para iniciar sesión y autorizar, y luego volverás a Noureon.',
    connectorSheetPrivacy: 'Una vez conectado, lo que lee el modelo pasa por el servidor de Noureon al proveedor de modelos que elegiste.',
    connectorSheetGo: 'Ir a iniciar sesión',
    connectorSheetBusy: 'Redirigiendo…',
    connectorSheetFailed: 'No se pudo iniciar el acceso. Inténtalo de nuevo en un momento.',
    connectorConnected_notice: 'Conectado: {name}',
    connectorDisconnected_notice: 'Desconectado: {name}',
    connectorErr_denied: 'Cancelaste el acceso.',
    connectorErr_expired: 'El acceso tardó demasiado. Inténtalo de nuevo.',
    connectorErr_bad_state: 'Este enlace de acceso ya no es válido. Vuelve a conectar.',
    connectorErr_failed: 'La conexión falló. Inténtalo de nuevo en un momento.',
    connectorErr_busy: 'Demasiadas personas se están conectando. Inténtalo de nuevo en un momento.',
    connectorSaveFailed: 'El ajuste no se guardó. Inténtalo de nuevo.'
  }
});

export function connectorText(language, key, values = {}) {
  const table = CONNECTOR_TEXTS[language] || CONNECTOR_TEXTS['zh-TW'];
  const template = table[key] ?? CONNECTOR_TEXTS['zh-TW'][key] ?? key;
  return template.replace(/\{(\w+)\}/g, (match, name) => (name in values ? String(values[name]) : match));
}
