// The words of the CLI tools (命令工具: the store page, the "@" menu, its chips) in the app's five languages. {name} placeholders are
// filled by cliText. Chinese calls them 命令工具; the other languages call them CLI. The page that holds them is called 擴充 (Extensions): it has two
// parts, skills and CLI tools, and `entry` and `storeTitle` name the page, `kindSkills` and `kindCli` its parts.

export const CLI_TEXTS = Object.freeze({
  'zh-TW': {
    entry: '擴充',
    storeTitle: '擴充',
    kindSkills: '技能',
    kindCli: '命令工具',
    switchLabel: '擴充的類型',
    back: '返回',
    searchPlaceholder: '搜尋命令工具',
    tabAll: '全部',
    tabMine: '我的',
    sectionMine: '我的命令工具',
    sectionOfficial: '官方',
    official: '官方',
    soon: '即將推出',
    add: '加入',
    added: '已加入',
    remove: '移除',
    details: '詳細資料',
    hideDetails: '收起詳細資料',
    more: '更多',
    allowModel: '允許模型自己使用',
    noneMine: '還沒有加入任何命令工具。',
    noResults: '找不到符合的命令工具。',
    author: '作者',
    license: '授權',
    version: '版本',
    website: '網站',
    needAccount: '命令工具在伺服器上執行，需要先登入雲端帳號。',
    added_notice: '已加入「{name}」。在輸入欄打 @ 就能使用。',
    removed_notice: '已移除「{name}」。',
    menuHeader: '輸入以搜尋命令工具',
    menuLabel: '命令工具',
    menuEmpty: '還沒有加入命令工具。',
    menuOpenStore: '前往命令工具商城',
    menuNoMatch: '沒有符合的命令工具。',
    slashHeader: '輸入以搜尋技能',
    slashLabel: '技能',
    slashEmpty: '還沒有加入技能。',
    slashOpenStore: '前往技能',
    slashNoMatch: '沒有符合的技能。',
    chipClose: '移除 {name}',
    notOnServer: '命令工具只能在伺服器上執行，這則訊息沒有用到它。',
    needToolModel: '這個模型不能呼叫工具，請換一個支援工具的模型才能使用命令工具。'
  },
  en: {
    entry: 'Extensions',
    storeTitle: 'Extensions',
    kindSkills: 'Skills',
    kindCli: 'CLI',
    switchLabel: 'Type of extension',
    back: 'Back',
    searchPlaceholder: 'Search CLI tools',
    tabAll: 'All',
    tabMine: 'Mine',
    sectionMine: 'My CLI tools',
    sectionOfficial: 'Official',
    official: 'Official',
    soon: 'Coming soon',
    add: 'Add',
    added: 'Added',
    remove: 'Remove',
    details: 'Details',
    hideDetails: 'Hide details',
    more: 'More',
    allowModel: 'Let the model use it by itself',
    noneMine: 'No CLI tools added yet.',
    noResults: 'No CLI tools match your search.',
    author: 'Author',
    license: 'License',
    version: 'Version',
    website: 'Website',
    needAccount: 'CLI tools run on the server, so you need to sign in to your cloud account first.',
    added_notice: '“{name}” added. Type @ in the message box to use it.',
    removed_notice: '“{name}” removed.',
    menuHeader: 'Type to search CLI tools',
    menuLabel: 'CLI',
    menuEmpty: 'No CLI tools added yet.',
    menuOpenStore: 'Open the CLI store',
    menuNoMatch: 'No CLI tools match.',
    slashHeader: 'Type to search skills',
    slashLabel: 'Skill',
    slashEmpty: 'No skills added yet.',
    slashOpenStore: 'Open skills',
    slashNoMatch: 'No skill matches.',
    chipClose: 'Remove {name}',
    notOnServer: 'CLI tools only run on the server, so this message was answered without them.',
    needToolModel: 'This model cannot call tools. Pick a model that supports tools to use CLI tools.'
  },
  fr: {
    entry: 'Extensions',
    storeTitle: 'Extensions',
    kindSkills: 'Compétences',
    kindCli: 'CLI',
    switchLabel: 'Type d’extension',
    back: 'Retour',
    searchPlaceholder: 'Rechercher des outils CLI',
    tabAll: 'Tous',
    tabMine: 'Les miens',
    sectionMine: 'Mes outils CLI',
    sectionOfficial: 'Officiels',
    official: 'Officiel',
    soon: 'Bientôt',
    add: 'Ajouter',
    added: 'Ajouté',
    remove: 'Retirer',
    details: 'Détails',
    hideDetails: 'Masquer les détails',
    more: 'Plus',
    allowModel: 'Autoriser le modèle à l’utiliser seul',
    noneMine: 'Aucun outil CLI ajouté.',
    noResults: 'Aucun outil CLI ne correspond.',
    author: 'Auteur',
    license: 'Licence',
    version: 'Version',
    website: 'Site web',
    needAccount: 'Les outils CLI s’exécutent sur le serveur : connectez-vous d’abord à votre compte cloud.',
    added_notice: '« {name} » ajouté. Tapez @ dans la zone de message pour l’utiliser.',
    removed_notice: '« {name} » retiré.',
    menuHeader: 'Tapez pour rechercher des outils CLI',
    menuLabel: 'CLI',
    menuEmpty: 'Aucun outil CLI ajouté.',
    menuOpenStore: 'Ouvrir la boutique CLI',
    menuNoMatch: 'Aucun outil CLI ne correspond.',
    slashHeader: 'Saisissez pour chercher des compétences',
    slashLabel: 'Compétence',
    slashEmpty: 'Aucune compétence ajoutée.',
    slashOpenStore: 'Ouvrir les compétences',
    slashNoMatch: 'Aucune compétence ne correspond.',
    chipClose: 'Retirer {name}',
    notOnServer: 'Les outils CLI ne s’exécutent que sur le serveur : ce message a reçu une réponse sans eux.',
    needToolModel: 'Ce modèle ne peut pas appeler d’outils. Choisissez un modèle compatible pour utiliser les outils CLI.'
  },
  ru: {
    entry: 'Расширения',
    storeTitle: 'Расширения',
    kindSkills: 'Навыки',
    kindCli: 'CLI',
    switchLabel: 'Тип расширения',
    back: 'Назад',
    searchPlaceholder: 'Поиск CLI-инструментов',
    tabAll: 'Все',
    tabMine: 'Мои',
    sectionMine: 'Мои CLI-инструменты',
    sectionOfficial: 'Официальные',
    official: 'Официальный',
    soon: 'Скоро',
    add: 'Добавить',
    added: 'Добавлено',
    remove: 'Удалить',
    details: 'Подробнее',
    hideDetails: 'Скрыть подробности',
    more: 'Ещё',
    allowModel: 'Разрешить модели использовать самой',
    noneMine: 'CLI-инструменты ещё не добавлены.',
    noResults: 'Подходящих CLI-инструментов нет.',
    author: 'Автор',
    license: 'Лицензия',
    version: 'Версия',
    website: 'Сайт',
    needAccount: 'CLI-инструменты работают на сервере: сначала войдите в облачный аккаунт.',
    added_notice: '«{name}» добавлен. Введите @ в поле сообщения, чтобы использовать.',
    removed_notice: '«{name}» удалён.',
    menuHeader: 'Введите для поиска CLI-инструментов',
    menuLabel: 'CLI',
    menuEmpty: 'CLI-инструменты ещё не добавлены.',
    menuOpenStore: 'Открыть магазин CLI',
    menuNoMatch: 'Подходящих CLI-инструментов нет.',
    slashHeader: 'Введите для поиска навыков',
    slashLabel: 'Навык',
    slashEmpty: 'Навыки ещё не добавлены.',
    slashOpenStore: 'Открыть навыки',
    slashNoMatch: 'Нет подходящих навыков.',
    chipClose: 'Удалить {name}',
    notOnServer: 'CLI-инструменты работают только на сервере, поэтому на это сообщение ответили без них.',
    needToolModel: 'Эта модель не умеет вызывать инструменты. Выберите модель с поддержкой инструментов, чтобы использовать CLI-инструменты.'
  },
  es: {
    entry: 'Extensiones',
    storeTitle: 'Extensiones',
    kindSkills: 'Habilidades',
    kindCli: 'CLI',
    switchLabel: 'Tipo de extensión',
    back: 'Volver',
    searchPlaceholder: 'Buscar herramientas CLI',
    tabAll: 'Todas',
    tabMine: 'Mías',
    sectionMine: 'Mis herramientas CLI',
    sectionOfficial: 'Oficiales',
    official: 'Oficial',
    soon: 'Próximamente',
    add: 'Añadir',
    added: 'Añadida',
    remove: 'Quitar',
    details: 'Detalles',
    hideDetails: 'Ocultar detalles',
    more: 'Más',
    allowModel: 'Permitir que el modelo la use por sí solo',
    noneMine: 'Aún no has añadido herramientas CLI.',
    noResults: 'Ninguna herramienta CLI coincide.',
    author: 'Autor',
    license: 'Licencia',
    version: 'Versión',
    website: 'Sitio web',
    needAccount: 'Las herramientas CLI se ejecutan en el servidor: inicia sesión primero en tu cuenta en la nube.',
    added_notice: '«{name}» añadida. Escribe @ en el cuadro de mensaje para usarla.',
    removed_notice: '«{name}» quitada.',
    menuHeader: 'Escribe para buscar herramientas CLI',
    menuLabel: 'CLI',
    menuEmpty: 'Aún no has añadido herramientas CLI.',
    menuOpenStore: 'Abrir la tienda CLI',
    menuNoMatch: 'Ninguna herramienta CLI coincide.',
    slashHeader: 'Escribe para buscar habilidades',
    slashLabel: 'Habilidad',
    slashEmpty: 'Aún no has añadido habilidades.',
    slashOpenStore: 'Abrir habilidades',
    slashNoMatch: 'Ninguna habilidad coincide.',
    chipClose: 'Quitar {name}',
    notOnServer: 'Las herramientas CLI solo se ejecutan en el servidor, así que este mensaje se respondió sin ellas.',
    needToolModel: 'Este modelo no puede llamar a herramientas. Elige un modelo compatible para usar las herramientas CLI.'
  }
});

/** One text in a language (English when the language lacks it), with {name} placeholders filled. */
export function cliText(language, key, values = {}) {
  const table = CLI_TEXTS[language] || CLI_TEXTS.en;
  const template = table[key] ?? CLI_TEXTS.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (values[name] === undefined ? match : String(values[name])));
}
