// The words of the Permissions tab of the settings (network access defaults, and the permissions of the CLI tools, the sites and the secure
// credentials) and of the page of third-party software, in the app's five languages. {name} placeholders are filled by permissionText.

export const PERMISSION_TEXTS = Object.freeze({
  'zh-TW': {
    nav: '權限',
    title: '權限',
    netTitle: '網路存取預設設定',
    netDesc: '命令工具要連到網站時，怎麼決定要不要放行。',
    netNew: '新網站才詢問，已經允許過的不再問',
    netNewDesc: '預設。沒有規則的網站會先問你。',
    netAlways: '一律詢問',
    netAlwaysDesc: '每次回覆第一次連到每個網站都先問，即使已經允許過。',
    manageTitle: '管理權限',
    rowTools: '命令工具',
    rowSites: '網站',
    rowCredentials: '安全憑證',
    back: '返回權限',
    toolsDesc: 'AI 預設只有在你用 @ 選了工具時才會使用它。打開開關，AI 也能在需要時自己使用。',
    toolsNone: '還沒有加入任何命令工具。',
    toolsOpenStore: '前往命令工具商城',
    modelUse: '允許模型自己使用',
    sitesDesc: '命令工具連過的網站會出現在這裡，你可以隨時改成允許、詢問或拒絕。連到伺服器本身與內部網路的位址永遠會被擋下，不能開放。',
    siteAddPlaceholder: '新增網站，例如 example.com',
    siteAdd: '新增',
    siteBad: '這不是有效的網站名稱。',
    ruleAllow: '允許',
    ruleAsk: '詢問',
    ruleDeny: '拒絕',
    siteDefault: '預設',
    siteRemove: '從清單移除',
    siteReset: '還原預設',
    siteMenu: '{host} 的規則',
    credDesc: '登入工具需要的憑證（例如 token、cookie）。加密保存在伺服器，只在命令工具執行時使用，AI 看不到內容。你可以顯示、替換或刪除。',
    credNeeded: '你的命令工具需要',
    credNotSet: '尚未設定',
    credSet: '設定',
    credAddTitle: '新增安全憑證',
    credName: '名稱（大寫英文、數字、底線）',
    credValue: '內容',
    credSave: '儲存',
    credCancel: '取消',
    credShow: '顯示',
    credHide: '隱藏',
    credReplace: '替換',
    credDelete: '刪除',
    credDeleteConfirm: '確定刪除？',
    credNone: '還沒有安全憑證。',
    credSaved: '已儲存「{name}」。',
    credDeleted: '已刪除「{name}」。',
    credBadName: '名稱只能用大寫英文、數字和底線，開頭要是英文。',
    credBadValue: '內容不能是空的，最多 4000 字。',
    credTooMany: '最多 40 個安全憑證。',
    credNeedAccount: '安全憑證保存在伺服器，需要先登入雲端帳號。',
    credUnreachable: '連不上伺服器，請稍後再試。',
    credLoading: '載入中……',
    credFailed: '沒有完成，請再試一次。',
    licensesLink: '第三方軟體與授權',
    licensesTitle: '第三方軟體與授權',
    licensesIntro: 'Noureon 用到下列開放原始碼與第三方軟體。各軟體的授權條款以其官方說明為準。',
    licensesTools: '命令工具',
    licensesSandbox: '伺服器沙盒裡的軟體',
    licensesApp: 'Noureon 使用的程式庫',
    licensesNote: '命令工具都是原作者發布的程式，Noureon 只在沙盒裡執行它們，沒有修改。下載與使用網路上的內容時，請遵守各網站的使用條款與著作權。'
  },
  en: {
    nav: 'Permissions',
    title: 'Permissions',
    netTitle: 'Network access defaults',
    netDesc: 'How a CLI tool is let through when it wants to reach a site.',
    netNew: 'Ask about new sites; do not ask again about ones already allowed',
    netNewDesc: 'The default. A site with no rule is asked about first.',
    netAlways: 'Always ask',
    netAlwaysDesc: 'Ask about every site the first time it is reached in each reply, even one that is allowed.',
    manageTitle: 'Manage permissions',
    rowTools: 'CLI tools',
    rowSites: 'Sites',
    rowCredentials: 'Secure credentials',
    back: 'Back to permissions',
    toolsDesc: 'By default the AI uses a tool only when you choose it with @. Turn the switch on and the AI may also use it by itself when it needs to.',
    toolsNone: 'No CLI tools added yet.',
    toolsOpenStore: 'Open the CLI store',
    modelUse: 'Let the model use it by itself',
    sitesDesc: 'Sites a CLI tool has reached appear here, and you can change each to allow, ask or refuse at any time. Addresses of the server itself and of its internal network are always blocked and cannot be opened.',
    siteAddPlaceholder: 'Add a site, such as example.com',
    siteAdd: 'Add',
    siteBad: 'That is not a valid site name.',
    ruleAllow: 'Allow',
    ruleAsk: 'Ask',
    ruleDeny: 'Refuse',
    siteDefault: 'Default',
    siteRemove: 'Remove from the list',
    siteReset: 'Restore the default',
    siteMenu: 'Rule for {host}',
    credDesc: 'Credentials that a tool needs to log in (a token, a cookie). They are kept encrypted on the server and used only while a CLI tool runs; the AI never sees them. You can show, replace or delete them.',
    credNeeded: 'Your CLI tools need',
    credNotSet: 'Not set',
    credSet: 'Set',
    credAddTitle: 'Add a secure credential',
    credName: 'Name (capital letters, digits, underscores)',
    credValue: 'Value',
    credSave: 'Save',
    credCancel: 'Cancel',
    credShow: 'Show',
    credHide: 'Hide',
    credReplace: 'Replace',
    credDelete: 'Delete',
    credDeleteConfirm: 'Delete it?',
    credNone: 'No secure credentials yet.',
    credSaved: 'Saved “{name}”.',
    credDeleted: 'Deleted “{name}”.',
    credBadName: 'A name is capital letters, digits and underscores, and starts with a letter.',
    credBadValue: 'The value cannot be empty, and is at most 4000 characters.',
    credTooMany: 'At most 40 secure credentials.',
    credNeedAccount: 'Secure credentials are kept on the server: sign in to a cloud account first.',
    credUnreachable: 'The server cannot be reached. Try again in a moment.',
    credLoading: 'Loading…',
    credFailed: 'That did not work. Try again.',
    licensesLink: 'Third-party software and licences',
    licensesTitle: 'Third-party software and licences',
    licensesIntro: 'Noureon uses the open-source and third-party software below. Each licence is as its own project states it.',
    licensesTools: 'CLI tools',
    licensesSandbox: 'Software in the server sandbox',
    licensesApp: 'Libraries Noureon uses',
    licensesNote: 'The CLI tools are the programs their authors publish; Noureon only runs them in a sandbox and does not change them. When you download or use content from the internet, follow each site’s terms of use and copyright law.'
  },
  fr: {
    nav: 'Autorisations',
    title: 'Autorisations',
    netTitle: 'Accès réseau par défaut',
    netDesc: 'Comment un outil en ligne de commande est autorisé lorsqu’il veut atteindre un site.',
    netNew: 'Demander pour les nouveaux sites, pas pour ceux déjà autorisés',
    netNewDesc: 'Par défaut. Un site sans règle fait d’abord l’objet d’une demande.',
    netAlways: 'Toujours demander',
    netAlwaysDesc: 'Demander pour chaque site la première fois qu’il est atteint dans chaque réponse, même s’il est autorisé.',
    manageTitle: 'Gérer les autorisations',
    rowTools: 'Outils CLI',
    rowSites: 'Sites',
    rowCredentials: 'Identifiants sécurisés',
    back: 'Retour aux autorisations',
    toolsDesc: 'Par défaut, l’IA n’utilise un outil que si vous le choisissez avec @. Activez l’interrupteur et l’IA pourra aussi l’utiliser seule quand elle en a besoin.',
    toolsNone: 'Aucun outil CLI ajouté pour le moment.',
    toolsOpenStore: 'Ouvrir la boutique CLI',
    modelUse: 'Laisser le modèle l’utiliser seul',
    sitesDesc: 'Les sites qu’un outil a atteints apparaissent ici, et vous pouvez à tout moment choisir autoriser, demander ou refuser. Les adresses du serveur lui-même et de son réseau interne sont toujours bloquées et ne peuvent pas être ouvertes.',
    siteAddPlaceholder: 'Ajouter un site, par exemple example.com',
    siteAdd: 'Ajouter',
    siteBad: 'Ce n’est pas un nom de site valide.',
    ruleAllow: 'Autoriser',
    ruleAsk: 'Demander',
    ruleDeny: 'Refuser',
    siteDefault: 'Par défaut',
    siteRemove: 'Retirer de la liste',
    siteReset: 'Rétablir par défaut',
    siteMenu: 'Règle pour {host}',
    credDesc: 'Les identifiants dont un outil a besoin pour se connecter (jeton, cookie). Ils sont chiffrés sur le serveur et utilisés seulement pendant l’exécution d’un outil ; l’IA ne les voit jamais. Vous pouvez les afficher, les remplacer ou les supprimer.',
    credNeeded: 'Vos outils CLI ont besoin de',
    credNotSet: 'Non défini',
    credSet: 'Définir',
    credAddTitle: 'Ajouter un identifiant sécurisé',
    credName: 'Nom (majuscules, chiffres, tirets bas)',
    credValue: 'Valeur',
    credSave: 'Enregistrer',
    credCancel: 'Annuler',
    credShow: 'Afficher',
    credHide: 'Masquer',
    credReplace: 'Remplacer',
    credDelete: 'Supprimer',
    credDeleteConfirm: 'Supprimer ?',
    credNone: 'Aucun identifiant sécurisé pour le moment.',
    credSaved: '« {name} » enregistré.',
    credDeleted: '« {name} » supprimé.',
    credBadName: 'Un nom est composé de majuscules, de chiffres et de tirets bas, et commence par une lettre.',
    credBadValue: 'La valeur ne peut pas être vide et fait 4000 caractères au plus.',
    credTooMany: '40 identifiants sécurisés au plus.',
    credNeedAccount: 'Les identifiants sécurisés sont conservés sur le serveur : connectez-vous d’abord à un compte cloud.',
    credUnreachable: 'Le serveur est injoignable. Réessayez dans un instant.',
    credLoading: 'Chargement…',
    credFailed: 'Cela n’a pas fonctionné. Réessayez.',
    licensesLink: 'Logiciels tiers et licences',
    licensesTitle: 'Logiciels tiers et licences',
    licensesIntro: 'Noureon utilise les logiciels libres et tiers ci-dessous. Chaque licence est celle que son projet indique.',
    licensesTools: 'Outils CLI',
    licensesSandbox: 'Logiciels du bac à sable du serveur',
    licensesApp: 'Bibliothèques utilisées par Noureon',
    licensesNote: 'Les outils CLI sont les programmes publiés par leurs auteurs ; Noureon se contente de les exécuter dans un bac à sable, sans les modifier. Lorsque vous téléchargez ou utilisez du contenu sur Internet, respectez les conditions d’utilisation de chaque site et le droit d’auteur.'
  },
  ru: {
    nav: 'Разрешения',
    title: 'Разрешения',
    netTitle: 'Доступ к сети по умолчанию',
    netDesc: 'Как инструмент командной строки получает доступ, когда хочет подключиться к сайту.',
    netNew: 'Спрашивать о новых сайтах, о разрешённых не спрашивать снова',
    netNewDesc: 'По умолчанию. О сайте без правила сначала спросят вас.',
    netAlways: 'Всегда спрашивать',
    netAlwaysDesc: 'Спрашивать о каждом сайте при первом обращении в каждом ответе, даже если он разрешён.',
    manageTitle: 'Управление разрешениями',
    rowTools: 'CLI-инструменты',
    rowSites: 'Сайты',
    rowCredentials: 'Защищённые учётные данные',
    back: 'Назад к разрешениям',
    toolsDesc: 'По умолчанию ИИ использует инструмент, только если вы выбрали его через @. Включите переключатель, и ИИ сможет использовать его сам, когда нужно.',
    toolsNone: 'CLI-инструменты ещё не добавлены.',
    toolsOpenStore: 'Открыть магазин CLI',
    modelUse: 'Разрешить модели использовать самой',
    sitesDesc: 'Сайты, к которым обращались инструменты, появляются здесь; в любой момент можно выбрать «разрешить», «спрашивать» или «отказать». Адреса самого сервера и его внутренней сети всегда заблокированы и не могут быть открыты.',
    siteAddPlaceholder: 'Добавить сайт, например example.com',
    siteAdd: 'Добавить',
    siteBad: 'Это недопустимое имя сайта.',
    ruleAllow: 'Разрешить',
    ruleAsk: 'Спрашивать',
    ruleDeny: 'Отказать',
    siteDefault: 'По умолчанию',
    siteRemove: 'Убрать из списка',
    siteReset: 'Вернуть по умолчанию',
    siteMenu: 'Правило для {host}',
    credDesc: 'Учётные данные, нужные инструменту для входа (токен, cookie). Они хранятся на сервере в зашифрованном виде и используются только во время работы CLI-инструмента; ИИ их не видит. Их можно показать, заменить или удалить.',
    credNeeded: 'Вашим CLI-инструментам нужны',
    credNotSet: 'Не задано',
    credSet: 'Задать',
    credAddTitle: 'Добавить защищённые учётные данные',
    credName: 'Имя (заглавные буквы, цифры, подчёркивания)',
    credValue: 'Значение',
    credSave: 'Сохранить',
    credCancel: 'Отмена',
    credShow: 'Показать',
    credHide: 'Скрыть',
    credReplace: 'Заменить',
    credDelete: 'Удалить',
    credDeleteConfirm: 'Удалить?',
    credNone: 'Защищённых учётных данных пока нет.',
    credSaved: '«{name}» сохранено.',
    credDeleted: '«{name}» удалено.',
    credBadName: 'Имя состоит из заглавных букв, цифр и подчёркиваний и начинается с буквы.',
    credBadValue: 'Значение не может быть пустым, максимум 4000 символов.',
    credTooMany: 'Не более 40 защищённых учётных данных.',
    credNeedAccount: 'Защищённые учётные данные хранятся на сервере: сначала войдите в облачный аккаунт.',
    credUnreachable: 'Сервер недоступен. Попробуйте чуть позже.',
    credLoading: 'Загрузка…',
    credFailed: 'Не получилось. Попробуйте ещё раз.',
    licensesLink: 'Стороннее ПО и лицензии',
    licensesTitle: 'Стороннее ПО и лицензии',
    licensesIntro: 'Noureon использует перечисленное ниже открытое и стороннее ПО. Лицензия каждого проекта — так, как указано в самом проекте.',
    licensesTools: 'CLI-инструменты',
    licensesSandbox: 'ПО в песочнице сервера',
    licensesApp: 'Библиотеки, которые использует Noureon',
    licensesNote: 'CLI-инструменты — это программы, опубликованные их авторами; Noureon лишь запускает их в песочнице и не изменяет. Скачивая или используя материалы из интернета, соблюдайте условия использования сайтов и авторские права.'
  },
  es: {
    nav: 'Permisos',
    title: 'Permisos',
    netTitle: 'Acceso a la red por defecto',
    netDesc: 'Cómo se deja pasar a una herramienta de línea de comandos cuando quiere llegar a un sitio.',
    netNew: 'Preguntar por los sitios nuevos y no volver a preguntar por los ya permitidos',
    netNewDesc: 'Es lo predeterminado. Por un sitio sin regla se pregunta primero.',
    netAlways: 'Preguntar siempre',
    netAlwaysDesc: 'Preguntar por cada sitio la primera vez que se alcanza en cada respuesta, aunque esté permitido.',
    manageTitle: 'Administrar permisos',
    rowTools: 'Herramientas CLI',
    rowSites: 'Sitios',
    rowCredentials: 'Credenciales seguras',
    back: 'Volver a permisos',
    toolsDesc: 'Por defecto la IA solo usa una herramienta si la eliges con @. Activa el interruptor y la IA también podrá usarla sola cuando la necesite.',
    toolsNone: 'Aún no has añadido herramientas CLI.',
    toolsOpenStore: 'Abrir la tienda CLI',
    modelUse: 'Dejar que el modelo la use solo',
    sitesDesc: 'Los sitios a los que ha llegado una herramienta aparecen aquí, y puedes cambiar cada uno a permitir, preguntar o rechazar en cualquier momento. Las direcciones del propio servidor y de su red interna siempre están bloqueadas y no se pueden abrir.',
    siteAddPlaceholder: 'Añadir un sitio, por ejemplo example.com',
    siteAdd: 'Añadir',
    siteBad: 'Ese no es un nombre de sitio válido.',
    ruleAllow: 'Permitir',
    ruleAsk: 'Preguntar',
    ruleDeny: 'Rechazar',
    siteDefault: 'Predeterminado',
    siteRemove: 'Quitar de la lista',
    siteReset: 'Restaurar el valor predeterminado',
    siteMenu: 'Regla para {host}',
    credDesc: 'Las credenciales que una herramienta necesita para iniciar sesión (un token, una cookie). Se guardan cifradas en el servidor y solo se usan mientras se ejecuta una herramienta CLI; la IA nunca las ve. Puedes mostrarlas, reemplazarlas o eliminarlas.',
    credNeeded: 'Tus herramientas CLI necesitan',
    credNotSet: 'Sin definir',
    credSet: 'Definir',
    credAddTitle: 'Añadir una credencial segura',
    credName: 'Nombre (mayúsculas, dígitos, guiones bajos)',
    credValue: 'Valor',
    credSave: 'Guardar',
    credCancel: 'Cancelar',
    credShow: 'Mostrar',
    credHide: 'Ocultar',
    credReplace: 'Reemplazar',
    credDelete: 'Eliminar',
    credDeleteConfirm: '¿Eliminar?',
    credNone: 'Aún no hay credenciales seguras.',
    credSaved: '«{name}» guardada.',
    credDeleted: '«{name}» eliminada.',
    credBadName: 'Un nombre son mayúsculas, dígitos y guiones bajos, y empieza por una letra.',
    credBadValue: 'El valor no puede estar vacío y tiene como máximo 4000 caracteres.',
    credTooMany: 'Como máximo 40 credenciales seguras.',
    credNeedAccount: 'Las credenciales seguras se guardan en el servidor: inicia sesión primero en una cuenta en la nube.',
    credUnreachable: 'No se puede conectar con el servidor. Inténtalo de nuevo en un momento.',
    credLoading: 'Cargando…',
    credFailed: 'No ha funcionado. Inténtalo de nuevo.',
    licensesLink: 'Software de terceros y licencias',
    licensesTitle: 'Software de terceros y licencias',
    licensesIntro: 'Noureon utiliza el software de código abierto y de terceros que se indica abajo. La licencia de cada uno es la que declara su propio proyecto.',
    licensesTools: 'Herramientas CLI',
    licensesSandbox: 'Software del entorno aislado del servidor',
    licensesApp: 'Bibliotecas que usa Noureon',
    licensesNote: 'Las herramientas CLI son los programas que publican sus autores; Noureon solo los ejecuta en un entorno aislado y no los modifica. Al descargar o usar contenido de internet, respeta las condiciones de uso de cada sitio y los derechos de autor.'
  }
});

export function permissionText(language, key, values = {}) {
  const table = PERMISSION_TEXTS[language] || PERMISSION_TEXTS.en;
  const template = table[key] ?? PERMISSION_TEXTS.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (values[name] === undefined ? match : String(values[name])));
}
