// User-facing copy for downloadable file cards. Kept separate from the main
// runtime dictionary so the feature owns its strings and their completeness
// test, and so later phases can add keys without touching shared text.

const FILE_TEXTS = Object.freeze({
  'zh-TW': {
    fileCard: '檔案',
    download: '下載',
    preview: '預覽',
    generating: '正在產生…',
    downloadAll: '全部下載（ZIP）',
    close: '關閉',
    copySource: '複製原始內容',
    copied: '已複製原始內容。',
    copyFailed: '無法複製內容。',
    writingFile: '正在撰寫檔案…',
    receivedCharacters: '已接收 {count} 字元',
    incomplete: '內容不完整：回覆在檔案結束前中斷。',
    blocked: '基於安全考量，無法提供 .{extension} 類型的檔案。',
    tooLarge: '檔案內容過大，無法產生。',
    unavailable: '此檔案格式目前尚未支援。',
    scriptWarning: '這是可執行的腳本檔，執行前請先確認內容。',
    generateFailed: '無法產生檔案：{reason}',
    downloadStarted: '已開始下載 {name}',
    tapAgainToSave: '{name} 已準備好，請再點一次「下載」儲存。',
    previewTitle: '預覽：{name}',
    previewTruncated: '僅顯示前 {count} 行。',
    previewUnavailable: '此格式暫不支援預覽，請直接下載。',
    layoutView: '版面預覽',
    sourceView: '原始內容',
    previewLoading: '正在產生預覽…',
    previewRenderFailed: '無法顯示版面預覽（{reason}），改為顯示文字內容。',
    pageCount: '共 {count} 頁',
    previewFontNote: '版面以這台裝置上的字型繪製，換行與分頁位置可能和 Word 略有不同。',
    slideCount: '共 {count} 張投影片',
    slidePreviewNote: '投影片以檔案使用的相同字型繪製；圖表為示意，PowerPoint 的原生圖表細節可能略有不同。',
    freeSlidePreviewNote: '這是 Python 做出的簡報的預覽，文字與圖表的排版可能和 PowerPoint 略有不同；下載後的檔案才是準確的。',
    sheetPreviewNote: '工作表以這台裝置上的字型繪製；公式結果以 Excel 開啟時的計算為準。',
    sheetRowsLimited: '預覽只顯示前 {count} 列，檔案包含全部資料。',
    sheetFilterButton: '篩選「{name}」',
    sheetSortAscending: '從 A 到 Z 排序',
    sheetSortDescending: '從 Z 到 A 排序',
    sheetFilterAll: '（全選）',
    sheetFilterBlank: '（空白）',
    sheetFilterClear: '清除篩選',
    sheetFilterApply: '確定',
    sheetFilterCancel: '取消',
    sheetFilterNote: '排序與篩選只改變預覽，下載的檔案不變。',
    htmlPreviewNote: '網頁在隔離的框中執行：讀不到 Noureon 的資料與登入狀態，但可能從其他網站載入內容。',
    deckDesign: '簡報設計',
    deckDesignAuto: 'AI 自適應',
    deckDesignAutoHint: 'AI 依內容、對象與你的需求，自己設定 25 項設計參數',
    deckDesignIntro: '請 AI 做簡報時套用；這個對話會記住你的選擇。',
    deckDesignTemplates: '或指定範本',
    deckSampleKicker: '2026 年度報告',
    deckSampleTitle: '年度成果與下一步',
    deckSampleSubtitle: '重點回顧、關鍵數字與明年計畫',
    design: '設計',
    designTabDeck: '簡報',
    designTabDocument: 'Word／PDF 文件',
    documentDesignAutoHint: 'AI 依內容、對象與你的需求，自己設定字型、配色、封面與版面',
    documentDesignIntro: '請 AI 做 Word 或 PDF 文件時套用；這個對話會記住你的選擇。',
    documentSampleHeading: '一、重點摘要',
    familyWord: 'Word 文件',
    familyExcel: 'Excel 試算表',
    familyPowerpoint: 'PowerPoint 簡報',
    familyPdf: 'PDF 文件',
    familyCsv: '表格資料',
    familyText: '文字檔',
    familyMarkdown: 'Markdown 文件',
    familyCode: '程式碼',
    familyData: '資料檔',
    familyWeb: '網頁檔',
    familyCalendar: '行事曆',
    familyContact: '聯絡人',
    familySubtitle: '字幕檔',
    familyImage: '圖片',
    familyArchive: '壓縮檔',
    missing: '檔案不在這台裝置上。',
    rerun: '重新執行',
    rerunning: '正在重新執行……',
    rerunNote: '重新執行的結果可能與原本略有不同。',
    rerunFailed: '無法重新產生檔案：{reason}',
    familyBlocked: '不支援的檔案',
    statLines: '{count} 行',
    statRows: '{count} 列',
    statWords: '約 {count} 字',
    statSheets: '{count} 個工作表',
    statSlides: '{count} 張投影片'
  },
  en: {
    fileCard: 'File',
    download: 'Download',
    preview: 'Preview',
    generating: 'Generating…',
    downloadAll: 'Download all (ZIP)',
    close: 'Close',
    copySource: 'Copy source',
    copied: 'Source copied.',
    copyFailed: 'Could not copy the content.',
    writingFile: 'Writing file…',
    receivedCharacters: '{count} characters received',
    incomplete: 'Incomplete: the response ended before the file was finished.',
    blocked: 'For your safety, .{extension} files cannot be provided.',
    tooLarge: 'This file is too large to generate.',
    unavailable: 'This file format is not supported yet.',
    scriptWarning: 'This is an executable script. Review it before running it.',
    generateFailed: 'Could not generate the file: {reason}',
    downloadStarted: 'Downloading {name}',
    tapAgainToSave: '{name} is ready. Tap Download again to save it.',
    previewTitle: 'Preview: {name}',
    previewTruncated: 'Showing the first {count} lines only.',
    previewUnavailable: 'Preview is not available for this format. Download the file instead.',
    layoutView: 'Page view',
    sourceView: 'Source',
    previewLoading: 'Preparing preview…',
    previewRenderFailed: 'The page view could not be shown ({reason}). Showing the text instead.',
    pageCount: '{count} pages',
    previewFontNote: 'Pages are drawn with the fonts on this device, so line and page breaks may differ slightly from Word.',
    slideCount: '{count} slides',
    slidePreviewNote: 'Slides are drawn with the same fonts the file uses. Charts are approximate; PowerPoint draws its native charts with slightly different details.',
    freeSlidePreviewNote: 'A preview of the deck Python made. PowerPoint may lay out text and charts slightly differently; the downloaded file is the exact one.',
    sheetPreviewNote: 'Sheets are drawn with this device’s fonts; formula results are what Excel calculates when the file opens.',
    sheetRowsLimited: 'The preview shows the first {count} rows; the file contains all of them.',
    sheetFilterButton: 'Filter “{name}”',
    sheetSortAscending: 'Sort A to Z',
    sheetSortDescending: 'Sort Z to A',
    sheetFilterAll: '(Select all)',
    sheetFilterBlank: '(Blanks)',
    sheetFilterClear: 'Clear filter',
    sheetFilterApply: 'OK',
    sheetFilterCancel: 'Cancel',
    sheetFilterNote: 'Sorting and filtering change the preview only, not the downloaded file.',
    htmlPreviewNote: 'The page runs in an isolated frame: it cannot read Noureon’s data or sign-in, but it may load content from other websites.',
    deckDesign: 'Presentation design',
    deckDesignAuto: 'AI adaptive',
    deckDesignAutoHint: 'The AI sets all 25 design parameters for the content, audience and your wish',
    deckDesignIntro: 'Used when you ask the AI for a presentation; this chat remembers your choice.',
    deckDesignTemplates: 'Or pick a template',
    deckSampleKicker: '2026 Annual report',
    deckSampleTitle: 'Our year and what comes next',
    deckSampleSubtitle: 'Highlights, key figures and next year’s plan',
    design: 'Design',
    designTabDeck: 'Presentations',
    designTabDocument: 'Word and PDF',
    documentDesignAutoHint: 'The AI sets fonts, colours, cover and layout for the content, audience and your wish',
    documentDesignIntro: 'Used when you ask the AI for a Word or PDF document; this chat remembers your choice.',
    documentSampleHeading: '1. Summary',
    familyWord: 'Word document',
    familyExcel: 'Excel spreadsheet',
    familyPowerpoint: 'PowerPoint presentation',
    familyPdf: 'PDF document',
    familyCsv: 'Table data',
    familyText: 'Text file',
    familyMarkdown: 'Markdown document',
    familyCode: 'Code',
    familyData: 'Data file',
    familyWeb: 'Web file',
    familyCalendar: 'Calendar',
    familyContact: 'Contact',
    familySubtitle: 'Subtitles',
    familyImage: 'Image',
    familyArchive: 'Archive',
    missing: 'This file is not on this device.',
    rerun: 'Run again',
    rerunning: 'Running again…',
    rerunNote: 'The result may differ slightly from the original.',
    rerunFailed: 'The file could not be made again: {reason}',
    familyBlocked: 'Unsupported file',
    statLines: '{count} lines',
    statRows: '{count} rows',
    statWords: 'About {count} words',
    statSheets: '{count} sheets',
    statSlides: '{count} slides'
  },
  fr: {
    fileCard: 'Fichier',
    download: 'Télécharger',
    preview: 'Aperçu',
    generating: 'Génération…',
    downloadAll: 'Tout télécharger (ZIP)',
    close: 'Fermer',
    copySource: 'Copier la source',
    copied: 'Source copiée.',
    copyFailed: 'Impossible de copier le contenu.',
    writingFile: 'Rédaction du fichier…',
    receivedCharacters: '{count} caractères reçus',
    incomplete: 'Incomplet : la réponse s’est arrêtée avant la fin du fichier.',
    blocked: 'Pour votre sécurité, les fichiers .{extension} ne peuvent pas être fournis.',
    tooLarge: 'Ce fichier est trop volumineux pour être généré.',
    unavailable: 'Ce format de fichier n’est pas encore pris en charge.',
    scriptWarning: 'Ce fichier est un script exécutable. Vérifiez-le avant de l’exécuter.',
    generateFailed: 'Impossible de générer le fichier : {reason}',
    downloadStarted: 'Téléchargement de {name}',
    tapAgainToSave: '{name} est prêt. Touchez à nouveau Télécharger pour l’enregistrer.',
    previewTitle: 'Aperçu : {name}',
    previewTruncated: 'Seules les {count} premières lignes sont affichées.',
    previewUnavailable: 'L’aperçu n’est pas disponible pour ce format. Téléchargez le fichier.',
    layoutView: 'Mise en page',
    sourceView: 'Source',
    previewLoading: 'Préparation de l’aperçu…',
    previewRenderFailed: 'Impossible d’afficher la mise en page ({reason}). Le texte est affiché à la place.',
    pageCount: '{count} pages',
    previewFontNote: 'Les pages utilisent les polices de cet appareil ; les retours à la ligne et les sauts de page peuvent légèrement différer de Word.',
    slideCount: '{count} diapositives',
    slidePreviewNote: 'Les diapositives utilisent les mêmes polices que le fichier. Les graphiques sont indicatifs : PowerPoint dessine ses graphiques natifs avec de légères différences.',
    freeSlidePreviewNote: 'Aperçu de la présentation créée par Python. PowerPoint peut disposer le texte et les graphiques un peu différemment ; le fichier téléchargé fait foi.',
    sheetPreviewNote: 'Les feuilles utilisent les polices de cet appareil ; les résultats des formules sont ceux qu’Excel calcule à l’ouverture.',
    sheetRowsLimited: 'L’aperçu montre les {count} premières lignes ; le fichier les contient toutes.',
    sheetFilterButton: 'Filtrer « {name} »',
    sheetSortAscending: 'Trier de A à Z',
    sheetSortDescending: 'Trier de Z à A',
    sheetFilterAll: '(Tout sélectionner)',
    sheetFilterBlank: '(Vides)',
    sheetFilterClear: 'Effacer le filtre',
    sheetFilterApply: 'OK',
    sheetFilterCancel: 'Annuler',
    sheetFilterNote: 'Le tri et le filtre ne changent que l’aperçu, pas le fichier téléchargé.',
    htmlPreviewNote: 'La page s’exécute dans un cadre isolé : elle ne peut pas lire les données ni la connexion de Noureon, mais peut charger du contenu d’autres sites.',
    deckDesign: 'Design de présentation',
    deckDesignAuto: 'IA adaptative',
    deckDesignAutoHint: 'L’IA règle les 25 paramètres de design selon le contenu, le public et votre demande',
    deckDesignIntro: 'Appliqué quand vous demandez une présentation à l’IA ; cette conversation retient votre choix.',
    deckDesignTemplates: 'Ou choisissez un modèle',
    deckSampleKicker: 'Rapport annuel 2026',
    deckSampleTitle: 'Notre année et la suite',
    deckSampleSubtitle: 'Faits marquants, chiffres clés et plan de l’an prochain',
    design: 'Design',
    designTabDeck: 'Présentations',
    designTabDocument: 'Word et PDF',
    documentDesignAutoHint: 'L’IA règle polices, couleurs, couverture et mise en page selon le contenu, le public et votre demande',
    documentDesignIntro: 'Appliqué quand vous demandez un document Word ou PDF à l’IA ; cette conversation retient votre choix.',
    documentSampleHeading: '1. Synthèse',
    familyWord: 'Document Word',
    familyExcel: 'Classeur Excel',
    familyPowerpoint: 'Présentation PowerPoint',
    familyPdf: 'Document PDF',
    familyCsv: 'Données tabulaires',
    familyText: 'Fichier texte',
    familyMarkdown: 'Document Markdown',
    familyCode: 'Code',
    familyData: 'Fichier de données',
    familyWeb: 'Fichier web',
    familyCalendar: 'Agenda',
    familyContact: 'Contact',
    familySubtitle: 'Sous-titres',
    familyImage: 'Image',
    familyArchive: 'Archive',
    missing: 'Ce fichier n’est pas sur cet appareil.',
    rerun: 'Relancer',
    rerunning: 'Nouvelle exécution…',
    rerunNote: 'Le résultat peut légèrement différer de l’original.',
    rerunFailed: 'Impossible de recréer le fichier : {reason}',
    familyBlocked: 'Fichier non pris en charge',
    statLines: '{count} lignes',
    statRows: '{count} lignes de données',
    statWords: 'Environ {count} mots',
    statSheets: '{count} feuilles',
    statSlides: '{count} diapositives'
  },
  ru: {
    fileCard: 'Файл',
    download: 'Скачать',
    preview: 'Просмотр',
    generating: 'Создание…',
    downloadAll: 'Скачать всё (ZIP)',
    close: 'Закрыть',
    copySource: 'Копировать исходник',
    copied: 'Исходник скопирован.',
    copyFailed: 'Не удалось скопировать содержимое.',
    writingFile: 'Создание файла…',
    receivedCharacters: 'Получено символов: {count}',
    incomplete: 'Неполный файл: ответ прервался до конца файла.',
    blocked: 'В целях безопасности файлы .{extension} недоступны.',
    tooLarge: 'Файл слишком большой для создания.',
    unavailable: 'Этот формат файла пока не поддерживается.',
    scriptWarning: 'Это исполняемый скрипт. Проверьте его перед запуском.',
    generateFailed: 'Не удалось создать файл: {reason}',
    downloadStarted: 'Скачивание {name}',
    tapAgainToSave: '{name} готов. Нажмите «Скачать» ещё раз, чтобы сохранить.',
    previewTitle: 'Просмотр: {name}',
    previewTruncated: 'Показаны только первые строки: {count}.',
    previewUnavailable: 'Просмотр этого формата недоступен. Скачайте файл.',
    layoutView: 'Макет страниц',
    sourceView: 'Исходный текст',
    previewLoading: 'Подготовка просмотра…',
    previewRenderFailed: 'Не удалось показать макет страниц ({reason}). Показан текст.',
    pageCount: 'Страниц: {count}',
    previewFontNote: 'Страницы отрисованы шрифтами этого устройства, поэтому переносы строк и страниц могут немного отличаться от Word.',
    slideCount: 'Слайдов: {count}',
    slidePreviewNote: 'Слайды отрисованы теми же шрифтами, что и в файле. Диаграммы приблизительны: PowerPoint рисует свои диаграммы с небольшими отличиями.',
    freeSlidePreviewNote: 'Предпросмотр презентации, созданной Python. PowerPoint может расположить текст и диаграммы немного иначе; точным является скачанный файл.',
    sheetPreviewNote: 'Листы отрисованы шрифтами этого устройства; результаты формул — те, что Excel вычислит при открытии.',
    sheetRowsLimited: 'В предпросмотре первые {count} строк; в файле есть все.',
    sheetFilterButton: 'Фильтр «{name}»',
    sheetSortAscending: 'Сортировка от А до Я',
    sheetSortDescending: 'Сортировка от Я до А',
    sheetFilterAll: '(Выделить все)',
    sheetFilterBlank: '(Пустые)',
    sheetFilterClear: 'Снять фильтр',
    sheetFilterApply: 'ОК',
    sheetFilterCancel: 'Отмена',
    sheetFilterNote: 'Сортировка и фильтр меняют только предпросмотр, а не скачиваемый файл.',
    htmlPreviewNote: 'Страница работает в изолированной рамке: она не видит данные и вход Noureon, но может загружать содержимое с других сайтов.',
    deckDesign: 'Дизайн презентации',
    deckDesignAuto: 'ИИ-подбор',
    deckDesignAutoHint: 'ИИ сам настроит все 25 параметров дизайна под содержание, аудиторию и ваш запрос',
    deckDesignIntro: 'Применяется, когда вы просите ИИ сделать презентацию; этот чат запомнит выбор.',
    deckDesignTemplates: 'Или выберите шаблон',
    deckSampleKicker: 'Годовой отчёт 2026',
    deckSampleTitle: 'Итоги года и планы',
    deckSampleSubtitle: 'Главное, ключевые цифры и планы на следующий год',
    design: 'Дизайн',
    designTabDeck: 'Презентации',
    designTabDocument: 'Word и PDF',
    documentDesignAutoHint: 'ИИ сам подберёт шрифты, цвета, обложку и вёрстку под содержание, аудиторию и ваш запрос',
    documentDesignIntro: 'Применяется, когда вы просите ИИ сделать документ Word или PDF; этот чат запомнит выбор.',
    documentSampleHeading: '1. Итоги',
    familyWord: 'Документ Word',
    familyExcel: 'Таблица Excel',
    familyPowerpoint: 'Презентация PowerPoint',
    familyPdf: 'Документ PDF',
    familyCsv: 'Табличные данные',
    familyText: 'Текстовый файл',
    familyMarkdown: 'Документ Markdown',
    familyCode: 'Код',
    familyData: 'Файл данных',
    familyWeb: 'Веб-файл',
    familyCalendar: 'Календарь',
    familyContact: 'Контакт',
    familySubtitle: 'Субтитры',
    familyImage: 'Изображение',
    familyArchive: 'Архив',
    missing: 'Этого файла нет на этом устройстве.',
    rerun: 'Запустить снова',
    rerunning: 'Повторный запуск…',
    rerunNote: 'Результат может немного отличаться от исходного.',
    rerunFailed: 'Не удалось создать файл заново: {reason}',
    familyBlocked: 'Неподдерживаемый файл',
    statLines: 'Строк: {count}',
    statRows: 'Строк данных: {count}',
    statWords: 'Около {count} слов',
    statSheets: 'Листов: {count}',
    statSlides: 'Слайдов: {count}'
  },
  es: {
    fileCard: 'Archivo',
    download: 'Descargar',
    preview: 'Vista previa',
    generating: 'Generando…',
    downloadAll: 'Descargar todo (ZIP)',
    close: 'Cerrar',
    copySource: 'Copiar contenido original',
    copied: 'Contenido original copiado.',
    copyFailed: 'No se pudo copiar el contenido.',
    writingFile: 'Escribiendo archivo…',
    receivedCharacters: '{count} caracteres recibidos',
    incomplete: 'Incompleto: la respuesta terminó antes de acabar el archivo.',
    blocked: 'Por tu seguridad, no se pueden proporcionar archivos .{extension}.',
    tooLarge: 'El archivo es demasiado grande para generarlo.',
    unavailable: 'Este formato de archivo aún no es compatible.',
    scriptWarning: 'Es un script ejecutable. Revísalo antes de ejecutarlo.',
    generateFailed: 'No se pudo generar el archivo: {reason}',
    downloadStarted: 'Descargando {name}',
    tapAgainToSave: '{name} está listo. Toca Descargar otra vez para guardarlo.',
    previewTitle: 'Vista previa: {name}',
    previewTruncated: 'Solo se muestran las primeras {count} líneas.',
    previewUnavailable: 'La vista previa no está disponible para este formato. Descarga el archivo.',
    layoutView: 'Vista de página',
    sourceView: 'Fuente',
    previewLoading: 'Preparando la vista previa…',
    previewRenderFailed: 'No se pudo mostrar la vista de página ({reason}). Se muestra el texto.',
    pageCount: '{count} páginas',
    previewFontNote: 'Las páginas se dibujan con las fuentes de este dispositivo; los saltos de línea y de página pueden variar un poco respecto a Word.',
    slideCount: '{count} diapositivas',
    slidePreviewNote: 'Las diapositivas usan las mismas fuentes que el archivo. Los gráficos son aproximados: PowerPoint dibuja sus gráficos nativos con pequeñas diferencias.',
    freeSlidePreviewNote: 'Vista previa de la presentación creada por Python. PowerPoint puede colocar el texto y los gráficos de forma algo distinta; el archivo descargado es el exacto.',
    sheetPreviewNote: 'Las hojas usan las fuentes de este dispositivo; los resultados de las fórmulas son los que Excel calcula al abrir el archivo.',
    sheetRowsLimited: 'La vista previa muestra las primeras {count} filas; el archivo las contiene todas.',
    sheetFilterButton: 'Filtrar «{name}»',
    sheetSortAscending: 'Ordenar de A a Z',
    sheetSortDescending: 'Ordenar de Z a A',
    sheetFilterAll: '(Seleccionar todo)',
    sheetFilterBlank: '(Vacías)',
    sheetFilterClear: 'Borrar filtro',
    sheetFilterApply: 'Aceptar',
    sheetFilterCancel: 'Cancelar',
    sheetFilterNote: 'Ordenar y filtrar solo cambian la vista previa, no el archivo descargado.',
    htmlPreviewNote: 'La página se ejecuta en un marco aislado: no puede leer los datos ni la sesión de Noureon, pero puede cargar contenido de otros sitios.',
    deckDesign: 'Diseño de presentación',
    deckDesignAuto: 'IA adaptativa',
    deckDesignAutoHint: 'La IA ajusta los 25 parámetros de diseño según el contenido, el público y lo que pidas',
    deckDesignIntro: 'Se aplica cuando pides una presentación a la IA; este chat recuerda tu elección.',
    deckDesignTemplates: 'O elige una plantilla',
    deckSampleKicker: 'Informe anual 2026',
    deckSampleTitle: 'Nuestro año y lo que viene',
    deckSampleSubtitle: 'Aspectos destacados, cifras clave y plan del próximo año',
    design: 'Diseño',
    designTabDeck: 'Presentaciones',
    designTabDocument: 'Word y PDF',
    documentDesignAutoHint: 'La IA ajusta fuentes, colores, portada y diseño según el contenido, el público y lo que pidas',
    documentDesignIntro: 'Se aplica cuando pides un documento de Word o PDF a la IA; este chat recuerda tu elección.',
    documentSampleHeading: '1. Resumen',
    familyWord: 'Documento de Word',
    familyExcel: 'Hoja de cálculo de Excel',
    familyPowerpoint: 'Presentación de PowerPoint',
    familyPdf: 'Documento PDF',
    familyCsv: 'Datos tabulares',
    familyText: 'Archivo de texto',
    familyMarkdown: 'Documento Markdown',
    familyCode: 'Código',
    familyData: 'Archivo de datos',
    familyWeb: 'Archivo web',
    familyCalendar: 'Calendario',
    familyContact: 'Contacto',
    familySubtitle: 'Subtítulos',
    familyImage: 'Imagen',
    familyArchive: 'Archivo comprimido',
    missing: 'Este archivo no está en este dispositivo.',
    rerun: 'Volver a ejecutar',
    rerunning: 'Ejecutando de nuevo…',
    rerunNote: 'El resultado puede variar un poco respecto al original.',
    rerunFailed: 'No se pudo volver a crear el archivo: {reason}',
    familyBlocked: 'Archivo no compatible',
    statLines: '{count} líneas',
    statRows: '{count} filas',
    statWords: 'Unas {count} palabras',
    statSheets: '{count} hojas',
    statSlides: '{count} diapositivas'
  }
});

export const SUPPORTED_FILE_TEXT_LANGUAGES = Object.freeze(Object.keys(FILE_TEXTS));

export function getFileTexts(language = 'zh-TW') {
  return FILE_TEXTS[language] || FILE_TEXTS['zh-TW'];
}

export function getFileText(language, key, replacements = {}) {
  let value = getFileTexts(language)[key] || FILE_TEXTS['zh-TW'][key] || key;
  Object.entries(replacements).forEach(([name, replacement]) => {
    value = value.replaceAll(`{${name}}`, String(replacement));
  });
  return value;
}

export function formatFileCount(language, count) {
  try {
    return new Intl.NumberFormat(language === 'zh-TW' ? 'zh-Hant-TW' : language).format(count);
  } catch {
    return String(count);
  }
}

export function formatFileSize(language, bytes) {
  const units = ['B', 'KB', 'MB', 'GB'];
  let value = Number(bytes) || 0;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }
  const digits = unitIndex === 0 || value >= 100 ? 0 : 1;
  let formatted;
  try {
    formatted = new Intl.NumberFormat(language === 'zh-TW' ? 'zh-Hant-TW' : language, {
      maximumFractionDigits: digits,
      minimumFractionDigits: 0
    }).format(value);
  } catch {
    formatted = value.toFixed(digits);
  }
  return `${formatted} ${units[unitIndex]}`;
}
