// The words of the quiz card (docs/superpowers/specs/2026-10-09-quiz-card-design.md) in the app's five languages. Loaded with the card, only when a ```quiz block is on the page.
// {n}, {total}, {count}, {right}, {letters}, {reason} placeholders are filled by quizText.

export const QUIZ_TEXTS = Object.freeze({
  'zh-TW': {
    quizTitle: '測驗',
    quizPreparing: '測驗準備中…',
    quizInvalid: '這份測驗的格式有問題（{reason}），所以顯示原文。可以請模型重新產生。',
    quizErr_empty: '內容是空的',
    quizErr_incomplete: '內容不完整',
    quizErr_not_json: '不是有效的 JSON',
    quizErr_not_object: '不是測驗格式',
    quizErr_no_questions: '沒有題目',
    quizErr_too_many_questions: '題目超過 30 題',
    quizErr_bad_question: '第 {n} 題缺少題目',
    quizErr_bad_options: '第 {n} 題的選項不對',
    quizErr_bad_answer: '第 {n} 題的答案不對',
    quizHint: '提示',
    quizHintLabel: '提示',
    quizPickOne: '選一個答案',
    quizPickMany: '選出 {count} 個正確答案',
    quizOf: '第 {n} 題，共 {total} 題',
    quizConfirm: '確認',
    quizNext: '下一題',
    quizSeeResults: '看結果',
    quizCorrect: '答對了',
    quizWrong: '答錯了',
    quizAnswerIs: '正確答案是 {letters}',
    quizYou: '你選的',
    quizRight: '正確答案',
    quizExtra: '補充說明',
    quizShowOthers: '看其他選項為什麼不對',
    quizHideOthers: '收起其他選項',
    quizDone: '測驗完成',
    quizScoreLine: '答對 {right} 題',
    quizAllRight: '全部答對！',
    quizMissed: '答錯的題目',
    quizQuestionN: '第 {n} 題',
    quizRetryMissed: '只重做答錯的',
    quizRestart: '全部重來',
    quizRound: '第 {n} 輪'
  },
  en: {
    quizTitle: 'Quiz',
    quizPreparing: 'Preparing the quiz…',
    quizInvalid: 'This quiz is not in the right format ({reason}), so its text is shown. You can ask the model to make it again.',
    quizErr_empty: 'it is empty',
    quizErr_incomplete: 'it is cut off',
    quizErr_not_json: 'it is not valid JSON',
    quizErr_not_object: 'it is not a quiz',
    quizErr_no_questions: 'it has no questions',
    quizErr_too_many_questions: 'it has more than 30 questions',
    quizErr_bad_question: 'question {n} has no text',
    quizErr_bad_options: 'the options of question {n} are wrong',
    quizErr_bad_answer: 'the answer of question {n} is wrong',
    quizHint: 'Hint',
    quizHintLabel: 'Hint',
    quizPickOne: 'Choose one answer',
    quizPickMany: 'Choose {count} correct answers',
    quizOf: 'Question {n} of {total}',
    quizConfirm: 'Check',
    quizNext: 'Next',
    quizSeeResults: 'See results',
    quizCorrect: 'Correct',
    quizWrong: 'Not quite',
    quizAnswerIs: 'The answer is {letters}',
    quizYou: 'Your choice',
    quizRight: 'Correct answer',
    quizExtra: 'Good to know',
    quizShowOthers: 'Why the other options are wrong',
    quizHideOthers: 'Hide the other options',
    quizDone: 'Quiz complete',
    quizScoreLine: '{right} correct',
    quizAllRight: 'All correct!',
    quizMissed: 'Questions you missed',
    quizQuestionN: 'Question {n}',
    quizRetryMissed: 'Redo the ones I missed',
    quizRestart: 'Start again',
    quizRound: 'Round {n}'
  },
  fr: {
    quizTitle: 'Quiz',
    quizPreparing: 'Préparation du quiz…',
    quizInvalid: 'Ce quiz n’a pas le bon format ({reason}) : son texte est affiché. Vous pouvez demander au modèle de le refaire.',
    quizErr_empty: 'il est vide',
    quizErr_incomplete: 'il est coupé',
    quizErr_not_json: 'ce n’est pas du JSON valide',
    quizErr_not_object: 'ce n’est pas un quiz',
    quizErr_no_questions: 'il n’a aucune question',
    quizErr_too_many_questions: 'il a plus de 30 questions',
    quizErr_bad_question: 'la question {n} n’a pas de texte',
    quizErr_bad_options: 'les options de la question {n} sont incorrectes',
    quizErr_bad_answer: 'la réponse de la question {n} est incorrecte',
    quizHint: 'Indice',
    quizHintLabel: 'Indice',
    quizPickOne: 'Choisissez une réponse',
    quizPickMany: 'Choisissez {count} bonnes réponses',
    quizOf: 'Question {n} sur {total}',
    quizConfirm: 'Valider',
    quizNext: 'Suivante',
    quizSeeResults: 'Voir les résultats',
    quizCorrect: 'Bonne réponse',
    quizWrong: 'Pas tout à fait',
    quizAnswerIs: 'La réponse est {letters}',
    quizYou: 'Votre choix',
    quizRight: 'Bonne réponse',
    quizExtra: 'Pour aller plus loin',
    quizShowOthers: 'Pourquoi les autres options sont fausses',
    quizHideOthers: 'Masquer les autres options',
    quizDone: 'Quiz terminé',
    quizScoreLine: '{right} bonnes réponses',
    quizAllRight: 'Tout est juste !',
    quizMissed: 'Questions manquées',
    quizQuestionN: 'Question {n}',
    quizRetryMissed: 'Refaire les questions manquées',
    quizRestart: 'Recommencer',
    quizRound: 'Tour {n}'
  },
  ru: {
    quizTitle: 'Тест',
    quizPreparing: 'Готовим тест…',
    quizInvalid: 'Формат этого теста неверный ({reason}), поэтому показан его текст. Можно попросить модель составить его заново.',
    quizErr_empty: 'он пустой',
    quizErr_incomplete: 'он обрезан',
    quizErr_not_json: 'это не корректный JSON',
    quizErr_not_object: 'это не тест',
    quizErr_no_questions: 'в нём нет вопросов',
    quizErr_too_many_questions: 'в нём больше 30 вопросов',
    quizErr_bad_question: 'у вопроса {n} нет текста',
    quizErr_bad_options: 'варианты вопроса {n} неверны',
    quizErr_bad_answer: 'ответ вопроса {n} неверен',
    quizHint: 'Подсказка',
    quizHintLabel: 'Подсказка',
    quizPickOne: 'Выберите один ответ',
    quizPickMany: 'Выберите правильных ответов: {count}',
    quizOf: 'Вопрос {n} из {total}',
    quizConfirm: 'Проверить',
    quizNext: 'Дальше',
    quizSeeResults: 'Результаты',
    quizCorrect: 'Верно',
    quizWrong: 'Неверно',
    quizAnswerIs: 'Правильный ответ: {letters}',
    quizYou: 'Ваш выбор',
    quizRight: 'Правильный ответ',
    quizExtra: 'Стоит знать',
    quizShowOthers: 'Почему другие варианты неверны',
    quizHideOthers: 'Скрыть другие варианты',
    quizDone: 'Тест завершён',
    quizScoreLine: 'Верно: {right}',
    quizAllRight: 'Все верно!',
    quizMissed: 'Вопросы с ошибками',
    quizQuestionN: 'Вопрос {n}',
    quizRetryMissed: 'Пройти ошибки заново',
    quizRestart: 'Начать заново',
    quizRound: 'Круг {n}'
  },
  es: {
    quizTitle: 'Cuestionario',
    quizPreparing: 'Preparando el cuestionario…',
    quizInvalid: 'Este cuestionario no tiene el formato correcto ({reason}), así que se muestra su texto. Puedes pedirle al modelo que lo haga de nuevo.',
    quizErr_empty: 'está vacío',
    quizErr_incomplete: 'está cortado',
    quizErr_not_json: 'no es un JSON válido',
    quizErr_not_object: 'no es un cuestionario',
    quizErr_no_questions: 'no tiene preguntas',
    quizErr_too_many_questions: 'tiene más de 30 preguntas',
    quizErr_bad_question: 'la pregunta {n} no tiene texto',
    quizErr_bad_options: 'las opciones de la pregunta {n} son incorrectas',
    quizErr_bad_answer: 'la respuesta de la pregunta {n} es incorrecta',
    quizHint: 'Pista',
    quizHintLabel: 'Pista',
    quizPickOne: 'Elige una respuesta',
    quizPickMany: 'Elige {count} respuestas correctas',
    quizOf: 'Pregunta {n} de {total}',
    quizConfirm: 'Comprobar',
    quizNext: 'Siguiente',
    quizSeeResults: 'Ver resultados',
    quizCorrect: 'Correcto',
    quizWrong: 'No exactamente',
    quizAnswerIs: 'La respuesta es {letters}',
    quizYou: 'Tu elección',
    quizRight: 'Respuesta correcta',
    quizExtra: 'Para saber más',
    quizShowOthers: 'Por qué las otras opciones son incorrectas',
    quizHideOthers: 'Ocultar las otras opciones',
    quizDone: 'Cuestionario completado',
    quizScoreLine: '{right} correctas',
    quizAllRight: '¡Todo correcto!',
    quizMissed: 'Preguntas falladas',
    quizQuestionN: 'Pregunta {n}',
    quizRetryMissed: 'Repetir las falladas',
    quizRestart: 'Empezar de nuevo',
    quizRound: 'Ronda {n}'
  }
});

export function quizText(language, key, values = {}) {
  const table = QUIZ_TEXTS[language] || QUIZ_TEXTS.en;
  const template = table[key] ?? QUIZ_TEXTS.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (values[name] === undefined ? match : String(values[name])));
}
