// The words of the deep research (menu, composer chip, cards, reader) in the app's five languages. {name} placeholders are filled by
// researchText. The report itself is written by the model, in the language of the topic.

export const RESEARCH_TEXTS = Object.freeze({
  'zh-TW': {
    menuLabel: '深度研究',
    menuDescription: '自主搜尋，整理成有引用的報告',
    closeChip: '關閉深度研究',
    planChipClose: '取消修改計劃',
    unsupportedModel: '深度研究目前不支援 Gemini 模型，請換一個模型。',
    needToolModel: '這個模型不能自己呼叫搜尋工具，請換一個支援工具的模型。',
    needSearchKey: '深度研究需要在設定中填入 Tavily 或 TinyFish 的搜尋金鑰。',
    needAccount: '深度研究在伺服器上執行，需要先登入雲端帳號。',
    needServer: '深度研究目前無法在伺服器上執行，請稍後再試。',
    busy: '伺服器正忙，請稍後再試。',
    startFailed: '深度研究沒能開始，請稍後再試。',
    planning: '正在擬定研究計劃…',
    intro: '深度研究已開始處理「{topic}」。它會先提供研究計劃，接著展開資料蒐集與分析，完成後報告會顯示在這裡。',
    edit: '編輯',
    cancel: '取消',
    start: '開始',
    revising: '正在修改計劃…',
    editingHint: '倒數已暫停。在輸入欄寫下想修改的地方並送出，計劃會更新。',
    researching: '正在研究…',
    writing: '正在撰寫報告…',
    searched: '已搜尋 {n} 次',
    elapsed: '已用 {t}',
    pause: '暫停',
    resume: '繼續',
    pausing: '做完這一輪就暫停…',
    paused: '已暫停',
    stop: '停止',
    stopAsk: '要用目前找到的資料寫一份簡短報告嗎？',
    stopWrite: '寫報告',
    stopDiscard: '放棄',
    stopBack: '繼續研究',
    stopped: '研究已停止。',
    failed: '研究沒有完成：{reason}',
    wrongPhase: '現在不能做這個動作。',
    actionFailed: '沒能送出這個動作，請再試一次。',
    doneStats: '研究完成時間：{t} · {c} 個引用 · {s} 次搜尋',
    download: '下載',
    expand: '展開',
    copy: '複製內容',
    copied: '已複製',
    exportMarkdown: '匯出 Markdown',
    close: '關閉',
    toc: '目錄',
    sources: '資料來源',
    activity: '活動',
    sourcesCount: '引用 {n} 筆',
    activityTitle: '活動 · 研究時間',
    workedFor: '工作了 {t}',
    finished: '完成',
    reportMade: '已產生報告',
    openSource: '開啟來源',
    prevSource: '上一筆',
    nextSource: '下一筆',
    exportWord: '匯出 Word',
    exportPdf: '匯出 PDF',
    preparing: '準備中…',
    exportFailed: '匯出沒有成功：{reason}',
    pauseExpired: '研究暫停太久，已經結束。請重新開始一次研究。',
    references: '參考資料',
  },
  en: {
    menuLabel: 'Deep research',
    menuDescription: 'Searches on its own and writes a report with citations',
    closeChip: 'Turn off deep research',
    planChipClose: 'Stop changing the plan',
    unsupportedModel: 'Deep research does not support Gemini models yet. Please pick another model.',
    needToolModel: 'This model cannot call search tools by itself. Please pick a model that supports tools.',
    needSearchKey: 'Deep research needs a Tavily or TinyFish search key in Settings.',
    needAccount: 'Deep research runs on the server, so you need to sign in to your cloud account first.',
    needServer: 'Deep research cannot run on the server right now. Please try again later.',
    busy: 'The server is busy. Please try again in a moment.',
    startFailed: 'Deep research could not start. Please try again later.',
    planning: 'Drafting the research plan…',
    intro: 'Deep research has started on “{topic}”. It will first give a research plan, then gather and analyze sources; the report will appear here when it is done.',
    edit: 'Edit',
    cancel: 'Cancel',
    start: 'Start',
    revising: 'Changing the plan…',
    editingHint: 'The countdown is paused. Write what to change in the message box and send it; the plan will be updated.',
    researching: 'Researching…',
    writing: 'Writing the report…',
    searched: '{n} searches',
    elapsed: '{t} so far',
    pause: 'Pause',
    resume: 'Resume',
    pausing: 'Pausing after this round…',
    paused: 'Paused',
    stop: 'Stop',
    stopAsk: 'Write a short report from what has been found so far?',
    stopWrite: 'Write report',
    stopDiscard: 'Discard',
    stopBack: 'Keep researching',
    stopped: 'Research stopped.',
    failed: 'The research did not finish: {reason}',
    wrongPhase: 'That cannot be done right now.',
    actionFailed: 'That could not be sent. Please try again.',
    doneStats: 'Research completed in {t} · {c} citations · {s} searches',
    download: 'Download',
    expand: 'Expand',
    copy: 'Copy content',
    copied: 'Copied',
    exportMarkdown: 'Export Markdown',
    close: 'Close',
    toc: 'Contents',
    sources: 'Sources',
    activity: 'Activity',
    sourcesCount: '{n} citations',
    activityTitle: 'Activity · research time',
    workedFor: 'Worked for {t}',
    finished: 'Done',
    reportMade: 'Report created',
    openSource: 'Open source',
    prevSource: 'Previous',
    nextSource: 'Next',
    exportWord: 'Export Word',
    exportPdf: 'Export PDF',
    preparing: 'Preparing…',
    exportFailed: 'The export failed: {reason}',
    pauseExpired: 'The research was paused for too long and has ended. Please start it again.',
    references: 'References',
  },
  fr: {
    menuLabel: 'Recherche approfondie',
    menuDescription: 'Cherche seule et rédige un rapport avec citations',
    closeChip: 'Désactiver la recherche approfondie',
    planChipClose: 'Ne plus modifier le plan',
    unsupportedModel: 'La recherche approfondie ne prend pas encore en charge les modèles Gemini. Choisissez un autre modèle.',
    needToolModel: 'Ce modèle ne peut pas appeler seul des outils de recherche. Choisissez un modèle compatible avec les outils.',
    needSearchKey: 'La recherche approfondie nécessite une clé de recherche Tavily ou TinyFish dans les réglages.',
    needAccount: 'La recherche approfondie s’exécute sur le serveur : connectez-vous d’abord à votre compte cloud.',
    needServer: 'La recherche approfondie ne peut pas s’exécuter sur le serveur pour le moment. Réessayez plus tard.',
    busy: 'Le serveur est occupé. Réessayez dans un instant.',
    startFailed: 'La recherche approfondie n’a pas pu démarrer. Réessayez plus tard.',
    planning: 'Rédaction du plan de recherche…',
    intro: 'La recherche approfondie sur « {topic} » a commencé. Elle propose d’abord un plan, puis collecte et analyse les sources ; le rapport s’affichera ici une fois terminé.',
    edit: 'Modifier',
    cancel: 'Annuler',
    start: 'Lancer',
    revising: 'Modification du plan…',
    editingHint: 'Le compte à rebours est en pause. Écrivez ce qu’il faut changer dans la zone de message et envoyez : le plan sera mis à jour.',
    researching: 'Recherche en cours…',
    writing: 'Rédaction du rapport…',
    searched: '{n} recherches',
    elapsed: '{t} écoulées',
    pause: 'Pause',
    resume: 'Reprendre',
    pausing: 'Pause à la fin de ce tour…',
    paused: 'En pause',
    stop: 'Arrêter',
    stopAsk: 'Rédiger un court rapport avec ce qui a été trouvé jusqu’ici ?',
    stopWrite: 'Rédiger le rapport',
    stopDiscard: 'Abandonner',
    stopBack: 'Continuer la recherche',
    stopped: 'Recherche arrêtée.',
    failed: 'La recherche ne s’est pas terminée : {reason}',
    wrongPhase: 'Cette action est impossible pour le moment.',
    actionFailed: 'Cette action n’a pas pu être envoyée. Réessayez.',
    doneStats: 'Recherche terminée en {t} · {c} citations · {s} recherches',
    download: 'Télécharger',
    expand: 'Agrandir',
    copy: 'Copier le contenu',
    copied: 'Copié',
    exportMarkdown: 'Exporter en Markdown',
    close: 'Fermer',
    toc: 'Sommaire',
    sources: 'Sources',
    activity: 'Activité',
    sourcesCount: '{n} citations',
    activityTitle: 'Activité · durée de recherche',
    workedFor: 'Travail de {t}',
    finished: 'Terminé',
    reportMade: 'Rapport créé',
    openSource: 'Ouvrir la source',
    prevSource: 'Précédente',
    nextSource: 'Suivante',
    exportWord: 'Exporter en Word',
    exportPdf: 'Exporter en PDF',
    preparing: 'Préparation…',
    exportFailed: 'L’export a échoué : {reason}',
    pauseExpired: 'La recherche est restée trop longtemps en pause et s’est terminée. Veuillez la relancer.',
    references: 'Références',
  },
  ru: {
    menuLabel: 'Глубокое исследование',
    menuDescription: 'Ищет сам и пишет отчёт со ссылками на источники',
    closeChip: 'Отключить глубокое исследование',
    planChipClose: 'Больше не менять план',
    unsupportedModel: 'Глубокое исследование пока не поддерживает модели Gemini. Выберите другую модель.',
    needToolModel: 'Эта модель не умеет сама вызывать инструменты поиска. Выберите модель с поддержкой инструментов.',
    needSearchKey: 'Для глубокого исследования нужен ключ поиска Tavily или TinyFish в настройках.',
    needAccount: 'Глубокое исследование выполняется на сервере: сначала войдите в облачный аккаунт.',
    needServer: 'Сейчас глубокое исследование нельзя выполнить на сервере. Попробуйте позже.',
    busy: 'Сервер занят. Попробуйте через минуту.',
    startFailed: 'Не удалось начать глубокое исследование. Попробуйте позже.',
    planning: 'Составляется план исследования…',
    intro: 'Глубокое исследование по теме «{topic}» началось. Сначала будет план, затем сбор и анализ источников; готовый отчёт появится здесь.',
    edit: 'Изменить',
    cancel: 'Отмена',
    start: 'Начать',
    revising: 'План меняется…',
    editingHint: 'Отсчёт приостановлен. Напишите в поле ввода, что изменить, и отправьте — план обновится.',
    researching: 'Исследование…',
    writing: 'Пишется отчёт…',
    searched: 'Поисков: {n}',
    elapsed: 'Прошло {t}',
    pause: 'Пауза',
    resume: 'Продолжить',
    pausing: 'Пауза после этого круга…',
    paused: 'На паузе',
    stop: 'Остановить',
    stopAsk: 'Написать краткий отчёт по тому, что найдено к этому моменту?',
    stopWrite: 'Написать отчёт',
    stopDiscard: 'Отказаться',
    stopBack: 'Продолжить исследование',
    stopped: 'Исследование остановлено.',
    failed: 'Исследование не завершилось: {reason}',
    wrongPhase: 'Сейчас это действие недоступно.',
    actionFailed: 'Не удалось отправить действие. Попробуйте ещё раз.',
    doneStats: 'Исследование заняло {t} · ссылок: {c} · поисков: {s}',
    download: 'Скачать',
    expand: 'Развернуть',
    copy: 'Копировать содержимое',
    copied: 'Скопировано',
    exportMarkdown: 'Экспорт в Markdown',
    close: 'Закрыть',
    toc: 'Оглавление',
    sources: 'Источники',
    activity: 'Активность',
    sourcesCount: 'Ссылок: {n}',
    activityTitle: 'Активность · время исследования',
    workedFor: 'Работа заняла {t}',
    finished: 'Готово',
    reportMade: 'Отчёт создан',
    openSource: 'Открыть источник',
    prevSource: 'Назад',
    nextSource: 'Далее',
    exportWord: 'Экспорт в Word',
    exportPdf: 'Экспорт в PDF',
    preparing: 'Подготовка…',
    exportFailed: 'Экспорт не удался: {reason}',
    pauseExpired: 'Исследование слишком долго стояло на паузе и завершено. Запустите его заново.',
    references: 'Источники',
  },
  es: {
    menuLabel: 'Investigación profunda',
    menuDescription: 'Busca por su cuenta y escribe un informe con citas',
    closeChip: 'Desactivar la investigación profunda',
    planChipClose: 'Dejar de modificar el plan',
    unsupportedModel: 'La investigación profunda aún no admite modelos de Gemini. Elige otro modelo.',
    needToolModel: 'Este modelo no puede llamar por sí solo a herramientas de búsqueda. Elige un modelo compatible con herramientas.',
    needSearchKey: 'La investigación profunda necesita una clave de búsqueda de Tavily o TinyFish en Ajustes.',
    needAccount: 'La investigación profunda se ejecuta en el servidor: primero inicia sesión en tu cuenta en la nube.',
    needServer: 'Ahora mismo la investigación profunda no puede ejecutarse en el servidor. Inténtalo más tarde.',
    busy: 'El servidor está ocupado. Inténtalo en un momento.',
    startFailed: 'No se pudo iniciar la investigación profunda. Inténtalo más tarde.',
    planning: 'Redactando el plan de investigación…',
    intro: 'La investigación profunda sobre «{topic}» ha comenzado. Primero propone un plan y después reúne y analiza fuentes; el informe aparecerá aquí al terminar.',
    edit: 'Editar',
    cancel: 'Cancelar',
    start: 'Iniciar',
    revising: 'Modificando el plan…',
    editingHint: 'La cuenta atrás está en pausa. Escribe qué cambiar en el cuadro de mensaje y envíalo: el plan se actualizará.',
    researching: 'Investigando…',
    writing: 'Redactando el informe…',
    searched: '{n} búsquedas',
    elapsed: '{t} transcurridos',
    pause: 'Pausar',
    resume: 'Reanudar',
    pausing: 'Pausa al terminar esta ronda…',
    paused: 'En pausa',
    stop: 'Detener',
    stopAsk: '¿Escribir un informe breve con lo encontrado hasta ahora?',
    stopWrite: 'Escribir informe',
    stopDiscard: 'Descartar',
    stopBack: 'Seguir investigando',
    stopped: 'Investigación detenida.',
    failed: 'La investigación no terminó: {reason}',
    wrongPhase: 'Eso no se puede hacer ahora.',
    actionFailed: 'No se pudo enviar. Inténtalo de nuevo.',
    doneStats: 'Investigación completada en {t} · {c} citas · {s} búsquedas',
    download: 'Descargar',
    expand: 'Ampliar',
    copy: 'Copiar contenido',
    copied: 'Copiado',
    exportMarkdown: 'Exportar a Markdown',
    close: 'Cerrar',
    toc: 'Contenido',
    sources: 'Fuentes',
    activity: 'Actividad',
    sourcesCount: '{n} citas',
    activityTitle: 'Actividad · tiempo de investigación',
    workedFor: 'Trabajó {t}',
    finished: 'Listo',
    reportMade: 'Informe creado',
    openSource: 'Abrir fuente',
    prevSource: 'Anterior',
    nextSource: 'Siguiente',
    exportWord: 'Exportar a Word',
    exportPdf: 'Exportar a PDF',
    preparing: 'Preparando…',
    exportFailed: 'La exportación falló: {reason}',
    pauseExpired: 'La investigación estuvo en pausa demasiado tiempo y terminó. Vuelve a iniciarla.',
    references: 'Referencias',
  }
});

export const RESEARCH_TEXT_LANGUAGES = Object.freeze(Object.keys(RESEARCH_TEXTS));

export function researchText(language, key, values = {}) {
  const template = RESEARCH_TEXTS[language]?.[key] ?? RESEARCH_TEXTS.en[key] ?? '';
  return template.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ''));
}

/** "13m 18s", "42s", "1h 5m": the way the times of a research are written, the same in every language. */
export function formatResearchTime(ms) {
  const total = Math.max(0, Math.round((Number(ms) || 0) / 1000));
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const seconds = total % 60;
  if (hours) return `${hours}h ${minutes}m`;
  if (minutes) return `${minutes}m ${seconds}s`;
  return `${seconds}s`;
}
