// The words of the skills part of the Extensions page (the list, the window that takes a pasted skill, the notices and the reasons a skill is refused) in the
// app's five languages. Apart from the other words of the page (cli-texts.js) because they are only needed when the page is opened. {name} and {count}
// placeholders are filled by skillText.

export const SKILL_TEXTS = Object.freeze({
  'zh-TW': {
    skillsSearchPlaceholder: '搜尋技能',
    skillsSoon: '技能即將推出',
    skillsSoonNote: '技能是教模型怎麼做一件事的說明與流程，上架後會出現在這裡。',
    skillsNoneMine: '還沒有加入任何技能。',
    skillsNoResults: '找不到符合的技能。',
    skillsSectionMine: '我的技能',
    skillPaste: '貼上技能',
    skillSourceYours: '你自己加入的',
    skillSourceOfficial: '官方',
    skillAdded_notice: '已加入技能「{name}」。',
    skillRemoved_notice: '已移除技能「{name}」。',
    skillsNeedAccount: '貼上或上傳技能需要先登入雲端帳號，技能會存在你的帳號裡。',
    skillPasteTitle: '貼上技能',
    skillPasteHint: '貼上 SKILL.md 的完整文字：開頭要有 name 與 description，下面是技能的內容。',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: 做什麼、什麼時候用\n---\n\n步驟與做法……',
    skillPasteWarning: '技能的內容會成為模型收到的指示。只加入你信任的內容，加入前請讀過全文。',
    skillPasteAdd: '加入',
    skillPasteReplace: '取代',
    skillPasteCancel: '取消',
    skillPreviewName: '名稱',
    skillPreviewDescription: '描述',
    skillPreviewSize: '內容 {count} 字',
    skillTextLabel: '技能內容',
    skillDetailsSize: '內容',
    skillDetailsSource: '來源',
    skillSizeChars: '{count} 字',
    skillErr_empty: '還沒有貼上內容。',
    skillErr_text_too_long: '內容太長了。',
    skillErr_no_header: '開頭要有一段用 --- 圍起來的標頭，裡面寫 name 和 description。',
    skillErr_header_unclosed: '標頭沒有結束：標頭後面要再有一行 ---。',
    skillErr_header_invalid: '標頭的格式不對：每一行要寫成「名稱: 內容」。',
    skillErr_name_missing: '標頭裡沒有 name。',
    skillErr_name_invalid: 'name 只能用小寫英文字母、數字和連字號，最長 64 字，不能以連字號開頭或結尾。',
    skillErr_description_missing: '標頭裡沒有 description。',
    skillErr_description_too_long: 'description 最長 1024 字。',
    skillErr_body_empty: '標頭後面沒有技能的內容。',
    skillErr_body_too_long: '技能的內容最長 20000 字。',
    skillErr_name_taken: '已經有同名的技能了。',
    skillErr_too_many: '技能最多 50 個，請先移除不用的。',
    skillErr_failed: '儲存失敗，請稍後再試。',
    skillErr_signed_out: '請先登入雲端帳號。',
    skillUpload: '上傳技能包',
    skillBundleTitle: '上傳技能包',
    skillBundleHint: '技能包是一個 zip：裡面要有 SKILL.md，也可以有 references/、scripts/ 等資料夾。下面是裡面所有的檔案，加入前請看過。',
    skillBundleWarning: '技能的內容會成為模型收到的指示。只加入你信任的來源，加入前請讀過全文。',
    skillBundleScriptsWarning: '這個技能包含腳本：模型可能會在伺服器的沙盒裡執行它們。沙盒沒有網路，但請確認你信任腳本的內容。',
    skillBundleFiles: '檔案（{count}）',
    skillBundleReading: '正在檢查技能包…',
    skillPreviewFiles: '{count} 個檔案',
    skillKindScript: '腳本',
    skillKindText: '文字',
    skillKindBinary: '其他',
    skillFileNoPreview: '這個檔案不是文字，無法顯示。',
    skillFileCut: '只顯示前 {count} 字。',
    skillFileLoading: '讀取中…',
    skillFileFailed: '讀不到這個檔案。',
    skillDetailsFiles: '檔案',
    skillErr_not_a_zip: '這不是有效的 zip 檔。',
    skillErr_zip_too_large: 'zip 檔最大 5 MB。',
    skillErr_bad_path: '有檔案的路徑不能用。',
    skillErr_blocked_file: '技能包裡不能有程式或安裝檔。',
    skillErr_symlink: '技能包裡不能有符號連結。',
    skillErr_duplicate_path: '有兩個檔案的路徑相同。',
    skillErr_too_many_files: '檔案最多 60 個。',
    skillErr_file_too_large: '單一檔案最大 2 MB。',
    skillErr_bundle_too_large: '全部檔案加起來最大 10 MB。',
    skillErr_skill_md_missing: '技能包裡找不到 SKILL.md。'
  },
  en: {
    skillsSearchPlaceholder: 'Search skills',
    skillsSoon: 'Skills are coming soon',
    skillsSoonNote: 'A skill teaches the model how to do one thing, step by step. Skills will appear here once they are available.',
    skillsNoneMine: 'No skills added yet.',
    skillsNoResults: 'No skills match your search.',
    skillsSectionMine: 'My skills',
    skillPaste: 'Paste a skill',
    skillSourceYours: 'Added by you',
    skillSourceOfficial: 'Official',
    skillAdded_notice: 'Skill “{name}” added.',
    skillRemoved_notice: 'Skill “{name}” removed.',
    skillsNeedAccount: 'Pasting or uploading a skill needs a cloud account: skills are kept in your account.',
    skillPasteTitle: 'Paste a skill',
    skillPasteHint: 'Paste the whole text of a SKILL.md: it starts with a header with name and description, and the skill itself follows.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: What it does and when to use it\n---\n\nSteps and how to do it…',
    skillPasteWarning: 'A skill becomes instructions the model receives. Only add what you trust, and read it all before adding.',
    skillPasteAdd: 'Add',
    skillPasteReplace: 'Replace',
    skillPasteCancel: 'Cancel',
    skillPreviewName: 'Name',
    skillPreviewDescription: 'Description',
    skillPreviewSize: '{count} characters of text',
    skillTextLabel: 'The skill',
    skillDetailsSize: 'Text',
    skillDetailsSource: 'Source',
    skillSizeChars: '{count} characters',
    skillErr_empty: 'Nothing has been pasted yet.',
    skillErr_text_too_long: 'The text is too long.',
    skillErr_no_header: 'It must start with a header between lines of ---, with name and description.',
    skillErr_header_unclosed: 'The header is not closed: another line of --- must follow it.',
    skillErr_header_invalid: 'The header is not in the right form: each line is “name: value”.',
    skillErr_name_missing: 'The header has no name.',
    skillErr_name_invalid: 'A name uses lower-case letters, digits and hyphens only, up to 64 characters, and does not start or end with a hyphen.',
    skillErr_description_missing: 'The header has no description.',
    skillErr_description_too_long: 'A description is at most 1024 characters.',
    skillErr_body_empty: 'There is no skill text after the header.',
    skillErr_body_too_long: 'The text of a skill is at most 20000 characters.',
    skillErr_name_taken: 'A skill with this name already exists.',
    skillErr_too_many: 'At most 50 skills: remove one you do not use first.',
    skillErr_failed: 'Saving failed. Please try again later.',
    skillErr_signed_out: 'Sign in to your cloud account first.',
    skillUpload: 'Upload a skill pack',
    skillBundleTitle: 'Upload a skill pack',
    skillBundleHint: 'A skill pack is a zip with a SKILL.md in it, and optionally folders such as references/ and scripts/. Every file in it is listed below: read them before you add it.',
    skillBundleWarning: 'The text of a skill becomes instructions the model receives. Only add what you trust, and read it all before adding.',
    skillBundleScriptsWarning: 'This pack has scripts: the model may run them in the sandbox on the server. The sandbox has no network, but make sure you trust what the scripts do.',
    skillBundleFiles: 'Files ({count})',
    skillBundleReading: 'Checking the pack…',
    skillPreviewFiles: '{count} files',
    skillKindScript: 'Script',
    skillKindText: 'Text',
    skillKindBinary: 'Other',
    skillFileNoPreview: 'This file is not text and cannot be shown.',
    skillFileCut: 'Only the first {count} characters are shown.',
    skillFileLoading: 'Reading…',
    skillFileFailed: 'The file could not be read.',
    skillDetailsFiles: 'Files',
    skillErr_not_a_zip: 'This is not a valid zip file.',
    skillErr_zip_too_large: 'A zip file can be 5 MB at most.',
    skillErr_bad_path: 'A file has a path that cannot be used.',
    skillErr_blocked_file: 'A skill pack cannot hold programs or installers.',
    skillErr_symlink: 'A skill pack cannot hold links to other places.',
    skillErr_duplicate_path: 'Two files have the same path.',
    skillErr_too_many_files: 'At most 60 files.',
    skillErr_file_too_large: 'One file can be 2 MB at most.',
    skillErr_bundle_too_large: 'All the files together can be 10 MB at most.',
    skillErr_skill_md_missing: 'No SKILL.md was found in the pack.'
  },
  fr: {
    skillsSearchPlaceholder: 'Rechercher des compétences',
    skillsSoon: 'Les compétences arrivent bientôt',
    skillsSoonNote: 'Une compétence explique au modèle comment faire une tâche, étape par étape. Elles apparaîtront ici dès leur lancement.',
    skillsNoneMine: 'Aucune compétence ajoutée.',
    skillsNoResults: 'Aucune compétence ne correspond à votre recherche.',
    skillsSectionMine: 'Mes compétences',
    skillPaste: 'Coller une compétence',
    skillSourceYours: 'Ajoutée par vous',
    skillSourceOfficial: 'Officielle',
    skillAdded_notice: 'Compétence « {name} » ajoutée.',
    skillRemoved_notice: 'Compétence « {name} » retirée.',
    skillsNeedAccount: 'Coller ou importer une compétence demande un compte cloud : les compétences sont gardées dans votre compte.',
    skillPasteTitle: 'Coller une compétence',
    skillPasteHint: 'Collez tout le texte d’un SKILL.md : il commence par un en-tête avec name et description, puis vient la compétence.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: Ce qu’elle fait et quand l’utiliser\n---\n\nÉtapes et façon de faire…',
    skillPasteWarning: 'Une compétence devient des instructions reçues par le modèle. N’ajoutez que ce en quoi vous avez confiance, et lisez tout avant d’ajouter.',
    skillPasteAdd: 'Ajouter',
    skillPasteReplace: 'Remplacer',
    skillPasteCancel: 'Annuler',
    skillPreviewName: 'Nom',
    skillPreviewDescription: 'Description',
    skillPreviewSize: '{count} caractères de texte',
    skillTextLabel: 'La compétence',
    skillDetailsSize: 'Texte',
    skillDetailsSource: 'Source',
    skillSizeChars: '{count} caractères',
    skillErr_empty: 'Rien n’a encore été collé.',
    skillErr_text_too_long: 'Le texte est trop long.',
    skillErr_no_header: 'Le texte doit commencer par un en-tête entre deux lignes --- avec name et description.',
    skillErr_header_unclosed: 'L’en-tête n’est pas fermé : une autre ligne --- doit le suivre.',
    skillErr_header_invalid: 'L’en-tête n’a pas la bonne forme : chaque ligne est « nom: valeur ».',
    skillErr_name_missing: 'L’en-tête n’a pas de name.',
    skillErr_name_invalid: 'Un name n’utilise que des minuscules, des chiffres et des tirets, 64 caractères au plus, sans tiret au début ni à la fin.',
    skillErr_description_missing: 'L’en-tête n’a pas de description.',
    skillErr_description_too_long: 'Une description fait 1024 caractères au plus.',
    skillErr_body_empty: 'Il n’y a pas de texte de compétence après l’en-tête.',
    skillErr_body_too_long: 'Le texte d’une compétence fait 20000 caractères au plus.',
    skillErr_name_taken: 'Une compétence de ce nom existe déjà.',
    skillErr_too_many: '50 compétences au plus : retirez-en une que vous n’utilisez pas.',
    skillErr_failed: 'L’enregistrement a échoué. Réessayez plus tard.',
    skillErr_signed_out: 'Connectez-vous d’abord à votre compte cloud.',
    skillUpload: 'Importer un pack',
    skillBundleTitle: 'Importer un pack de compétence',
    skillBundleHint: 'Un pack est un zip qui contient un SKILL.md et, si vous voulez, des dossiers comme references/ et scripts/. Tous les fichiers sont listés ci-dessous : lisez-les avant d’ajouter.',
    skillBundleWarning: 'Le texte d’une compétence devient des instructions reçues par le modèle. N’ajoutez que ce en quoi vous avez confiance, et lisez tout avant d’ajouter.',
    skillBundleScriptsWarning: 'Ce pack contient des scripts : le modèle peut les exécuter dans le bac à sable du serveur. Il n’a pas de réseau, mais assurez-vous de faire confiance à ce que font les scripts.',
    skillBundleFiles: 'Fichiers ({count})',
    skillBundleReading: 'Vérification du pack…',
    skillPreviewFiles: '{count} fichiers',
    skillKindScript: 'Script',
    skillKindText: 'Texte',
    skillKindBinary: 'Autre',
    skillFileNoPreview: 'Ce fichier n’est pas du texte et ne peut pas être affiché.',
    skillFileCut: 'Seuls les {count} premiers caractères sont affichés.',
    skillFileLoading: 'Lecture…',
    skillFileFailed: 'Le fichier n’a pas pu être lu.',
    skillDetailsFiles: 'Fichiers',
    skillErr_not_a_zip: 'Ce n’est pas un fichier zip valide.',
    skillErr_zip_too_large: 'Un fichier zip fait 5 Mo au maximum.',
    skillErr_bad_path: 'Un fichier a un chemin inutilisable.',
    skillErr_blocked_file: 'Un pack ne peut contenir ni programme ni installateur.',
    skillErr_symlink: 'Un pack ne peut pas contenir de liens vers d’autres emplacements.',
    skillErr_duplicate_path: 'Deux fichiers ont le même chemin.',
    skillErr_too_many_files: '60 fichiers au maximum.',
    skillErr_file_too_large: 'Un fichier fait 2 Mo au maximum.',
    skillErr_bundle_too_large: 'L’ensemble des fichiers fait 10 Mo au maximum.',
    skillErr_skill_md_missing: 'Aucun SKILL.md dans le pack.'
  },
  ru: {
    skillsSearchPlaceholder: 'Поиск навыков',
    skillsSoon: 'Навыки скоро появятся',
    skillsSoonNote: 'Навык объясняет модели, как выполнить одну задачу, шаг за шагом. Здесь они появятся после запуска.',
    skillsNoneMine: 'Навыки ещё не добавлены.',
    skillsNoResults: 'Навыки по вашему запросу не найдены.',
    skillsSectionMine: 'Мои навыки',
    skillPaste: 'Вставить навык',
    skillSourceYours: 'Добавлен вами',
    skillSourceOfficial: 'Официальный',
    skillAdded_notice: 'Навык «{name}» добавлен.',
    skillRemoved_notice: 'Навык «{name}» удалён.',
    skillsNeedAccount: 'Чтобы вставить или загрузить навык, нужен облачный аккаунт: навыки хранятся в вашем аккаунте.',
    skillPasteTitle: 'Вставить навык',
    skillPasteHint: 'Вставьте весь текст файла SKILL.md: он начинается с заголовка с name и description, затем идёт сам навык.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: Что делает и когда использовать\n---\n\nШаги и способ выполнения…',
    skillPasteWarning: 'Навык становится инструкциями, которые получает модель. Добавляйте только то, чему доверяете, и прочтите всё перед добавлением.',
    skillPasteAdd: 'Добавить',
    skillPasteReplace: 'Заменить',
    skillPasteCancel: 'Отмена',
    skillPreviewName: 'Название',
    skillPreviewDescription: 'Описание',
    skillPreviewSize: 'Символов в тексте: {count}',
    skillTextLabel: 'Навык',
    skillDetailsSize: 'Текст',
    skillDetailsSource: 'Источник',
    skillSizeChars: 'Символов: {count}',
    skillErr_empty: 'Пока ничего не вставлено.',
    skillErr_text_too_long: 'Текст слишком длинный.',
    skillErr_no_header: 'Текст должен начинаться с заголовка между строками --- с name и description.',
    skillErr_header_unclosed: 'Заголовок не закрыт: после него нужна ещё одна строка ---.',
    skillErr_header_invalid: 'Заголовок написан неверно: каждая строка имеет вид «имя: значение».',
    skillErr_name_missing: 'В заголовке нет name.',
    skillErr_name_invalid: 'Name состоит только из строчных латинских букв, цифр и дефисов, до 64 символов, без дефиса в начале и в конце.',
    skillErr_description_missing: 'В заголовке нет description.',
    skillErr_description_too_long: 'Description — не более 1024 символов.',
    skillErr_body_empty: 'После заголовка нет текста навыка.',
    skillErr_body_too_long: 'Текст навыка — не более 20000 символов.',
    skillErr_name_taken: 'Навык с таким названием уже есть.',
    skillErr_too_many: 'Не более 50 навыков: сначала удалите ненужный.',
    skillErr_failed: 'Не удалось сохранить. Попробуйте позже.',
    skillErr_signed_out: 'Сначала войдите в облачный аккаунт.',
    skillUpload: 'Загрузить пакет',
    skillBundleTitle: 'Загрузить пакет навыка',
    skillBundleHint: 'Пакет навыка — это zip с файлом SKILL.md и, при желании, папками вроде references/ и scripts/. Ниже перечислены все файлы: прочтите их перед добавлением.',
    skillBundleWarning: 'Текст навыка становится инструкциями, которые получает модель. Добавляйте только то, чему доверяете, и прочтите всё перед добавлением.',
    skillBundleScriptsWarning: 'В пакете есть скрипты: модель может запускать их в песочнице на сервере. В песочнице нет сети, но убедитесь, что доверяете тому, что делают скрипты.',
    skillBundleFiles: 'Файлы ({count})',
    skillBundleReading: 'Проверяем пакет…',
    skillPreviewFiles: 'Файлов: {count}',
    skillKindScript: 'Скрипт',
    skillKindText: 'Текст',
    skillKindBinary: 'Другое',
    skillFileNoPreview: 'Этот файл не текстовый, его нельзя показать.',
    skillFileCut: 'Показаны только первые {count} символов.',
    skillFileLoading: 'Чтение…',
    skillFileFailed: 'Не удалось прочитать файл.',
    skillDetailsFiles: 'Файлы',
    skillErr_not_a_zip: 'Это не корректный zip-файл.',
    skillErr_zip_too_large: 'Размер zip-файла — не более 5 МБ.',
    skillErr_bad_path: 'У одного из файлов недопустимый путь.',
    skillErr_blocked_file: 'В пакете не может быть программ и установщиков.',
    skillErr_symlink: 'В пакете не может быть ссылок на другие места.',
    skillErr_duplicate_path: 'У двух файлов одинаковый путь.',
    skillErr_too_many_files: 'Не более 60 файлов.',
    skillErr_file_too_large: 'Один файл — не более 2 МБ.',
    skillErr_bundle_too_large: 'Все файлы вместе — не более 10 МБ.',
    skillErr_skill_md_missing: 'В пакете нет файла SKILL.md.'
  },
  es: {
    skillsSearchPlaceholder: 'Buscar habilidades',
    skillsSoon: 'Las habilidades llegarán pronto',
    skillsSoonNote: 'Una habilidad enseña al modelo a hacer una tarea paso a paso. Aparecerán aquí cuando estén disponibles.',
    skillsNoneMine: 'Aún no has añadido habilidades.',
    skillsNoResults: 'Ninguna habilidad coincide con tu búsqueda.',
    skillsSectionMine: 'Mis habilidades',
    skillPaste: 'Pegar una habilidad',
    skillSourceYours: 'Añadida por ti',
    skillSourceOfficial: 'Oficial',
    skillAdded_notice: 'Habilidad «{name}» añadida.',
    skillRemoved_notice: 'Habilidad «{name}» quitada.',
    skillsNeedAccount: 'Pegar o subir una habilidad requiere una cuenta en la nube: las habilidades se guardan en tu cuenta.',
    skillPasteTitle: 'Pegar una habilidad',
    skillPasteHint: 'Pega todo el texto de un SKILL.md: empieza con un encabezado con name y description, y luego va la habilidad.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: Qué hace y cuándo usarla\n---\n\nPasos y cómo hacerlo…',
    skillPasteWarning: 'Una habilidad se convierte en instrucciones que recibe el modelo. Añade solo lo que te inspire confianza y léelo todo antes de añadirlo.',
    skillPasteAdd: 'Añadir',
    skillPasteReplace: 'Reemplazar',
    skillPasteCancel: 'Cancelar',
    skillPreviewName: 'Nombre',
    skillPreviewDescription: 'Descripción',
    skillPreviewSize: '{count} caracteres de texto',
    skillTextLabel: 'La habilidad',
    skillDetailsSize: 'Texto',
    skillDetailsSource: 'Origen',
    skillSizeChars: '{count} caracteres',
    skillErr_empty: 'Todavía no se ha pegado nada.',
    skillErr_text_too_long: 'El texto es demasiado largo.',
    skillErr_no_header: 'Debe empezar con un encabezado entre líneas --- con name y description.',
    skillErr_header_unclosed: 'El encabezado no está cerrado: debe seguirle otra línea ---.',
    skillErr_header_invalid: 'El encabezado no tiene la forma correcta: cada línea es «nombre: valor».',
    skillErr_name_missing: 'El encabezado no tiene name.',
    skillErr_name_invalid: 'Un name usa solo minúsculas, dígitos y guiones, hasta 64 caracteres, sin guion al principio ni al final.',
    skillErr_description_missing: 'El encabezado no tiene description.',
    skillErr_description_too_long: 'Una description tiene como máximo 1024 caracteres.',
    skillErr_body_empty: 'No hay texto de la habilidad después del encabezado.',
    skillErr_body_too_long: 'El texto de una habilidad tiene como máximo 20000 caracteres.',
    skillErr_name_taken: 'Ya existe una habilidad con este nombre.',
    skillErr_too_many: 'Máximo 50 habilidades: quita una que no uses.',
    skillErr_failed: 'No se pudo guardar. Inténtalo más tarde.',
    skillErr_signed_out: 'Primero inicia sesión en tu cuenta en la nube.',
    skillUpload: 'Subir un paquete',
    skillBundleTitle: 'Subir un paquete de habilidad',
    skillBundleHint: 'Un paquete es un zip con un SKILL.md y, si quieres, carpetas como references/ y scripts/. Abajo se listan todos los archivos: léelos antes de añadirlo.',
    skillBundleWarning: 'El texto de una habilidad se convierte en instrucciones que recibe el modelo. Añade solo lo que te inspire confianza y léelo todo antes de añadirlo.',
    skillBundleScriptsWarning: 'Este paquete tiene scripts: el modelo puede ejecutarlos en el entorno aislado del servidor. No tiene red, pero asegúrate de confiar en lo que hacen los scripts.',
    skillBundleFiles: 'Archivos ({count})',
    skillBundleReading: 'Comprobando el paquete…',
    skillPreviewFiles: '{count} archivos',
    skillKindScript: 'Script',
    skillKindText: 'Texto',
    skillKindBinary: 'Otro',
    skillFileNoPreview: 'Este archivo no es de texto y no se puede mostrar.',
    skillFileCut: 'Solo se muestran los primeros {count} caracteres.',
    skillFileLoading: 'Leyendo…',
    skillFileFailed: 'No se pudo leer el archivo.',
    skillDetailsFiles: 'Archivos',
    skillErr_not_a_zip: 'No es un archivo zip válido.',
    skillErr_zip_too_large: 'Un archivo zip puede tener 5 MB como máximo.',
    skillErr_bad_path: 'Un archivo tiene una ruta que no se puede usar.',
    skillErr_blocked_file: 'Un paquete no puede contener programas ni instaladores.',
    skillErr_symlink: 'Un paquete no puede contener enlaces a otros lugares.',
    skillErr_duplicate_path: 'Dos archivos tienen la misma ruta.',
    skillErr_too_many_files: 'Máximo 60 archivos.',
    skillErr_file_too_large: 'Un archivo puede tener 2 MB como máximo.',
    skillErr_bundle_too_large: 'Todos los archivos juntos pueden tener 10 MB como máximo.',
    skillErr_skill_md_missing: 'No se encontró SKILL.md en el paquete.'
  }
});

/** One text in a language (English when the language lacks it), with {name} and {count} placeholders filled. */
export function skillText(language, key, values = {}) {
  const table = SKILL_TEXTS[language] || SKILL_TEXTS.en;
  const template = table[key] ?? SKILL_TEXTS.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (values[name] === undefined ? match : String(values[name])));
}
