// The words of the skills part of the Extensions page (the list, the window that takes a pasted skill, the notices and the reasons a skill is refused) in the
// app's five languages. Apart from the other words of the page (cli-texts.js) because they are only needed when the page is opened. {name} and {count}
// placeholders are filled by skillText.

export const SKILL_TEXTS = Object.freeze({
  'zh-TW': {
    skillsSearchPlaceholder: '搜尋技能',
    skillsSoon: '技能即將推出',
    skillsSoonNote: '技能是教模型怎麼做一件事的說明與流程，上架後會出現在這裡。',
    skillsNoneMine: '還沒有加入任何技能。',
    skillsNoResults: '找不到符合的技能。',
    skillsSectionMine: '我的技能',
    skillPaste: '貼上技能',
    skillSourceYours: '你自己加入的',
    skillSourceOfficial: '官方',
    skillAdded_notice: '已加入技能「{name}」。',
    skillRemoved_notice: '已移除技能「{name}」。',
    skillsNeedAccount: '貼上技能需要先登入雲端帳號，技能會存在你的帳號裡。',
    skillPasteTitle: '貼上技能',
    skillPasteHint: '貼上 SKILL.md 的完整文字：開頭要有 name 與 description，下面是技能的內容。',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: 做什麼、什麼時候用\n---\n\n步驟與做法……',
    skillPasteWarning: '技能的內容會成為模型收到的指示。只加入你信任的內容，加入前請讀過全文。',
    skillPasteAdd: '加入',
    skillPasteReplace: '取代',
    skillPasteCancel: '取消',
    skillPreviewName: '名稱',
    skillPreviewDescription: '描述',
    skillPreviewSize: '內容 {count} 字',
    skillTextLabel: '技能內容',
    skillDetailsSize: '內容',
    skillDetailsSource: '來源',
    skillSizeChars: '{count} 字',
    skillErr_empty: '還沒有貼上內容。',
    skillErr_text_too_long: '內容太長了。',
    skillErr_no_header: '開頭要有一段用 --- 圍起來的標頭，裡面寫 name 和 description。',
    skillErr_header_unclosed: '標頭沒有結束：標頭後面要再有一行 ---。',
    skillErr_header_invalid: '標頭的格式不對：每一行要寫成「名稱: 內容」。',
    skillErr_name_missing: '標頭裡沒有 name。',
    skillErr_name_invalid: 'name 只能用小寫英文字母、數字和連字號，最長 64 字，不能以連字號開頭或結尾。',
    skillErr_description_missing: '標頭裡沒有 description。',
    skillErr_description_too_long: 'description 最長 1024 字。',
    skillErr_body_empty: '標頭後面沒有技能的內容。',
    skillErr_body_too_long: '技能的內容最長 20000 字。',
    skillErr_name_taken: '已經有同名的技能了。',
    skillErr_too_many: '技能最多 50 個，請先移除不用的。',
    skillErr_failed: '儲存失敗，請稍後再試。',
    skillErr_signed_out: '請先登入雲端帳號。'
  },
  en: {
    skillsSearchPlaceholder: 'Search skills',
    skillsSoon: 'Skills are coming soon',
    skillsSoonNote: 'A skill teaches the model how to do one thing, step by step. Skills will appear here once they are available.',
    skillsNoneMine: 'No skills added yet.',
    skillsNoResults: 'No skills match your search.',
    skillsSectionMine: 'My skills',
    skillPaste: 'Paste a skill',
    skillSourceYours: 'Added by you',
    skillSourceOfficial: 'Official',
    skillAdded_notice: 'Skill “{name}” added.',
    skillRemoved_notice: 'Skill “{name}” removed.',
    skillsNeedAccount: 'Pasting a skill needs a cloud account: skills are kept in your account.',
    skillPasteTitle: 'Paste a skill',
    skillPasteHint: 'Paste the whole text of a SKILL.md: it starts with a header with name and description, and the skill itself follows.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: What it does and when to use it\n---\n\nSteps and how to do it…',
    skillPasteWarning: 'A skill becomes instructions the model receives. Only add what you trust, and read it all before adding.',
    skillPasteAdd: 'Add',
    skillPasteReplace: 'Replace',
    skillPasteCancel: 'Cancel',
    skillPreviewName: 'Name',
    skillPreviewDescription: 'Description',
    skillPreviewSize: '{count} characters of text',
    skillTextLabel: 'The skill',
    skillDetailsSize: 'Text',
    skillDetailsSource: 'Source',
    skillSizeChars: '{count} characters',
    skillErr_empty: 'Nothing has been pasted yet.',
    skillErr_text_too_long: 'The text is too long.',
    skillErr_no_header: 'It must start with a header between lines of ---, with name and description.',
    skillErr_header_unclosed: 'The header is not closed: another line of --- must follow it.',
    skillErr_header_invalid: 'The header is not in the right form: each line is “name: value”.',
    skillErr_name_missing: 'The header has no name.',
    skillErr_name_invalid: 'A name uses lower-case letters, digits and hyphens only, up to 64 characters, and does not start or end with a hyphen.',
    skillErr_description_missing: 'The header has no description.',
    skillErr_description_too_long: 'A description is at most 1024 characters.',
    skillErr_body_empty: 'There is no skill text after the header.',
    skillErr_body_too_long: 'The text of a skill is at most 20000 characters.',
    skillErr_name_taken: 'A skill with this name already exists.',
    skillErr_too_many: 'At most 50 skills: remove one you do not use first.',
    skillErr_failed: 'Saving failed. Please try again later.',
    skillErr_signed_out: 'Sign in to your cloud account first.'
  },
  fr: {
    skillsSearchPlaceholder: 'Rechercher des compétences',
    skillsSoon: 'Les compétences arrivent bientôt',
    skillsSoonNote: 'Une compétence explique au modèle comment faire une tâche, étape par étape. Elles apparaîtront ici dès leur lancement.',
    skillsNoneMine: 'Aucune compétence ajoutée.',
    skillsNoResults: 'Aucune compétence ne correspond à votre recherche.',
    skillsSectionMine: 'Mes compétences',
    skillPaste: 'Coller une compétence',
    skillSourceYours: 'Ajoutée par vous',
    skillSourceOfficial: 'Officielle',
    skillAdded_notice: 'Compétence « {name} » ajoutée.',
    skillRemoved_notice: 'Compétence « {name} » retirée.',
    skillsNeedAccount: 'Coller une compétence demande un compte cloud : les compétences sont gardées dans votre compte.',
    skillPasteTitle: 'Coller une compétence',
    skillPasteHint: 'Collez tout le texte d’un SKILL.md : il commence par un en-tête avec name et description, puis vient la compétence.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: Ce qu’elle fait et quand l’utiliser\n---\n\nÉtapes et façon de faire…',
    skillPasteWarning: 'Une compétence devient des instructions reçues par le modèle. N’ajoutez que ce en quoi vous avez confiance, et lisez tout avant d’ajouter.',
    skillPasteAdd: 'Ajouter',
    skillPasteReplace: 'Remplacer',
    skillPasteCancel: 'Annuler',
    skillPreviewName: 'Nom',
    skillPreviewDescription: 'Description',
    skillPreviewSize: '{count} caractères de texte',
    skillTextLabel: 'La compétence',
    skillDetailsSize: 'Texte',
    skillDetailsSource: 'Source',
    skillSizeChars: '{count} caractères',
    skillErr_empty: 'Rien n’a encore été collé.',
    skillErr_text_too_long: 'Le texte est trop long.',
    skillErr_no_header: 'Le texte doit commencer par un en-tête entre deux lignes --- avec name et description.',
    skillErr_header_unclosed: 'L’en-tête n’est pas fermé : une autre ligne --- doit le suivre.',
    skillErr_header_invalid: 'L’en-tête n’a pas la bonne forme : chaque ligne est « nom: valeur ».',
    skillErr_name_missing: 'L’en-tête n’a pas de name.',
    skillErr_name_invalid: 'Un name n’utilise que des minuscules, des chiffres et des tirets, 64 caractères au plus, sans tiret au début ni à la fin.',
    skillErr_description_missing: 'L’en-tête n’a pas de description.',
    skillErr_description_too_long: 'Une description fait 1024 caractères au plus.',
    skillErr_body_empty: 'Il n’y a pas de texte de compétence après l’en-tête.',
    skillErr_body_too_long: 'Le texte d’une compétence fait 20000 caractères au plus.',
    skillErr_name_taken: 'Une compétence de ce nom existe déjà.',
    skillErr_too_many: '50 compétences au plus : retirez-en une que vous n’utilisez pas.',
    skillErr_failed: 'L’enregistrement a échoué. Réessayez plus tard.',
    skillErr_signed_out: 'Connectez-vous d’abord à votre compte cloud.'
  },
  ru: {
    skillsSearchPlaceholder: 'Поиск навыков',
    skillsSoon: 'Навыки скоро появятся',
    skillsSoonNote: 'Навык объясняет модели, как выполнить одну задачу, шаг за шагом. Здесь они появятся после запуска.',
    skillsNoneMine: 'Навыки ещё не добавлены.',
    skillsNoResults: 'Навыки по вашему запросу не найдены.',
    skillsSectionMine: 'Мои навыки',
    skillPaste: 'Вставить навык',
    skillSourceYours: 'Добавлен вами',
    skillSourceOfficial: 'Официальный',
    skillAdded_notice: 'Навык «{name}» добавлен.',
    skillRemoved_notice: 'Навык «{name}» удалён.',
    skillsNeedAccount: 'Чтобы вставить навык, нужен облачный аккаунт: навыки хранятся в вашем аккаунте.',
    skillPasteTitle: 'Вставить навык',
    skillPasteHint: 'Вставьте весь текст файла SKILL.md: он начинается с заголовка с name и description, затем идёт сам навык.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: Что делает и когда использовать\n---\n\nШаги и способ выполнения…',
    skillPasteWarning: 'Навык становится инструкциями, которые получает модель. Добавляйте только то, чему доверяете, и прочтите всё перед добавлением.',
    skillPasteAdd: 'Добавить',
    skillPasteReplace: 'Заменить',
    skillPasteCancel: 'Отмена',
    skillPreviewName: 'Название',
    skillPreviewDescription: 'Описание',
    skillPreviewSize: 'Символов в тексте: {count}',
    skillTextLabel: 'Навык',
    skillDetailsSize: 'Текст',
    skillDetailsSource: 'Источник',
    skillSizeChars: 'Символов: {count}',
    skillErr_empty: 'Пока ничего не вставлено.',
    skillErr_text_too_long: 'Текст слишком длинный.',
    skillErr_no_header: 'Текст должен начинаться с заголовка между строками --- с name и description.',
    skillErr_header_unclosed: 'Заголовок не закрыт: после него нужна ещё одна строка ---.',
    skillErr_header_invalid: 'Заголовок написан неверно: каждая строка имеет вид «имя: значение».',
    skillErr_name_missing: 'В заголовке нет name.',
    skillErr_name_invalid: 'Name состоит только из строчных латинских букв, цифр и дефисов, до 64 символов, без дефиса в начале и в конце.',
    skillErr_description_missing: 'В заголовке нет description.',
    skillErr_description_too_long: 'Description — не более 1024 символов.',
    skillErr_body_empty: 'После заголовка нет текста навыка.',
    skillErr_body_too_long: 'Текст навыка — не более 20000 символов.',
    skillErr_name_taken: 'Навык с таким названием уже есть.',
    skillErr_too_many: 'Не более 50 навыков: сначала удалите ненужный.',
    skillErr_failed: 'Не удалось сохранить. Попробуйте позже.',
    skillErr_signed_out: 'Сначала войдите в облачный аккаунт.'
  },
  es: {
    skillsSearchPlaceholder: 'Buscar habilidades',
    skillsSoon: 'Las habilidades llegarán pronto',
    skillsSoonNote: 'Una habilidad enseña al modelo a hacer una tarea paso a paso. Aparecerán aquí cuando estén disponibles.',
    skillsNoneMine: 'Aún no has añadido habilidades.',
    skillsNoResults: 'Ninguna habilidad coincide con tu búsqueda.',
    skillsSectionMine: 'Mis habilidades',
    skillPaste: 'Pegar una habilidad',
    skillSourceYours: 'Añadida por ti',
    skillSourceOfficial: 'Oficial',
    skillAdded_notice: 'Habilidad «{name}» añadida.',
    skillRemoved_notice: 'Habilidad «{name}» quitada.',
    skillsNeedAccount: 'Pegar una habilidad requiere una cuenta en la nube: las habilidades se guardan en tu cuenta.',
    skillPasteTitle: 'Pegar una habilidad',
    skillPasteHint: 'Pega todo el texto de un SKILL.md: empieza con un encabezado con name y description, y luego va la habilidad.',
    skillPastePlaceholder: '---\nname: my-skill\ndescription: Qué hace y cuándo usarla\n---\n\nPasos y cómo hacerlo…',
    skillPasteWarning: 'Una habilidad se convierte en instrucciones que recibe el modelo. Añade solo lo que te inspire confianza y léelo todo antes de añadirlo.',
    skillPasteAdd: 'Añadir',
    skillPasteReplace: 'Reemplazar',
    skillPasteCancel: 'Cancelar',
    skillPreviewName: 'Nombre',
    skillPreviewDescription: 'Descripción',
    skillPreviewSize: '{count} caracteres de texto',
    skillTextLabel: 'La habilidad',
    skillDetailsSize: 'Texto',
    skillDetailsSource: 'Origen',
    skillSizeChars: '{count} caracteres',
    skillErr_empty: 'Todavía no se ha pegado nada.',
    skillErr_text_too_long: 'El texto es demasiado largo.',
    skillErr_no_header: 'Debe empezar con un encabezado entre líneas --- con name y description.',
    skillErr_header_unclosed: 'El encabezado no está cerrado: debe seguirle otra línea ---.',
    skillErr_header_invalid: 'El encabezado no tiene la forma correcta: cada línea es «nombre: valor».',
    skillErr_name_missing: 'El encabezado no tiene name.',
    skillErr_name_invalid: 'Un name usa solo minúsculas, dígitos y guiones, hasta 64 caracteres, sin guion al principio ni al final.',
    skillErr_description_missing: 'El encabezado no tiene description.',
    skillErr_description_too_long: 'Una description tiene como máximo 1024 caracteres.',
    skillErr_body_empty: 'No hay texto de la habilidad después del encabezado.',
    skillErr_body_too_long: 'El texto de una habilidad tiene como máximo 20000 caracteres.',
    skillErr_name_taken: 'Ya existe una habilidad con este nombre.',
    skillErr_too_many: 'Máximo 50 habilidades: quita una que no uses.',
    skillErr_failed: 'No se pudo guardar. Inténtalo más tarde.',
    skillErr_signed_out: 'Primero inicia sesión en tu cuenta en la nube.'
  }
});

/** One text in a language (English when the language lacks it), with {name} and {count} placeholders filled. */
export function skillText(language, key, values = {}) {
  const table = SKILL_TEXTS[language] || SKILL_TEXTS.en;
  const template = table[key] ?? SKILL_TEXTS.en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (values[name] === undefined ? match : String(values[name])));
}
